### ISSUE TITLE
Calendar's selection is not updated when we change datepicker date using the API

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular#2574] opened 2018-09-10 05:47 UTC
### Description  
Calendar's selection is not updated when we change datepicker date using the API

### Steps to reproduce

1. Open [datepicker ](https://stackblitz.com/edit/datepicker-select-bug-cukzfm?file=app%2Fdatepicker-sample-4%2Fdatepicker-sample-4.component.ts) sample
2. Click on the `igx-datePicker` so the `igx-calendar` can be created and shown
3. datepicker value is updated thought the API on the onOpen event handler.
4. Calendar value is not updated due missing appropriate handler

### Result  
The selected calendar date is not tomorrow.

### Expected result  
The selected calendar date should reflect the selected datepicker date.

**Comment by Aleksandyr** [comment] 2018-10-05 08:06
Check the date value through the datepicker API not through the calendar API. Because when the calendar is closed it doesn't exists into the DOM.

**Comment by wnvko** [comment] 2019-07-23 15:00
This is expected behavior. To change the date in the calendar you should change your handler like this:

```
  open(evt) {
    var today = new Date();
    today.setDate(today.getDate() + 1);
    this.datePicker.calendar.selectDate(today);
  }
```

**Closed by wnvko** 2019-07-23 15:00 UTC
Labels: date-picker, feature-request, status: in-review
