### ISSUE TITLE
Bug - Row Editing - Focusing a deleted row cell does not exit row editing

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#2876] opened 2018-10-30 15:26 UTC
### Description  
When focusing a cell on a deleted row, the row editing overlay is not hidden and the row is not committed.

 * igniteui-angular version: 6.2.x
 * browser: All

### Steps to reproduce  

1. Open the 'Grid Row Editing' DevDemo, use the 'Grid with row editing and transactions' grid
2. Delete the **first row**
3. Start editing a cell in the **second row**
4. Without exiting edit mode, click on a cell in the **first row**

### Result  
The cell **does not** enter edit mode (expected)
The row edit overlay **is not** closed and the edit value **is not** committed (clicking cancel discards it)

### Expected result  
The cell **does not** enter edit mode (expected)
The row edit overlay **is** closed and the edit value **is** committed (clicking cancel discards it)

### Attachments  
![image](https://user-images.githubusercontent.com/24314672/47729021-1f060d80-dc68-11e8-9b53-ad48bde022d9.png)

**Comment by damyanpetev** [comment] 2018-10-30 15:38
Dupe of #2874

**Closed by damyanpetev** 2018-10-30 15:38 UTC
Labels: bug, grid, row-editing, version: 6.2.x
