### ISSUE TITLE
Typing a non-existing value in the search input does not disable the apply filter button.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#4018] opened 2019-02-26 08:19 UTC
## Description  
Typing a non-existing value in the search input does not disable the apply filter button.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run DEV demos
2. Navigate to Grid Column Moving sample
3. Open Excel filtering dropdown
4. Type a non-existing value in the search box, e.g. 'alll'.

## Result  
The list gets cleared but the "Apply" button stays enabled.

## Expected result  
The "Apply" button should get disabled as it does in MS Excel.

**Comment by SlavUI** [comment] 2019-02-26 10:03
@gedinakova I this is not a bug it should work like that because you have selected values before the search is performed. If you deselect all values and then do a search and the value you are searching is not present the button is disabled.

**Comment by gedinakova** [comment] 2019-02-26 11:29
@SlavUI Whatever the initial state is, pressing the Apply button does nothing, so it seems like the better UX is to disable it, as they do in MS Excel.

**Comment by tachojelev** [comment] 2019-07-25 12:45
@DaniMarinov , can you share your thoughts on this?

**Comment by DaniMarinov** [comment] 2019-07-25 13:11
IMO it's a bug and should behave like in MS Excel. It is not possible to Apply not existing value (in that way Apply is just closing the ESF dialog).

**Comment by DaniMarinov** [comment] 2020-02-05 13:24
In the scenario when a user:
1. Types a value in the search input
2. Then selects some of the filtered results
3. Change again the value in the search input that shows "there are no items in the list", but still have a selected value from the previous search

After the third step, the button Apply goes Disabled **but should be Enabled**, because still there are selected values from the previous search.

**Closed** 2020-02-06 12:59 UTC
Labels: bug, excel-style-filtering, grid, severity: low, status: not-a-bug, version: 7.2.x
