### ISSUE TITLE
igx-datePicker not properly vertically aligned in igx-grid

### ISSUE THREAD

**Issue by Hypenate** [IgniteUI/igniteui-angular#1518] opened 2018-06-12 07:25 UTC
### Description  
In a igx-grid, the igx-datePicker is aligned lower than rest of the controls/cells.

### Steps to reproduce  

1. Create a new  Angular UI project with everything in place
2. Add a igx-grid
3. Add a igxColumn with an ng-template that contains a igx-datePicker
4. Provide it with data
5. `ng serve`

### Result  
The igx-datePicker is placed lower then the rest of the items.

### Expected result  
The igx-datePicker is vertically aligned like al the rest.

### Attachments  
![image](https://user-images.githubusercontent.com/7478681/41275396-1499400c-6e21-11e8-9133-b3bdf2ea04fd.png)

I created a reproduction in my git:
[Link to reproduction](https://github.com/Hypenate/IgniteUI_issues/tree/datepickerInGridAlignment)

**Comment by zdrawku** [comment] 2018-06-12 08:31
@Hypenate I am closing this issue with reason duplicate, the missalignment is caused because of the label and issue #1519 is covering that part.

Thank you for the detailed and well formed issue, we can use it for reference if there is something unclear from #1519

**Comment by zdrawku** [comment] 2018-06-12 08:32
after further investigation it seems that the missalignment is caused by the flex container

**Closed** 2018-06-13 12:58 UTC
Labels: bug, date-picker, grid, severity: low, status: in-review
