### ISSUE TITLE
Cursor moving in text input on custom igx-grid toolbar

### ISSUE THREAD

**Issue by sddania** [IgniteUI/igniteui-angular#6937] opened 2020-03-19 16:20 UTC
## Description  

With the last version of ignite-ui, implementing a custom template of the igx-grid's toolbar and inserting an input text does not work the movement cursors (left, right)

## Steps to reproduce  

https://stackblitz.com/edit/angular-ffnknj?file=src%2Fapp%2Fgrid%2Fgrid-toolbar-sample%2Fgrid-toolbar-sample-4.component.html

on the stackblitz preview put the cursor focus on the text input on the igx-grid's toolbar and try to write something. If you try to use the cursor buttons left or right the cursor won't move.

## Expected result  
If you try to use the cursor buttons left or right the cursor will move.

**Comment by kdinev** [comment] 2020-03-23 10:17
@sddania Did this work as expected with previous versions?

**Comment by sddania** [comment] 2020-03-23 10:38
@kdinev I'm sorry but I have no memory of this :(

**Comment by kdinev** [comment] 2020-03-23 11:56
@sddania We will check that anyways. I was asking if I should directly mark it as regression, but I think it's not.

**Comment by 3phase** [comment] 2020-06-05 16:51
@sddania I am not able to reproduce the issue with the latest version of the product (9.1.0). Here's a [sample](https://angular-ffnknj-pudtaw.stackblitz.io) that I forked from yours and where I upgraded the igniteui-angular version. Therefore I will close the issue. If it persists after upgrading though, please reopen.

**Closed by 3phase** 2020-06-05 16:51 UTC
Labels: bug, grid, grid-toolbar, severity: medium, version: 9.0.x
