### ISSUE TITLE
igxDateRangePicker doesn't render in type reactive form scenario.

### ISSUE THREAD

**Issue by Marina-L-Stoyanova** [IgniteUI/igniteui-angular#14041] opened 2024-04-02 10:49 UTC
## Description  
Describe the issue.

 * igniteui-angular version: latest
 * browser: 

## Steps to reproduce  

1. Create a typed reactive form with igx-date-range-picker
2. Run the app

## Result  
An error message: No value accessor for form control 

## Expected result  
The control should work

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by RivaIvanova** [comment] 2024-04-04 10:38
I tried reproducing the described behavior with the following configuration:

```html
<form [formGroup]="registrationForm">
  <igx-date-range-picker formControlName="range">
      <label igxLabel>Select dates</label>
  </igx-date-range-picker>
</form>
```
```ts
interface User {
  range: FormControl<DateRange | null>;
}

@Component({
  selector: 'app-range-picker',
  standalone: true,
  imports: [IGX_DATE_RANGE_PICKER_DIRECTIVES, ReactiveFormsModule],
  templateUrl: './range-picker.component.html',
  styleUrl: './range-picker.component.scss',
})
export class RangePickerComponent {
  private dateRange: DateRange = {
    start: new Date(),
    end: new Date(new Date().setDate(new Date().getDate() + 5)),
  };

  public registrationForm: FormGroup<User> = new FormGroup<User>({
    range: new FormControl(this.dateRange, { validators: Validators.required }),
  });
}
```

On my side, everything works as expected and the `IgxDateRangePicker` is displayed successfully without any errors. I will close the issue since the described behavior cannot be reproduced.
![range-picker](https://github.com/IgniteUI/igniteui-angular/assets/49126110/52570c30-7357-419d-80d2-5f4a2b620f5f)

**Closed by RivaIvanova** 2024-04-04 10:38 UTC
Labels: :bug: bug, :eyes: status: in-review, :crown:  app-builder
