### ISSUE TITLE
Row drag error when try to Grid Row Reorder

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#9478] opened 2021-04-30 06:52 UTC
### Description  
I have used [this ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag) las example to be able to move the table rows but have encountered several problems. If I have a table and I speak another one inside a mat-dialog I have found that:

- When doing the drog it is shown below the dialog and therefore it does not appear in blue above the table as it should, although it does move the row correctly.
- If I drag a row from the dialog table and leave it on one of the rows of the table that is not in the drag, it adds it and this should not be the case.
 * igniteui-angular version: 10.2.20
 * browser: chrome

### Steps to reproduce  

1. Create a grid
2. Create another grid inside of a mat-dialog
3. Drag the row

### Result  
When moving the row inside the mat-dialog, the effect is not shown and is below it and is added in the grid that is outside the mat-dialog
### Expected result  
To be able to move the row inside the mat-dialog, that the effect is shown correctly and that the row is not added on the grid that is outside the mat-dialog

**Comment by dafo** [comment] 2021-05-18 08:05
@ssg127 
I tried to reproduce your issue, however I am not sure about your exact scenario. In a very basic demo, where I have two grids - one inside a material dialog and another one - that is not in a dialog - dropping a row in the grid that is inside the dialog is working as expected and the drag ghost is displayed correctly. Can you please provide a stackblitz example that demonstrates the problem?

**Comment by ssg127** [comment] 2021-05-31 11:50
@dafo yes, as soon as I can I upload an example to stackblitz so you can see the problem.

**Comment by ssg127** [comment] 2021-05-31 14:45
@dafo here is the [example](https://stackblitz.com/edit/github-kvkjr3-xtegvc). Click on Open Dialog and try to drag any row.

**Comment by dafo** [comment] 2021-06-01 09:35
Thank you for the example, @ssg127 !
In order to see the drag ghost above the grid that is inside the dialog - please set the z-index of the drag ghost to a higher value. Here is an [example ](https://stackblitz.com/edit/github-kvkjr3-2m3k6r?file=src%2Fapp%2Fgrid%2Fgrid-row-reorder-sample%2Fgrid-row-reorder.html)
About your second concern - that it is allowed to drop a row from the dialog to the grid outside the dialog - the reason is that you are showing the very same grid inside the dialog. And it has igxDrop directive set - allowing for dropping a row inside it. 
You can check [this demo](https://stackblitz.com/edit/github-kvkjr3-sxncec?file=src%2Fapp%2Fgrid%2Fgrid-row-reorder-sample%2Fgrid-row-reorder.html) that is based on your project - it uses a different grid inside the dialog that has igxDrop directive set. The grid outside the dialog does not have the directive so reordering is only allowed inside the dialog.

**Comment by ssg127** [comment] 2021-06-01 10:27
Thank you so much @dafo!
I need to use the same grid several times so I will add an id to differentiate them. If I don't want to overwrite igxRowDragGhost and make it the same, how could I put the z-index: 1000? Is there any class?

**Comment by ssg127** [comment] 2021-06-01 10:59
I found that adding this to global styles works:

`.igx-grid__tr--ghost {
  z-index: 1000 !important;
}`

**Comment by dafo** [comment] 2021-06-01 13:24
Yes, it is fine if you are OK with all drag ghost to have the same z-index.

**Comment by dafo** [comment] 2021-06-01 20:01
Closing the issue as resolved. However, let us know if you face any other doubts related to this scenario.

**Closed by dafo** 2021-06-01 20:01 UTC
Labels: bug, grid: row-drag, status: in-review
