### ISSUE TITLE
igx-grid - cell repeats switching edit mode during pressing the Enter key.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#2775] opened 2018-10-19 08:00 UTC
### Description  
Cell repeats switching edit mode during pressing the Enter key.

 * igniteui-angular version: 6.1.7, 6.2.0-beta.3
 * browser: N/A

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-editing-issue
2. Click a cell.
3. Press and hold down the Enter key for a while.

### Result  
A selected cell repeats switching edit mode during pressing the Enter key.

### Expected result  
A selected cell should not repeat switching edit mode during pressing the Enter key.

### Attachments  
https://stackblitz.com/edit/igx-grid-editing-issue

**Comment by nrobakova** [comment] 2018-10-22 10:42
This is by design. 
When a cell is selected and press Enter Key it opens in edit mode.
When a cell is opened in edit mode and press Enter key the edit mode closes and the cell is only selected.
If you hold the Enter key the cell start switching between edit mode and selected.
Here is the documentation:
https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Editing#end-user

**Comment by zdrawku** [comment] 2018-11-07 12:11
@tkiryu is there a convenient use case for this functionality?

**Comment by zdrawku** [comment] 2018-11-19 13:55
@tkiryu I am closing this issue with reason by-design.

**Closed by zdrawku** 2018-11-19 13:55 UTC
Labels: browser: firefox, cell-editing, severity: low, status: by-design, status: in-review
