### ISSUE TITLE
Nested IGX drag and drop

### ISSUE THREAD

**Issue by Mehraajbee** [IgniteUI/igniteui-angular#12764] opened 2023-03-14 11:35 UTC
## Question  
For questions, please use the `Discussions` tab of the repository!

This is implemented with material(CDK drag and drop). I need to implement same thing with igx drag and drop. please help me with the example and also the versions that will support nested drag and drop

https://user-images.githubusercontent.com/97018502/224988691-e81df885-8c07-49cf-824c-f76f828292f9.mp4

Angular version:
@angular/animations": "~11.2.14",
    "@angular/cdk": "^10.2.7",
    "@angular/common": "~11.2.14",
    "@angular/compiler": "~11.2.14",
    "@angular/core": "~11.2.14",
    "@angular/forms": "~11.2.14",
    "@angular/platform-browser": "~11.2.14",
    "@angular/platform-browser-dynamic": "~11.2.14",
    "@angular/router": "~11.2.14",
IGX versions:
     @infragistics/igniteui-angular": "11.0.15"
      "igniteui-angular-core": "^11.1.1",

**Comment by Mehraajbee** [comment] 2023-03-17 08:40
I have created a project with nested igx drag and drop which is not working as expected. Please refer the project for the below comments
- While dragging screening to the other position inside the same category ie. Idea Generation the category gets dragged.
- the elements inside the category(Idea Generation) does not get drop until I click the dragged element.

[nested-drag-drop.zip](https://github.com/IgniteUI/igniteui-angular/files/10999453/nested-drag-drop.zip)

**Comment by georgianastasov** [comment] 2023-03-17 08:50
Hello @Mehraajbee,

I have been looking into your question and I created a sample that is as identical as possible to the sample that was implemented in the video you provided.

What I could suggest as an approach is to use three nested elements for the containers, the cards and the items in the cards themselves. As such, elements are dynamically created with the *ngFor directive from given lists to allow swapping of container locations, transferring cards from one container to another, and removing items from cards within a container or placing an item inside a card. Lists are used to make it possible to remove an element from a list and add it to another list and then render it in the view as the given element.

The [igxDrag](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDragDirective.html) and [igxDrop](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDropDirective.html) directives are placed on each element, handling their events for the start of dragging - [dragStart](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDragDirective.html#dragStart), for the end of dragging - [dragEnd](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDragDirective.html#dragEnd), for [enter](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDropDirective.html#enter)ing a given element when dragging - enter, for leaving a given element - [leave](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDropDirective.html#leave), for dropping drag element in another element - [dropped](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDropDirective.html#dropped) and to create the ghost element that is being drawn - [ghostCreate](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDragDirective.html#ghostCreate). After handling these events, you will be able to implement your custom logic and how to container swapping, swapping cards between containers, or inserting and removing items.

The [igxDragIgnore](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDragIgnoreDirective.html) directive is also used to indicate which elements are itertractable and must ignore the drag behavior in order for certain events to occur on them, thus defining how three nested elements within each other can be dragged without execute the event for the parent elements as well.

In the given sample, when starting to drag an element, its id is taken, when entering an element, it is checked what type the element is according to its state or id, checking whether it is possible to drop the dredged element into this element, and this is accordingly indicates and check given boolean values. When leaving an element, the boolean values are unchecked, that is, we are already outside the element and the drop will not take place. At the end of dragging the element, we remove and clear given variables and also check whether a drop was made or not, and when dropping the element, the element is removed from its old list and added to its new list.

The given sample strictly based on a given custom logic according to which the ids and states of the elements from the view and of the items themselves from the given lists are taken to indicate what is the dredged element and what is the target element whether they are containers, cards or items and according it implements doping and moving elements and whether these operations are possible.

As for the realization of the given sample, there is a possibility of variations, and it is determined according to your custom logic. [Here](https://stackblitz.com/edit/angular-rkqljl-kpjgpt?file=src/app/drag-drop/kanban-sample/drag-and-drop-sample.component.html) you can find the prepared sample that illustrates this behavior and implements this approach. Additionally, you can find detailed information about the igxDrag and igxDrop directives in [this topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/drag-drop) of our Angular documentation. Here you can find all the properties and events that can be handled by the [igxDrag](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDragDirective.html) directive and here you can find the rest of the properties and events from the [igxDrop](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxDropDirective.html) directive.

Please keep in mind that according to our [policy](https://github.com/IgniteUI/igniteui-angular/wiki/Ignite-UI-for-Angular-versioning#maintenance-and-support) igniteui-angular version ^11.0.15 is considered retired and it is no longer eligible for Developer Support Services, to achieve your requirement and take advantage of all introduced features and enhancements, I would suggest upgrading to the supported versions of igniteui-angular or latest version i.e. ^15.0.16.

The described scenario could be observed here:

https://user-images.githubusercontent.com/48180072/225854974-abf61b2c-51a9-444a-9e29-837491c660ea.mp4

**Comment by Mehraajbee** [comment] 2023-03-31 12:48
The elements inside the card is not working with the drag indicator. In the above example icon is hidden if the icon is visible the card also get's dragged with the element and the element does not work the way it should work.

**Comment by georgianastasov** [comment] 2023-04-03 13:13
Hello @Mehraajbee 

I have been looking into your question and I managed to reproduce the described behavior when the innermost nested elements have an igx-icon element with a drag indicator which, when trying to drag, triggers a drag event on the card itself and not on the innermost nested element. This will be investigated, and the described behavior will be determined as issue or feature request. Further updates regarding our investigation as they become available will be provided here. In order to receive a notification whenever a new information is available, please make sure that you are subscribed to this discussion. This can be achieved via the "Subscribe" button.

However, what I could suggest you as a workaround until providing new information about the described behavior is to remove the igx-icon element and handle the innermost nested element and create an after element for it. As this after element can contain for content the given icon drag indicator in the form of a picture and be further styled to be according to your preferences.

```
.element::after{
   content:url('dragg.png');
   display: block;
   width: 25px;
   height: 25px;
   color: black;
}
```

In this case, it will be a pseudo element located in the same place as a structural igx-icon element, but it will not trigger the drag event of the entire card, but only the innermost nested element will be dragged.

In addition, I have modified my previous sample illustrating this behavior which could be found [here](https://stackblitz.com/edit/angular-rkqljl-kpjgpt?file=src/app/drag-drop/kanban-sample/drag-and-drop-sample.component.html). 

Please keep in mind that according to our [policy](https://github.com/IgniteUI/igniteui-angular/wiki/Ignite-UI-for-Angular-versioning#maintenance-and-support) igniteui-angular version ^11.0.15 is considered retired and it is no longer eligible for Developer Support Services, to achieve your requirement and take advantage after changing this described behavior, I would suggest upgrading to the supported versions of igniteui-angular or latest version ^15.1.0.

The described scenario could be observed here:

https://user-images.githubusercontent.com/48180072/229519947-047ef40c-14e9-4c98-91c6-3b8bfde2a1d6.mp4

**Comment by skrustev** [comment] 2023-04-04 13:52
Marking this as a bug since this is an issue related to the nesting of IgxDrag directives that each level use an IgxDragHandle.

**Comment by radomirchev** [comment] 2023-06-05 08:23
@dkamburov do we have a progress on the bug?

**Comment by dkamburov** [comment] 2023-06-06 14:34
@skrustev Please let me know when this is ready for testing, I believe there were some things, that were cleared out with @damyanpetev

**Closed** 2023-07-07 08:32 UTC
Labels: :bug: bug, :question: question, :white_check_mark: status: resolved, awaiting author, drag-drop
