### ISSUE TITLE
The Date column is not formatted correctly - Grid Searching

### ISSUE THREAD

**Issue by alexalex972** [IgniteUI/igniteui-angular#1789] opened 2018-06-28 12:44 UTC
### Description  
When you type something in the search field in Grid Searching sample, the `Date` column breaks.

### Steps to reproduce  

1. Open the Grid Searching sample on staging.
2. Type something in the search field.
3. Observe the `Date` column

### Result  
The format of the `Date` column is lost.

### Expected result  
The format should not be lost.

### Attachments  
![gridsearch](https://user-images.githubusercontent.com/33548921/42034827-edfee926-7ae9-11e8-85cc-30555748e145.gif)

**Comment by SlavUI** [comment] 2018-06-28 13:06
Duplicate of #1769

**Closed by SlavUI** 2018-06-28 13:06 UTC
Labels: bug, grid, status: in-review
