### ISSUE TITLE
igx-select not closing automatically after selection on iOS 17.4 and 17.4.1

### ISSUE THREAD

**Issue by georgianastasov** [IgniteUI/igniteui-angular#14057] opened 2024-04-04 10:05 UTC
## Description  
The igx-select component are not functioning as expected on iOS versions 17.4 and 17.4.1. After selecting a value in the igx-select component, it automatically reopens and does not close, even when attempting to close it manually.

Angular version: ^17.1.2
Infragistics version: ^17.0.12
Affected devices: iPhone
Scenario: **Reported by customer**

## Steps to reproduce  

1. Navigate to a page containing igx-select component on an iPhone running iOS 17.4 or 17.4.1.
2. Select a value in the igx-select component.
3. Observe that the igx-select component automatically reopens and does not close.

[Overview Sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/select#angular-select-example)

## Result  
The igx-select component does not close automatically after selection on iOS 17.4 and 17.4.1.

## Expected result  
The igx-select component should close automatically after selection on all supported platforms, including iOS 17.4 and 17.4.1.

## Attachments  
https://github.com/IgniteUI/igniteui-angular/assets/48180072/0a6de1d0-526b-4843-a018-d026a740abea

**Comment by AkashJ-PP** [comment] 2024-04-12 05:51
Hi,
Any update on above?

**Comment by Lipata** [comment] 2024-04-12 08:43
@AkashJ-PP we will investigate the problem and will update you.

**Comment by Lipata** [comment] 2024-04-25 11:05
@AkashJ-PP should be duplicate of #14030. There is a problem with WebKit 17.4 that seems fixed in 17.5

**Closed** 2024-04-30 11:35 UTC
Labels: :bug: bug, :new: status: new, select, browser: Safari Mobile
