### ISSUE TITLE
MRL headers don't have correct hight in IE

### ISSUE THREAD

**Issue by MartinKamenov** [IgniteUI/igniteui-angular#4815] opened 2019-05-16 14:15 UTC
## Description  
In some cases the mrl header of a column is not visualized correctly in IE.

 * igniteui-angular version: 7.3.x
 * browser: IE

## Steps to reproduce 

1. Open mrl dev sample and add following column layout
```
<igx-column-layout [movable]="false" [pinned]="false" field='group0'>
                <igx-column [rowStart]="1" [colStart]="1" [rowEnd]="4" field="ContactName"></igx-column>
</igx-column-layout>
```
2. Open sample
3. Observe the "ContactName" header.

## Result  
Image from IE
![IEStyles2](https://user-images.githubusercontent.com/24592428/57860644-e55cb480-77fd-11e9-9309-3ac7d5b583be.PNG)

## Expected result 
Image from other browsers
![IEStyles1](https://user-images.githubusercontent.com/24592428/57860662-eab9ff00-77fd-11e9-8aeb-7350546414ab.PNG)

**Comment by skrustev** [comment] 2019-05-22 12:15
Possibly related to #4825

**Comment by MayaKirova** [comment] 2019-05-29 07:53
Duplicate of #4825

**Closed** 2019-05-29 08:31 UTC
Labels: bug, duplicate, grid, multi-row-layout, severity: low, version: 7.3.x
