### ISSUE TITLE
When cell is selected and then sorting is applied, cell selection is lost

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1010] opened 2018-04-16 13:23 UTC
### Description  
When cell is selected and then sorting is applied, cell selection is lost.

### Steps to reproduce  

1. Open the "Grid" demo sample.
2. Enable sorting on the "ID" column.
3. Select a cell.
4. Sort the "ID" column is descending order.

### Result  
Selection is lost.

### Expected result  
Selection should stay on the same cell, no matter which data operation is applied.

**Comment by rkaraivanov** [comment] 2018-04-16 13:45
Duplicate of #1005

**Closed** 2018-04-16 14:07 UTC
Labels: bug, duplicate, grid, severity: medium, version: 5.3.x
