### ISSUE TITLE
Misbehavior of Text Filtering's Autosuggestion on Pinned Column

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#6864] opened 2020-03-05 10:10 UTC
## Description  
A text filter, applied on a column that's pinned, won't show autosuggestion prior a click or other interaction with the component that'd invoke detectChanges() 

## Steps to reproduce  

1. Open either /gridFilterTemplate (which uses a custom filtering layout, but is cleaner to see) or /gridFiltering;
2. In case you opened the /gridFiltering sample, make sure to have the advanced filtering cleared (via the button below);  (_Edit_)
3. Enable column pinning (doesn't matter if it's left or right) and pin a certain column _using the API (Edit)_;
4. Type a single letter that exists in the column in the text filter;
5. Observe how the suggested columns won't change unless you interact with the grid or the filter box.

## Result  
Suggested columns not updating prior interacting w/ the component, the filter input lies into.

## Expected result  
Real-time updating of the suggestions

## Attachments  
![bug_2](https://user-images.githubusercontent.com/8365193/75971282-3b5c2f00-5eda-11ea-99d4-a14bde6311f6.gif)

![bug_2 2](https://user-images.githubusercontent.com/8365193/76523244-b8eee480-6470-11ea-9bd0-45a8568c3a88.gif)

**Comment by MayaKirova** [comment] 2020-03-05 16:16
@3phase Could be a duplicate of https://github.com/IgniteUI/igniteui-angular/issues/6220, which is already resolved. Could you check if the fix for it resolves this as well -https://github.com/IgniteUI/igniteui-angular/pull/6221?

**Comment by 3phase** [comment] 2020-03-06 08:58
> @3phase Could be a duplicate of #6220, which is already resolved. Could you check if the fix for it resolves this as well -#6221?

@MayaKirova The fix proposed in #6221 is outdated since the fix of #6567 got merged.

**Comment by ChronosSF** [comment] 2020-03-12 16:11
Closing this as the new way to reproduce is simply astounding.

**Closed by ChronosSF** 2020-03-12 16:11 UTC
Labels: bug, column-pinning, filtering, severity: low, status: resolved
