### ISSUE TITLE
The container for the horizontal scrollbar is always visible

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#925] opened 2018-04-05 12:13 UTC
### Description  
Describe the issue.
The horizontal scroll container is always visible, even if scroll bar is not necessary 

### Steps to reproduce  
Place a grid on the page

### Result
![capture](https://user-images.githubusercontent.com/14248932/38365024-79f0a5b2-38e3-11e8-8956-d1ff34494762.PNG)

Use the attached sample or any other to verify two scenarios:

- [x] Grid width is set
- [x] Grid width is not set

In both cases grid should display horizontal scrollbar if total columns width exceeds the grid width.

[igx-grid-app.zip](https://github.com/IgniteUI/igniteui-angular/files/1931811/igx-grid-app.zip)

**Comment by SlavUI** [comment] 2018-04-25 10:49
Closing as the issue is resolved

**Closed by SlavUI** 2018-04-25 10:49 UTC
Labels: bug, grid, status: resolved, version: 5.3.x
