### ISSUE TITLE
Filtering UI is building a different tree depending on the filtering operator

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#3713] opened 2019-01-24 10:14 UTC
### Description  
The filtering UI is building a different FilteringExpressionTree depending on the filtering operator when adding multiple filters for a single column.
 * igniteui-angular version: 7.2.1

### Steps to reproduce  

1. Go to https://stackblitz.com/angular/lpyqqjvgvqg
2. Add a handler for the onFilteringDone event.
3. Set two filters on the Product Name column, does not matter what.
4. Breakpoint on the filteringDone event listener
5. Change the filtering operator from the default AND to OR and see what is the current filtering expression tree:
![or](https://user-images.githubusercontent.com/14248932/51671181-055b3480-1fd1-11e9-93d6-48f1c28de115.PNG)

6. Change the filtering operator to AND and see what is the current filtering expression tree:
![and](https://user-images.githubusercontent.com/14248932/51671208-1310ba00-1fd1-11e9-8dc9-e36f838c55eb.PNG)

Result:
When the filtering operator is AND, this.grid1.filteringExpressionsTree.filteringOperands[0].filteringOperands returns an array of **FilteringExpressionTree** object.

When the filtering operator is OR, this.grid1.filteringExpressionsTree.filteringOperands[0].filteringOperands returns an array of **FilteringExpression** objects.

**Comment by DiyanDimitrov** [comment] 2019-05-09 08:26
Closing this as by design. We create an expression subtree for the AND operation since it has a higher priority than the OR operation.

**Closed by DiyanDimitrov** 2019-05-09 08:26 UTC
Labels: bug, filter-ui, severity: low, status: by-design, version: 7.2.x
