### ISSUE TITLE
Mispositioned ripple on item checkboxes

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#5474] opened 2019-07-22 13:48 UTC
## Description  
When you select an item in the grid's excel-style-filtering/column-hiding dropdown list, the ripple indicator does not appear as expected.

 * igniteui-angular version: 8.0.x
 * browser: n/a

## Steps to reproduce  

1. Open [this](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel_style_filtering.html) or [this](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column_hiding.html) topics.
2. On the first demo open the excel-style-filtering/column-hiding dropdowns.
3. Select an item in the dropdown by clicking on its checkbox.
4. Observe.

## Result  
The ripple does not appear in the checkbox that was just selected but a little to the left.

## Expected result  
The ripple should appear in the checkbox.

## Attachments  

![Annotation 2019-07-22 163639](https://user-images.githubusercontent.com/16020256/61637142-ac2e3e00-ac9f-11e9-8828-1ea3a1a7cc98.png)
![Annotation 2019-07-22 164203](https://user-images.githubusercontent.com/16020256/61637143-acc6d480-ac9f-11e9-8e30-d237152db294.png)

**Comment by DiyanDimitrov** [comment] 2019-07-22 13:52
Duplicate of #5243

**Closed by DiyanDimitrov** 2019-07-22 13:52 UTC
Labels: bug, column-hiding, excel-style-filtering, severity: low, version: 8.0.x
