### ISSUE TITLE
IgxDatePicker does not reset its state upon resetForm

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#9526] opened 2021-05-13 07:04 UTC
### Description  
IgxDatePicker does not reset its state upon resetForm. Is there any configuration missing in the implementation?

 * igniteui-angular version: 11.1.10
 * browser: n/a

### Steps to reproduce  
1. Run the sample (https://stackblitz.com/edit/github-yrdu1t-uv6ki9?file=src%2Fapp%2Fscheduling%2Fdatepicker%2Fdatepicker-sample-6%2Fdatepicker-sample-6.component.html)
2. Input date on IgxDatePicker
3. Enter any string on IgxInput
4. Manually clear values on IgxDatePicker and IgxInput
5. Click "RESET FORM" button

### Result  
IgxDatePicker remain its required error.

### Expected result  
Required error on IgxDatePicker is cleared.

### Note
If we skip the step 4, the error state of the IgxDatePicker is cleared.

### Attachment
![IgxDatePicker_behavior](https://user-images.githubusercontent.com/14340675/118090620-be451780-b404-11eb-9553-fcff9406ba99.gif)

**Comment by ymita** [comment] 2021-05-17 04:22
@Lipata, @jackofdiamond5 
Is there a workaround for this issue?

**Comment by jackofdiamond5** [comment] 2021-05-18 14:39
@ymita This is a bug that reproduces in `12.0` as well, so we will fix it in all supported versions.

**Comment by ymita** [comment] 2021-05-19 01:01
@jackofdiamond5 Thank you for the update. We have a customer who will stay in 11.1.x. For this customer, is there a workaround that we can provide?

**Comment by ymita** [comment] 2021-05-25 05:48
@Lipata , @jackofdiamond5 
Is there a workaround for this issue? If there is no feasible workaround, would you kindly let me know?

**Comment by Lipata** [comment] 2021-05-25 19:37
Hi, @ymita.

There is already a PR resolving that issue - we need to approve and verify it. There are going to have PRs also for 11.1.x and 10.2.x and we will work on finalizing them. Is it will be possible to apply a patch because there isn't a proper workaround?

**Comment by ymita** [comment] 2021-05-27 00:43
Hi @Lipata,

I am contacting to the customer if she can use 11.1.x that includes the fix. If I need further assistance with this, I will consult you!

**Closed** 2021-05-31 16:29 UTC
Labels: bug, date-picker, status: resolved, version: 10.2.x, version: 11.1.x, version: 12.0.x
