### ISSUE TITLE
Localization (i18n) not available for grid filtering expressions

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular#1930] opened 2018-07-04 16:49 UTC
### Description  
Localization (i18n) is not available for grid filtering expressions

### Steps to reproduce  

1. Go to [Grid filtering example](https://stackblitz.com/angular/dmgarjpxqrd)

2. Click on filtering icon on Product Name column

### Result  
A select is shown with filtering options.

### Expected result  
That exists a localization (i18n) of grid filtering expressions

**Comment by lalo-mx** [comment] 2018-07-05 13:39
Thanks i will try to implement the suggested solution but my main concern is that i am seeing other labels that will have to be localized and overridden in its own component.

Will be possible to define a single localization file with all its correspondents keys to be translated by the users?

**Comment by kdinev** [comment] 2018-07-06 05:38
@lalo-mx We were waiting for the runtime localization feature of Angular to be finished in order to take advantage of it. It's been over 7 months now, although originally we had information it was going to be done by March of 2018. We provide the strings for overriding in the components as a workaround.

https://github.com/angular/angular/issues/16477

I see that the issue is assigned under "ivy" now, which means it would take a little while longer. If however, we provide our own solution now, which consolidates all locale strings and provides an injectable mechanism of retrieving them to the components, then in a few months we would probably have to scrap it and redo with the Angular runtime translations, or not be compliant with it.

**Comment by bkulov** [comment] 2018-10-03 07:19
As a workaround in the following issue it's described how the filtering conditions could be localized:
https://github.com/IgniteUI/igniteui-angular/issues/2067

**Comment by bkulov** [comment] 2018-11-09 07:50
There is a duplicate of this issue so I'm closing this one.
#1930

**Closed by bkulov** 2018-11-09 07:50 UTC
Labels: filter-ui, grid, i18n, status: third-party-issue

**Comment by bkulov** [comment] 2018-11-09 07:59
This is the help topic which describes how to create a custom filtering conditions. The same technique could be used to localize the filtering conditions. It needs to change the filtering expression text while preserving filtering logic.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_filtering.html#custom-filtering-operands
