### ISSUE TITLE
Error when setting the rowEditable property of a Tree Grid with flat data structure in code

### ISSUE THREAD

**Issue by ddaribo** [IgniteUI/igniteui-angular#9560] opened 2021-05-17 11:38 UTC
## Description  
For a Tree Grid with a flat data structure (having primaryKey and foreignKey properties), the following error is thrown when attempting to set the rowEditable property to "true" in code:
_TypeError: Cannot read property 'data' of undefined at IgxTreeGridComponent.refreshGridState (tree-grid.component.ts:516)_
The error does not occur for a Tree Grid  with an hierarchical data structure (no foreignKey property specified).

 * igniteui-angular version: 11.1.x
 * browser: any

## Steps to reproduce  

1. Open the following [sample](https://stackblitz.com/edit/igx-tree-grid-hierarchical-and-flat-roweditable-issue?file=src%2Fapp%2Ftree-grid-childdatakey-sample%2Ftree-grid-childdatakey-sample.component.html).
(The two Tree Grids initially have rowEditable set to "false")
2. [optional] Press "Enable row editing for hierarchical-structured tree grid" button to verify correct behavior of the first grid.
3. Press "Enable row editing for flat-structured tree grid" button.
4. Check the console.

## Result  
An error is thrown and the second Tree Grid does not become editable.

## Expected result  
The second Tree Grid to correctly reflect the change of the rowEditable property's value.

**Comment by gedinakova** [comment] 2021-05-17 11:46
I believe this is a duplicate of #9510

**Closed** 2021-05-17 14:16 UTC
Labels: bug, duplicate, grid: tree-grid, version: 11.1.x
