### ISSUE TITLE
Smoother Accordion expand/collapse transitions

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#11582] opened 2022-05-18 12:18 UTC
## Is your feature request related to a problem? Please describe.
When expanding/collapsing panels in an Accordion there's a noticeable jump that can be a bit jarring. While the content is animated, the additional margins in the expanded state are not and their sudden set causes the content to jump. See https://www.infragistics.com/products/ignite-ui-angular/angular/components/accordion#angular-accordion-example

Would be an improvement if we can make that transition smoother.

## Describe the solution you'd like
If there's a way to animate the margin alongside the expand/collapse animation - akin to `transition: margin <timing>`. From a quick test that almost works but the visual state of the margin is set too late for the CSS animation to work as intended, so there's a chance this might require tweaking of some component logic to accommodate

**Comment by desig9stein** [comment] 2022-05-19 06:27
This issue appears to be duplicate to [this one](https://github.com/IgniteUI/igniteui-angular/issues/10695)

**Comment by simeonoff** [comment] 2022-05-19 06:35
@desig9stein Is there an issue with providing a fix by introducing a transition property on the element that animates margin?

**Comment by desig9stein** [comment] 2022-05-19 06:44
@simeonoff the transition can be set. However, as @damyanpetev said the visual state of the margin is set too late and so there is a slide delay before the transition starts. If that can be fixed it should work.

**Comment by kdinev** [comment] 2022-05-20 08:57
Closing as duplicate of #10695

**Closed by kdinev** 2022-05-20 08:57 UTC
Labels: duplicate, enhancement, :white_check_mark: status: resolved, accordion
