### ISSUE TITLE
Excel Style Filter showing ARIA errors for color contrast

### ISSUE THREAD

**Issue by igdmdimitrov** [IgniteUI/igniteui-angular#10607] opened 2021-11-23 09:07 UTC
## Description  
Related to #10391 

Excel Style Filter showing ARIA errors for color contrast

 * igniteui-angular version: all
 * browser: any

## Steps to reproduce  

1. Install the Accessibility Insights extension for chrome
2. Open 'Grid Filtering' dev sample
3. Open Excel Style Filter for any column
4. Run the FastPass check from the extension menu

## Result  
Several ARIA errors are shown related to color contrast

## Expected result  
No ARIA errors should be shown for the excel style filter

## Attachments  
![image](https://user-images.githubusercontent.com/49060557/142995639-7553f252-da84-44dd-be9c-cde5601ee5d0.png)
![image](https://user-images.githubusercontent.com/49060557/142996326-0e0d69a8-79a4-48bb-840a-aec666c3cebe.png)

**Comment by StefanIvanov** [comment] 2021-11-23 09:54
This seems to be an issue for the Fluent theme if my observations are correct. Is it something reproducible across all themes or is specific to just that one?

**Comment by igdmdimitrov** [comment] 2021-11-23 13:24
> This seems to be an issue for the Fluent theme if my observations are correct. Is it something reproducible across all themes or is specific to just that one?

@StefanIvanov, there are errors on all themes. For example, this is on bootstrap:
![image](https://user-images.githubusercontent.com/49060557/143031436-df915656-f2ec-4266-b234-699e1f07af61.png)

**Comment by radomirchev** [comment] 2023-08-14 08:35
@igdmdimitrov is the issue still reproducible?

**Comment by igdmdimitrov** [comment] 2023-08-21 14:37
@radomirchev, currently there are no errors for the Excel Style Filter related to color contrast. However there are other errors for color contrast in grid headers:
![image](https://github.com/IgniteUI/igniteui-angular/assets/49060557/2e81ad56-fec4-4754-8c81-701ee5e0139a)

**Comment by radomirchev** [comment] 2023-08-28 08:24
@igdmdimitrov in that case we can close the issue

**Closed by radomirchev** 2023-08-28 08:24 UTC
Labels: :bug: bug, :new: status: new, grid: excel-style-filtering, aria-support
