### ISSUE TITLE
Not able to move column that has ngTemplate and custom cell formatting or use of custom cell template

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#8896] opened 2021-02-03 11:20 UTC
@hanastasov 
## Description  
Cannot Move column that has custom information i.e if used ngtemplate and igxCell to describe the cell data.
its happening even in the example on your website.
https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-moving-styled-sample

Try moving column Change and Change (%) => you wont be able to.

Please can you solve this ASAP or let me know if you need more information.

 * igniteui-angular version: 11.0.12
 * browser: google-chrome: Version 88.0.4324.104 (Official Build) (64-bit)

## Steps to reproduce  

https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-moving-styled-sample

Try moving column Change and Change (%) => you wont be able to.

**Comment by wnvko** [comment] 2021-02-04 06:59
I am not able to reproduce this in Google Chrome latest version 88.0.4324.146 (Official Build) (64-bit).
@amitmoondra can you try to update your browser and let us know if issue is reproducible in the latest Google Chrome?

**Comment by amitmoondra** [comment] 2021-02-07 09:45
Please check the video on this link, i upgraded the version and you will see the issue
this is i am sure a bug, please let me know what i need to do more
https://drive.google.com/file/d/1BebYp0XN9DLln9IGYFH6r0kU3A6AuSRZ/view?usp=sharing

**Comment by hanastasov** [comment] 2021-02-08 07:19
Hi @amitmoondra ,

Please check the information in #8129. Basically it is the same issue, and we assume the issue is a result of the way Angular resolves child queries. @rkaraivanov also suggested a template to workaround such issues. Please let us know if it helps.

**Comment by amitmoondra** [comment] 2021-02-08 11:52
Hi @hanastasov ,
I will check the solution. Thanks

**Comment by amitmoondra** [comment] 2021-02-12 13:43
@hanastasov,
The solution is good, but is there a way we can add more properties to column object, so we can actually make use of those properties in templates, that is the work around. In current way a lot of things can be done, but in the workaround we cannot access all properties of column objects that are not not needed by igx-column but can be added to column and used while looping the column objects, I dont want to add more dynamic functions as that would significantly slow down the grid performance.

**Comment by hanastasov** [comment] 2021-02-12 15:11
> @hanastasov,
> The solution is good, but is there a way we can add more properties to column object, so we can actually make use of those properties in templates, that is the work around. In current way a lot of things can be done, but in the workaround we cannot access all properties of column objects that are not not needed by igx-column but can be added to column and used while looping the column objects, I dont want to add more dynamic functions as that would significantly slow down the grid performance.

Hi, you must be able to add any property, just like shown:

`<div class="grid-wrapper">
  <igx-grid #grid1 [data]="data" height="400px" width="100%" [autoGenerate]="false">
    <ng-container *ngFor="let column of columns">
      <ng-container *ngIf="!column.isGroupHeader">
        <igx-column [field]="column.fieldKey" [header]="column.headerText" [dataType]="column.dataType"
          [headerTemplate]="headerTemplate" [cellTemplate]="cellTemplate" [movable]="column.movable"
          [pinned]="column.pinned">
        </igx-column>
      </ng-container>
      <ng-container *ngIf="column.isGroupHeader">
        <igx-column-group [header]="column.headerText" [movable]="column.movable" [pinned]="column.pinned">
          <igx-column *ngFor="let c of column.columns" [field]="c.fieldKey" [dataType]="c.dataType"
            [header]="c.headerText" [headerTemplate]="headerTemplate" [cellTemplate]="cellTemplate"
            [movable]="c.movable" [pinned]="c.pinned">
          </igx-column>
        </igx-column-group>
      </ng-container>
    </ng-container>
  </igx-grid>
</div>

<ng-template let-column #headerTemplate>
  <div>{{ column.header }}</div>
</ng-template>
<ng-template let-value #cellTemplate>
  <div>{{ value }}</div>
</ng-template>`

**Comment by amitmoondra** [comment] 2021-02-12 15:13
some custom properties, that is just for our custom use as we customize the grid.

**Comment by hanastasov** [comment] 2021-02-12 15:21
You will be able to set only what `igxColumnComponen`  exposes as properties. DO you mean thta you have a wrapper around the grid or the column that you want to pass custom properies?

**Comment by amitmoondra** [comment] 2021-02-12 15:24
have wrapper around columns exactly, in our case.
so igx-column tag is within a loop as we create lots of columns depending upon users view/choice => so that actually facilitated to use more properties other than just igx-grid-column restrictive props.
But now with this template way there is no way to do that same.
I hope you understand now ?

**Comment by rkaraivanov** [comment] 2021-02-15 07:42
@amitmoondra 
Sounds like you need a input to provide additional template context from the column...
For example something along the lines of :

```html
    <igx-column [templateContext]="contextObject">
        <ng-template igxCell let-cell="cell">
            {{ cell.column.contextObject.prop }}
        </ng-template>
    </igx-column>
```
Is this the use case you are targetting?

**Comment by amitmoondra** [comment] 2021-02-15 10:34
> @amitmoondra
> Sounds like you need a input to provide additional template context from the column...
> For example something along the lines of :
> 
> ```
>     <igx-column [templateContext]="contextObject">
>         <ng-template igxCell let-cell="cell">
>             {{ cell.column.contextObject.prop }}
>         </ng-template>
>     </igx-column>
> ```
> 
> Is this the use case you are targetting?

This is exactly what i was looking for, thanks, i think i will achieve any functionality using this particular way.
Thank you, will comment here once this way works

**Comment by rkaraivanov** [comment] 2021-02-15 12:09
@amitmoondra 
In that case, I suggest that we close this issue and open a new feature request as currently you cannot achieve this functionality

@radomirchev 
Should I open a new feature request for this or should I leave to you?

**Comment by amitmoondra** [comment] 2021-02-15 12:15
Yeah please create one and mark it as high priority, this needs to be done, its very important, so that we can customize the grid to the maximum.

**Comment by radomirchev** [comment] 2021-02-18 13:26
@rkaraivanov Please, create a new one. Thank you!

**Comment by rkaraivanov** [comment] 2021-02-18 13:36
@amitmoondra 
I'm closing this issue. You can follow the feature request [here](https://github.com/IgniteUI/igniteui-angular/issues/9020)

**Closed by rkaraivanov** 2021-02-18 13:36 UTC
Labels: browser: chrome, grid: column-moving, question, status: in-review, version: 11.0.x
