### ISSUE TITLE
IgxDisplay Container is not recalculated correctly

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#2054] opened 2018-07-19 12:08 UTC
### Steps to reproduce  

1.Open Grid Summary Sample (the paging should be disabled and all columns should be fully visible)
2. Scroll to bottom
3. Click on the button **Hide**

### Result  
![screenshot_22](https://user-images.githubusercontent.com/34240583/42931007-36d07300-8b47-11e8-8a40-d7774bf5b79f.png)

### Expected result  
![screenshot_23](https://user-images.githubusercontent.com/34240583/42931024-3f48add6-8b47-11e8-843a-c986bf820006.png)

**Comment by skrustev** [comment] 2018-07-23 15:01
This seems to be reproduced only on Chrome when the page is zoomed in for example on 110%.

**Comment by skrustev** [comment] 2018-07-24 16:01
Since the sample above is not yet merged different steps to reproduce this are:

1. Open the summaries sample.
2. Set the grid height to 500px, width to 1200px.
3. Zoom in on the page.
4.. Click on `Enable summary..` button
5. Scroll to bottom.
6. Click on `Enable summary..` button again

**Closed** 2018-07-25 10:47 UTC
Labels: bug, grid, severity: medium, status: resolved, virtualization
