### ISSUE TITLE
Grid with DefaultSortingStrategy throws error

### ISSUE THREAD

**Issue by georgianastasov** [IgniteUI/igniteui-angular#14592] opened 2024-07-26 13:38 UTC
## Description  
When using DefaultSortingStrategy with any grid component (igx-grid, igx-tree-grid, igx-hierarchical-grid), an error occurs in the console related to sorting functionality.

 * igniteui-angular version: 17.2 18.1 master
 * browser: all

## Steps to reproduce  

1. Create a grid component (igx-grid, igx-tree-grid, or igx-hierarchical-grid) in your Angular application.

2. Add the following sorting strategy to your component class:
`public defaultSortingStrategy = DefaultSortingStrategy.instance();`

3. Bind the defaultSortingStrategy to the grid's [sortStrategy] property:
`<igx-grid #grid [data]="data" [sortStrategy]="defaultSortingStrategy">
`

4. Run the application and observe the console for errors.

## Result  
An error is thrown in the console:
```
ERROR TypeError: Cannot read properties of undefined (reading 'call')
    at _DefaultSortingStrategy.compareObjects (sorting-strategy.ts:85:31)
    at cmpFunc (sorting-strategy.ts:57:56)
    at Array.sort (<anonymous>)
    at _DefaultSortingStrategy.arraySort (sorting-strategy.ts:95:21)
    at _DefaultSortingStrategy.sort (sorting-strategy.ts:58:21)
    at _DataUtil.sort (data-util.ts:52:24)
    at _DataUtil.treeGridSort (data-util.ts:70:24)
    at data-util.ts:65:41
    at Array.forEach (<anonymous>)
    at _DataUtil.treeGridSort (data-util.ts:61:26)
```

## Expected result  
The grid should sort data correctly without any errors in the console.

**Comment by RivaIvanova** [comment] 2024-08-28 07:57
The [documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/sorting#sorting-through-the-api) states that:
![sorting-column-grid](https://github.com/user-attachments/assets/e25c1026-2372-4ac5-a071-340f33ebc17b)

The grid [`sortStrategy`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#sortStrategy) is of type [`IGridSortingStrategy`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IGridSortingStrategy.html) and the [`sort`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/IGridSortingStrategy.html#sort) method is as follows:
```ts
sort(data: any[], expressions: ISortingExpression[], grid?: GridType): any[]
```

The column [`sortStrategy`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxcolumncomponent.html#sortStrategy) is of type [`ISortingStrategy`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/ISortingStrategy.html) and the [`sort`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/interfaces/ISortingStrategy.html#sort) method is as follows:

```ts
sort: (
    data: any[],
    fieldName: string,
    dir: SortingDirection,
    ignoreCase: boolean,
    valueResolver: (obj: any, key: string, isDate?: boolean) => any,
    isDate?: boolean,
    isTime?: boolean,
    grid?: GridType
) => any[];
```

The [`DefaultSortingStrategy`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/DefaultSortingStrategy.html) implements the `ISortingStrategy` and its [`sort`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/DefaultSortingStrategy.html#sort) method requires the same parameters:
`sort(data, fieldName, dir, ignoreCase, valueResolver, isDate?, isTime?): any[]`

So the `DefaultSortingStrategy` cannot be assigned to the grid `sortStrategy` since they are of different types and the `DefaultSortingStrategy` is intended to be used on a column level not on the grid level.

If we proceed with the **Steps to reproduce**, the app cannot be run due to a compilation error which basically says the above.
![defaultSortingStrategy - column](https://github.com/user-attachments/assets/2cf84ee3-c1d2-4d15-847b-2da344857d76)

The equivalent of the `DefaultSortingStrategy` for the grid is the [`IgxSorting`](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/IgxSorting.html) class:
```ts
public defaultGridSortingStrategy = new IgxSorting();
public defaultColumnSortingStrategy = DefaultSortingStrategy.instance();
```
```html
<igx-grid [data]="data" [sortStrategy]="defaultGridSortingStrategy">
  <igx-column
    field="ID"
    [sortable]="true"
    [sortStrategy]="defaultColumnSortingStrategy"
  ></igx-column>
</igx-grid>
```

**Closed by RivaIvanova** 2024-08-28 07:57 UTC
Labels: :bug: bug, grid: sorting, :eyes: status: in-review
