### ISSUE TITLE
In carousel the active slide button does not have indication the it is selected

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2173] opened 2018-07-30 08:43 UTC
### Description  
In carousel the active slide button does not have indication the it is selected

### Steps to reproduce  

1. Open https://www.infragistics.com//angularsite/components/carousel.html#carousel-demo
2. Look at the carousel indicator buttons

### Result  
The active slide button looks similar as other buttons

### Expected result  
The active slide button should look as selected

![carouselcapture](https://user-images.githubusercontent.com/11463104/43386937-9bec5728-93d4-11e8-8720-a52db6aa9b53.PNG)

**Comment by simeonoff** [comment] 2018-08-14 08:14
@nrobakova @hanastasov The reason for this is because the background of the carousel in the sample is white - same as the active indicator. Unfortunately, the default carousel theme cannot cater to all scenarios. Developers are responsible for creating custom themes that match their requirements in terms of color and contrast.

Since this issue is not a bug, nor there is a problem with the theme in any way, I am closing it. The issue must be fixed on a sample level.

**Closed by simeonoff** 2018-08-14 08:14 UTC
Labels: carousel, status: by-design, status: not-to-fix, styling, version: 6.2.x
