### ISSUE TITLE
Scrolling issue with cellSelection = 'none' or cellSelection = 'single'

### ISSUE THREAD

**Issue by m4yorga** [IgniteUI/igniteui-angular#11395] opened 2022-04-13 16:56 UTC
## Description  
Dear Ignite, we have an issue with the master-detail grid when **[cellSelection]="'none'"** or **[cellSelection]="'single'"**.
Issue does not happen when  **[cellSelection]="'multiple'"**.
Please find the steps and details of the issue described below:

 * igniteui-angular version: 13.1.9
 * browser: all

## Steps to reproduce  

1. Expand any record to see its details
1. Scroll a little down so the expanded record is not visible, just its details component should be visible
1. Click on any other window different than your browser (Details component should lose focus)
1. Click back anywhere on the Details component  (Details component should gain focus)
1. As you can see, the vertical scrollbar moved up

The issue can be replicated [on this stackblitz](https://stackblitz.com/edit/angular-k7pshd-qyqvwi?file=src%2Fapp%2Fapp.component.html)

Also you can take a look at this gif that replicates the issue:
![Issue](https://user-images.githubusercontent.com/4580348/163231005-f797f36c-4219-4b2e-88e6-9f50cc15916d.gif)

## Result  
The vertical scrollbar moves up every time the Details component becomes activated/focused

## Expected result  
The vertical scrollbar should not move automatically

**Comment by MayaKirova** [comment] 2022-04-20 11:56
@dkamburov I don't think this is related to the master-detail grid.
It seems that depending on the selection mode (all except when mode is multiple) on focus of the grid body the last active element gets focus and is scrolled in view:
https://github.com/IgniteUI/igniteui-angular/blob/master/projects/igniteui-angular/src/lib/grids/grid-navigation.service.ts#L144

Same can be observed in any grid with cell selection, for example:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-selection#angular-cell-selection-example
If some cell is active, then is scrolled out of the view, on focus of the grid it gets scrolled back in view:
![scrollInView](https://user-images.githubusercontent.com/10397980/164223355-cccf56a7-42af-41d3-96ac-e651d3bad4e5.gif)

Seems to be the intended behavior since it has worked like this since 11.0.x, but maybe @hanastasov might have an idea whether this is the expected behavior or not.

**Comment by hanastasov** [comment] 2022-04-21 05:38
Thanks for the investigation @MayaKirova . Looking at the code  I also believe is expected , though it looks a bit unintuitive to me. @ddincheva do you remember the reason for this behavior anyway?

**Comment by m4yorga** [comment] 2022-04-21 10:55
Thanks @MayaKirova , @hanastasov , in case this is expected behavior, can we have a setting or any way to turn it off?

Thanks much for investigating.

**Comment by ddincheva** [comment] 2022-06-24 13:56
This behavior ensures that the selected node is in the view is intended .. and is related to the implementation of the tab navigation flow in the grid so this can not be avoided .. as a workaround, I can suggest you to clear the lastActiveNode which you can access from the grid navigation service .. when the grid loses focus .. and in this way, you will not experience this behavior .. also from the sample that you've linked I noticed, besides the scrolling that the master detailed cell is not activated on click which is fixed in the linked PRs
If you have any additional questions, just let me know.

**Closed** 2022-08-12 08:06 UTC
Labels: :bug: bug, :white_check_mark: status: resolved
