### ISSUE TITLE
ignite ui highlight directive custom color not changing

### ISSUE THREAD

**Issue by VivithaAlamur** [IgniteUI/igniteui-angular#5406] opened 2019-07-12 00:21 UTC
## Description  
I am using ignite ui highlight dirctive for find purpose.The matched text by default showing yellow and active text showing in orange color.We need to change the color of the matched and active test to our custom colors.

 * ignite-ui version: 
 * browser: 

## Steps to reproduce  

we used  [cssClass]="myClass" and   [activeCssClass]="activeHighlightClass" but those are not working

   <span class="display" igxTextHighlight [groupName]="'group1'" [row]='i'  [cssClass]="activeHighlightClass"  [activeCssClass]="activeHighlightClass" (click)="getRouterCatalogEventDetails(i,entity)" 
            [value]="entity.entity"><span   class="textsize display">{{entity.entity}}</span></span>

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by rkaraivanov** [comment] 2019-07-12 14:24
Duplicate of #5403

**Closed by rkaraivanov** 2019-07-12 14:24 UTC
Labels: global-search, status: in-review, text-highlight
