### ISSUE TITLE
Disable client side filtering when using remote filtering

### ISSUE THREAD

**Issue by Lightw3ight** [IgniteUI/igniteui-angular#5586] opened 2019-08-05 21:25 UTC
## Is your feature request related to a problem? Please describe.
Currently when trying to achieve remote filtering, client side filtering also runs on the data that is currently displayed before the remote data can be returned.
What this means is that if you enter a filter that does not match any items in the client side data, the grid will display a **No records found** message until the remote call completes and loads the new data into the grid.

You can see this in action if you go to the [remote filtering and sorting demo](https://stackblitz.com/angular/jxpgmdkgypd) and type in the letter _z_ into the filter field for the _ProductName_ column.

## Describe the solution you'd like
I would like a way to disable client filtering / sorting so it doesn't filter/sort the client data while server side data is being loaded
`[disableClientFiltering]="true"` and `[disableClientSorting]="true"`

## Describe alternatives you've considered
I thought I could just set `[isLoading]="true"` on the grid to show the loading template while I am fetching data, but this does not work when there is a filter active
I will be adding a custom overlay over the grid similar to the above demo for when I am loading data, however this does not hide the message **No records found** that the grid displays when data is being loaded

## Additional context
![image](https://user-images.githubusercontent.com/740446/62496080-f0871580-b82b-11e9-9182-ac875119772c.png)

**Comment by DiyanDimitrov** [comment] 2019-08-06 07:20
Closing as duplicate of #4356

**Closed by DiyanDimitrov** 2019-08-06 07:20 UTC
Labels: feature-request, filtering, grid
