### ISSUE TITLE
igx-grid - After filtering a column via filter method, filter dropdown icon is not highlighted. 

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#1153] opened 2018-04-24 10:45 UTC
### Description  
On igx-grid, after filtering a column via filter method, filter dropdown icon is not highlighted. 

### Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-method-issues
2. Click "FILTER" button.

### Result  
Filter dropdown icon is not highlighted. 

### Expected result  
Filter dropdown icon should be highlighted.

**Comment by SlavUI** [comment] 2018-04-25 10:37
@tkiryu i used the filter and in both cased the filter icons is changing it's color. On click it is highlighted with the circle but upon closing of the Filter it stays with a different color which is by design"
![filter 1](https://user-images.githubusercontent.com/33216749/39240886-cebbb60e-488d-11e8-9bc6-d79d8dceb957.PNG)
![filter 2](https://user-images.githubusercontent.com/33216749/39240890-d0d8ab4a-488d-11e8-824d-6ab4b19f5c86.PNG)

**Comment by tkiryu** [comment] 2018-05-01 23:03
@SlavUI I'm sorry for the late reply. Please reopen this issue.

"FILTER" button is as below. Did you click that?
![image](https://user-images.githubusercontent.com/15909409/39497309-a6ec3c16-4ddd-11e8-8add-0ff7b0c16e05.png)

After clicking "FILTER" button(internally executing filter method), boolean column gets filtered but filter icon color is not changed.
![image](https://user-images.githubusercontent.com/15909409/39497474-7588456a-4dde-11e8-9ede-e33d018198da.png)

**Comment by tkiryu** [comment] 2018-05-02 07:48
@SlavUI thanks for reopening!

**Closed** 2018-05-08 09:02 UTC
Labels: filter-ui, grid, status: resolved, version: 5.3.x
