### ISSUE TITLE
When grid has horizontal scroll and pin all columns the buttons in the toolbar disappear 

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#12287] opened 2022-11-10 08:19 UTC
## Description  

 * igniteui-angular version: 
 * browser: all

## Steps to reproduce  

1. Open the[ following stackblitz sample](https://stackblitz.com/edit/angular-mklrr9?file=src/app/app.component.html)
2. Click on the pinning button in the toolbar
3. Pin all the columns
4. Observe the toolbar

## Result  
The pinning and hiding buttons are no longer visible
![image](https://user-images.githubusercontent.com/34240583/201034531-fade7bdf-2900-49c8-bdec-2f3734161013.png)

## Expected result  
The pinning and hiding buttons must be visible.
![image](https://user-images.githubusercontent.com/34240583/201035265-97795e06-398b-41ef-828b-cf4644b4b852.png)

**Comment by zdrawku** [comment] 2022-11-18 19:15
@ddincheva I believe this is a duplicate of https://github.com/IgniteUI/igniteui-angular/issues/12249. Closing this for the time being and marking the other one with high severity

**Closed by zdrawku** 2022-11-18 19:15 UTC
Labels: :bug: bug, :eyes: status: in-review, :fire: severity: high, grid: column-pinning, grid: toolbar-pinning, grid, status: in-review
