### ISSUE TITLE
IgxGrid: use formatter on title (hover tooltip) 

### ISSUE THREAD

**Issue by sddania** [IgniteUI/igniteui-angular#9895] opened 2021-07-21 08:42 UTC
## Description  
I created a formatter and i've set it in a column. If i go with the mouse hover the cell column, i see the binded data value, not the  value i can see on the grid (and transformed by the formatter)
![image](https://user-images.githubusercontent.com/7241893/126459127-b1931a10-d5bd-4842-b0e9-053d3e815a67.png)

## Steps to reproduce  

https://stackblitz.com/edit/github-k6yekt
go hover countryName column and check the html5 standard tooltip

## Result  
I see the binded value

## Expected result  
I want to see the transformed value by the formatter

**Comment by zdrawku** [comment] 2021-07-29 08:03
The issue is added to out next sprint board.

**Comment by zdrawku** [comment] 2021-08-05 08:38
The fix will be part of the weekly release on Monday - versions to be released 10.2.x, 11.1.x and 12.1.x

**Closed** 2021-08-16 15:59 UTC
Labels: bug, status: resolved, tooltip, grid: cell-interaction
