### ISSUE TITLE
soft delete data from igx-tree-grid ( on delete row it should not delete row permanently from data array )

### ISSUE THREAD

**Issue by anmolpadit30** [IgniteUI/igniteui-angular#9553] opened 2021-05-17 06:13 UTC
## Is your feature request related to a problem? Please describe.
we want to display the data row in tree-grid on basis of the flag. whenever a row is deleted then it should change the flag variable in the row data. 
We have a large data set, so whenever a row is permanently deleted and we are saving the data, the backend has to compare it with previous data to find out which row is deleted, this is affecting the application performance due to the huge dataset. We need the deleted row because we have to send it to the ML algorithm to improve the data extraction for others in order to improve data extraction accuracy for the future.

## Describe the solution you'd like
there should be an option to show and hide row data on the condition of a variable. and it should be dynamic when we delete a row the variable should be changed and data should be hidden from the row. In other words, there should be a "soft delete" functionality.

## Describe alternatives you've considered
the alternative we have considered to make a copy of data and compare it with tree data to find out deleted rows and changing its flag variable. But this is affecting the application performance negatively because of the large dataset.

**Comment by hanastasov** [comment] 2021-08-25 12:53
Seems like duplicate of #9623

**Closed** 2021-08-25 13:03 UTC
Labels: status: in-review, feature-request, grid: tree-grid, grid: row-editing
