### ISSUE TITLE
Incorrect format in column of type DateTime

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#11463] opened 2022-04-22 14:13 UTC
I have two columns of type DateTime, but in the grid a format appears (correct) but when filtering it appears changed, it takes the day as the month and the month as the day:

![image](https://user-images.githubusercontent.com/36885861/164730620-a751d0c6-4327-4483-bc1a-cd3bd813e1b5.png)

Also, if the day is greater than 12, trying to open the filter gives an error:

![image](https://user-images.githubusercontent.com/36885861/164730740-7e67f73f-90e2-4368-9e7c-a1a89c895d90.png)

In this line:

![image](https://user-images.githubusercontent.com/36885861/164730812-484882a8-47a9-4e58-bead-87ae1f5fcc00.png)

This error is because of what I mentioned before, take the day as if it were the month. I have tried to pass a pipeArgs but the same thing happens to me.

I receive the Date as Long and I have this method to format:

`
getDate(date: number): Date {
    return date ? new Date(moment(date).milliseconds(0).valueOf()) : null;
  }
`

I have columns of type Date and it works ok:

![image](https://user-images.githubusercontent.com/36885861/164731747-7c307a75-a458-4c30-9391-fb9a7e27b504.png)

I don't know what else to try, I've wasted a lot of time already.

 * infragistics/igniteui-angular: 12.3.21 
 * browser:  Google Chrome

**Comment by ssg127** [comment] 2022-04-25 09:47
I download your examples from [here](https://github.com/IgniteUI/igniteui-angular-samples/tree/12.2.x), I try `samples/grid/grid-column-data-types` and It fails too.

**Comment by ssg127** [comment] 2022-05-23 11:12
Any update? We have this in production and we had to change it to DATE type so it doesn't fail, but this was a one-off solution.

**Comment by radomirchev** [comment] 2022-05-31 07:15
Hi @ssg127 we are going to check the issue and if it is confirmed, can be scheduled for the next sprint, starting on 6th of June.

**Comment by hanastasov** [comment] 2022-06-01 06:45
@ssg127 , we are looking into this., What locale are you using (spanish, portugese?, etc?)? And did you set it directly to the grid, or is imported globally for the Angular appplication>

**Comment by dobromirts** [comment] 2022-06-01 11:26
Hi @ssg127 I was not able to reproduce this issue. This sample  https://stackblitz.com/edit/angular-x8kgfb-xafx97?file=src/app/grid/grid-column-data-types-sample/grid-column-data-types-sample.component.ts represents the grid filtering with 'dateTime' column . If you are still reproducing the same behavior could you provide a sample or steps to reproduce please?

**Comment by dobromirts** [comment] 2022-06-02 07:20
@ssg127, Thank you for the provided example, but with it everything with filtering works properly on my side. To be able to isolate this behavior, would you share which time zone you use on your machine and also did you have the same issue with newer versions from the previous example?
![dateTime-filtering](https://user-images.githubusercontent.com/46093564/171575267-e4ed90ef-c3fb-42f0-8a96-bca814b969c9.png)

**Comment by ssg127** [comment] 2022-06-02 07:35
@dobromirts my timezone is (UTC+01:00) Madrid or (GMT+2), whichever you prefer. I'll show you the screenshot so you can see how it actually fails when I try to open the filter.
![image](https://user-images.githubusercontent.com/36885861/171578324-a82849be-09e9-4467-bf35-0622e1397615.png)

**Comment by ssg127** [comment] 2022-06-02 08:02
@dobromirts sorry, I forgot to answer the second question, with teh example that you provide with angular 13 and igniteui13 it works:
![image](https://user-images.githubusercontent.com/36885861/171583217-6e03bca1-73dc-47c5-acab-4a1210a9d13b.png)

**Comment by dobromirts** [comment] 2022-06-09 13:02
The issue is resolved with this pull request #11606 and the fix will be available in the next patch.

**Comment by ssg127** [comment] 2022-06-09 15:56
Thank you so much!!!

**Closed** 2022-08-04 12:56 UTC
Labels: duplicate, :white_check_mark: status: resolved
