### ISSUE TITLE
Pressing Ctrl + Arrow Up inside a second layout child inside a Hierarchical Grid scroll to the first child.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#5127] opened 2019-06-19 14:36 UTC
## Description  
When pressing Ctrl + Arrow Up when a cell is selected inside a second child grid, the parent grid scrolls to the top position of the first child instead of the second.

 * igniteui-angular version: 7.3.x
 * browser: any

## Steps to reproduce  

1. Open the second grid in the "Hierarchical Grid" demo
2. Expand the first row
3. Select a cell in the second grid
4. Press Ctrl + Arrow Up

## Result  
The parent grid scrolls to the top of the first child grid

## Expected result  
The parent grid should scroll to the top of the second child grid instead.

## Attachments
![Issue#5127](https://user-images.githubusercontent.com/3768136/59775950-ad440800-92ba-11e9-8f43-6af91ea597a8.gif)

**Comment by ChronosSF** [comment] 2020-01-10 13:45
@skrustev , this doesn't reproduce anymore - you can close it if you can confirm

**Comment by radomirchev** [comment] 2020-01-27 11:50
@skrustev , @ChronosSF any update on the issue?

**Comment by VMihalkov** [comment] 2020-02-04 09:23
I was unable to reproduce the issue

**Closed by VMihalkov** 2020-02-04 09:23 UTC
Labels: bug, hierarchical-grid, keyboard-navigation, severity: medium, status: in-review, version: 7.3.x, version: 8.0.x
