### ISSUE TITLE
Chip layout broken when using avatar in igxPrefix

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#13132] opened 2023-06-16 15:36 UTC
## Description  

Chip with avatar in `igxPrefix` doesn't get the correct padding.
E.g. Documentation samples: https://www.infragistics.com/products/ignite-ui-angular/angular/components/chip#demo

 * igniteui-angular version: 16.0.5
 * browser: Chrome / FF

## Steps to reproduce  

1. Use avatar as Chip prefix:
    ```
        <igx-chip>
            <igx-avatar igxPrefix [initials]="'AA'" shape="circle"></igx-avatar>
            Some text
        </igx-chip>
    ```

## Result  
![image](https://github.com/IgniteUI/igniteui-angular/assets/12942794/22fb719a-8e18-46e5-8d3f-e4ea8fb60194)

**Comment by simeonoff** [comment] 2023-06-19 15:35
I may be wrong, but I believe this is by design. @desig9stein can confirm.

**Comment by desig9stein** [comment] 2023-06-20 08:10
@pmoleri This is by design.
 
The styling for that sample needs to be fixed, the size of the avatar is overwritten. I guess those styles were needed before the refactoring in order to make the avatar look OK inside the chip.

This is without the size overrides.
<img width="511" alt="Screenshot 2023-06-20 at 10 50 02" src="https://github.com/IgniteUI/igniteui-angular/assets/21260963/d77b0590-d438-4e51-8d34-ac8ded06d2a0">

This is without the negative margin.
<img width="537" alt="Screenshot 2023-06-20 at 10 49 55" src="https://github.com/IgniteUI/igniteui-angular/assets/21260963/b64243f7-8f84-42cf-9063-12637b7cbeaf">

Keep in mind that the icons used in that sample are not the default ones.

default icons
<img width="281" alt="Screenshot 2023-06-20 at 11 08 04" src="https://github.com/IgniteUI/igniteui-angular/assets/21260963/3c7e1e5b-6e62-44a7-9b70-3ab3e73d09bd">

**Comment by pmoleri** [comment] 2023-06-20 12:41
Thanks @desig9stein , it makes sense to update the samples.

**Comment by simeonoff** [comment] 2023-06-23 07:50
Closing as resolved.

**Closed by simeonoff** 2023-06-23 07:50 UTC
Labels: :bug: bug, :new: status: new, chip
