### ISSUE TITLE
Export Hierarchical Grid to Excel

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#5848] opened 2019-09-24 14:35 UTC
## Is your feature request related to a problem? Please describe.
The igxHierarchicalGrid cannot be exported to Excel

## Describe the solution you'd like
Export hierarchical grid in Angular to Excel, as by hierarchical grid in jQuery.

### The Excel Exporter is not  generic enough
The Excel Exporter is not generic, i.e it's so much dependent on the type of the grid, the data originates from. That may cause trouble and is not flexible.
### There are not enough exposed properties in the Exporter Service API
If the user wants to export data, which looks somehow different from the already implemented logics, one may not succeed, because of lack of enough handlers.

## Reference
[Exporter Service API](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxexcelexporterservice.html)

**Comment by bmtheo** [comment] 2020-03-17 09:05
Hi there, just jumping in because this would be really helpful for us too

For info, the workaround I did is to flatten the data and export it as a single array (which might not meet some requirements)

**Comment by bmtheo** [comment] 2020-12-05 13:27
up to avoid automatic closing :)

**Comment by senkron-dev** [comment] 2021-02-05 12:09
Hi, 
any ETA about this request?
Would be very helpfull for us too.

**Comment by radomirchev** [comment] 2021-02-11 11:39
@bmtheo @senkron-dev the feature could be planned for the next milestone ,starting end of Feb. I will update you next week on the possible ETA.

**Comment by senkron-dev** [comment] 2021-02-11 11:46
Thank for the info,
this is a needed for our WebApp to reach feature parity with our WinForms app where we use Infragistics controls as well.

**Comment by radomirchev** [comment] 2021-02-25 08:25
@senkron-dev, I can confirm the feature is included in the roadmap, ETA - 19th Apr.

**Closed** 2021-04-19 10:51 UTC
Labels: excel-exporter, feature-request, grid: hierarchical-grid, program: igniteui, status: resolved
