### ISSUE TITLE
[igx-grid] Grid range selection flaky when another row is active

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#13383] opened 2023-08-16 21:14 UTC
## Description  
 * igniteui-angular version: 16.0.15
 * browser: all

### Scenario 1: Having rowSelection=multiple && cellSelection=multiple
1. Add a grid with multi-selection enabled
2. Click on a cell of Row 2 (the cell gets activated and row selected)
3. Click on selection checkbox of Row 8
4. Shift+Click on a field of Row 5

### Result  
It simultaneously adds different ranges for cell and row selection.
![image](https://github.com/IgniteUI/igniteui-angular/assets/12942794/dc3a5e7f-e826-499d-9df2-9b7c10478e93)

### Scenario 2: Having rowSelection=multiple && cellSelection=None

Select a range clicking on fields.

### Result  
![image](https://github.com/IgniteUI/igniteui-angular/assets/12942794/cc34cdb9-5df0-465d-8502-0b057e52e22f)

## Expected result
To be defined. Maybe only one of the actions should take precedence?
Text selection should never happen when row range selection is being done.

**Comment by valeriatoneva** [comment] 2024-01-19 15:03
I examined the behavior with rowSelection and cellSelection both set to multiple and it appears that the grid's functionality is operating as designed. The selection is dynamically updated based on user interaction and the last cell clicked when using Shift+Click dictates the new range for selection. This allows for a flexible and intuitive user experience, I would guess. Regarding scenario 2 - I was not able to received the same result and did not get the text in blue as in the screenshot. Thus, based on my findings, this issue does not reflect a bug but rather the intended behavior of the grid's multi-selection feature (at least for scenario 1).

**Comment by hanastasov** [comment] 2024-01-22 12:24
> I examined the behavior with rowSelection and cellSelection both set to multiple and it appears that the grid's functionality is operating as designed. The selection is dynamically updated based on user interaction and the last cell clicked when using Shift+Click dictates the new range for selection. This allows for a flexible and intuitive user experience, I would guess. Regarding scenario 2 - I was not able to received the same result and did not get the text in blue as in the screenshot. Thus, based on my findings, this issue does not reflect a bug but rather the intended behavior of the grid's multi-selection feature (at least for scenario 1).

Thanks @valeriatoneva  for the detailed research and feedback. I agree with you Scenario 1 is not a bug therefore.

Scenario 2 - @sdimchevski I wonder if you have any recommendations/requirements on whether cell text should be "markable", i.e. a user should be able to select/mark it as a regular text in the page. I will wait for your input before proceeding or closing the issue.

**Comment by hanastasov** [comment] 2024-03-11 07:36
@sdimchevski

**Comment by hanastasov** [comment] 2024-03-25 11:19
Closing due to inactivity and low priority.

**Closed by hanastasov** 2024-03-25 11:19 UTC
Labels: :bug: bug, status: not-a-bug
