### ISSUE TITLE
Row count doesn't update when clearing one of multiple filters

### ISSUE THREAD

**Issue by ruslanss** [IgniteUI/igniteui-angular#83] opened 2016-08-31 14:21 UTC
This was raised by our QA team and I have managed to replicate the issue on the demo page: http://igniteui.github.io/igniteui-angular/samples/igGrid.html

steps to reproduce:

1. enter filter in column 2
2. enter filter in column 3
3. clear filter in column 2 by using "Clear Filter" drop-down menu item
4. observe row count in "matching records" label as incorrect

see attached screenshot
![iggrid filter bug](https://cloud.githubusercontent.com/assets/1591905/18132386/8a47ed50-6f8e-11e6-9406-7ed1054f610c.PNG)

**Comment by dkamburov** [comment] 2016-09-08 10:14
This is not related to IgniteUI AngularJS extensions. 
It can be reproduced in [non-angular grid](http://www.igniteui.com/grid/simple-filtering) too.
I also tried this with the latest development version and it is already fixed, so stay tuned for the next Service Releases.

**Comment by kdinev** [comment] 2016-09-08 10:55
@ruslanss We have a service release scheduled for the end of this month (September). I will keep the issue open until the SR is release.

**Comment by kdinev** [comment] 2016-10-07 08:24
@dkamburov Could you make sure the issue is resolved with the latest service release?

**Comment by dkamburov** [comment] 2016-10-10 11:04
I tried it against 16.1.20161.2145 and it is working fine now. It is also working fine in our demo page - 
[http://igniteui.github.io/igniteui-angular/samples/igGrid.html](http://igniteui.github.io/igniteui-angular/samples/igGrid.html)
I think we can close this now.

**Closed** 2016-10-10 13:23 UTC
Labels: grid, investigate
