### ISSUE TITLE
A newly added row can not be scrolled horizontally

### ISSUE THREAD

**Issue by gwozt** [IgniteUI/igniteui-angular#8593] opened 2020-11-16 08:17 UTC
## Description  
A newly added row can not be scrolled horizontally and it follows the position of the scrollbar so that even though one scrolls horizontally he or she sees the row as if no horizontal scrolling has been done.
 * igniteui-angular version: latest current version at the time of entry
 * browser: chrome

## Steps to reproduce  
1. Add a new row
2. Scroll horizontally

## Expected result  
Being able to scroll horizontally.

## Attachments  
![Unbenannt1](https://user-images.githubusercontent.com/6621154/99227966-434fcb00-27ec-11eb-8f83-6b1af0ab9dfb.PNG)
The picture above is taken from a Stackblitz sample. The second row in the picture has the described problem of not letting itself to be scrolled horizontally.

**Comment by ChronosSF** [comment] 2020-11-17 12:56
Thanks for the report. This is most likely duplicate of #8587

**Comment by ChronosSF** [comment] 2020-11-24 10:49
Can you try the latest 10.2 or 11.0 patch to see if it solves the issue?

**Closed** 2021-01-07 15:00 UTC
Labels: bug, status: in-review
