### ISSUE TITLE
NavDrawer doesn't get pinned when resizing from a small to large screen

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#686] opened 2018-02-28 17:20 UTC
### Description  
Resizing my screen from large to small causes the dialog to go into unpinned state. However resizing back to large doesn't bring it back to pinned state.

### Steps to reproduce  

1. Run the repo demos
2. Resize the window to < 1024px
3. Resize back to normal

### Result  
I cannot open the drawer anymore.

### Expected result  
The drawer should have appeared back.

### Attachments  
![image](https://user-images.githubusercontent.com/1472513/36802081-6fb0d092-1cbc-11e8-9fd8-5c42f8ac1e97.png)

**Comment by damyanpetev** [comment] 2018-03-02 15:35
Yeah, the hamburger button in the demos went missing at some point.
There should be a step before 3. "Click the overlay or select a sample" to hide the drawer as I can't reproduce it otherwise. If you can repro without that do let me know, otherwise I'm labeling this for the demos and I'll add back the button. (see below).

> Notes:
> Opening and closing the drawer is entirely up to the app. It's not even open by default - the initial open is explicit in the demos setup, and the auto-close on selecting a sample is app-specific as well.
> The only state the drawer should be auto-updating is the `pin` and if already closed it remains that way.



As far as how auto-pin works, I certainly don't mind adding more automatic open if needed.
@SlavUI @sbozalieva Thoughts?

P.S. Alternatively this can easily be achieved in the demos app by just binding the open state to the pin:
```html
<igx-nav-drawer [isOpen]="drawerState.pin" [(pin)]="drawerState.pin">
```
Though that'll also close it when it unpins, which I'm not sure is always desired.

**Comment by sbozalieva** [comment] 2018-03-06 15:36
@damyanpetev Let's not automate it for now.

**Comment by damyanpetev** [comment] 2018-03-21 12:21
Closing for now. If auto-pin + open combination comes up again in the future this can be reopened.

**Closed by damyanpetev** 2018-03-21 12:21 UTC
Labels: bug, demos, nav-drawer
