### ISSUE TITLE
GroupBy selection optimization

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#9405] opened 2021-04-23 07:46 UTC
## Description  
Currently the group by selection doesn't use any caching mechanism which leads to poor performance when selecting larger groups. 

 * igniteui-angular version:  11.1.x, 12.1.x
 * browser: any

## Steps to reproduce  

1. Open the [following sample](https://stackblitz.com/edit/igxgrid-largegrouptest-event)
2. Group by the `Field` column
3. Select the `Field: some text` group

## Result  
There is a slight delay until all the records in the group get selected.

## Expected result  
There shouldn't be a delay.

**Comment by Timmeeeey** [comment] 2021-07-16 08:24
For me it's more than just a slight delay (see example).

https://stackblitz.com/edit/github-hwxmub

If you group by 'category' and select any group the page doesn't respond anymore.
This could be related to #9250.

- igniteui-angular version: 12.0.7

**Comment by damyanpetev** [comment] 2021-09-07 13:28
@Timmeeeey That's correct, part of the delay (about a third by my perf logs) is due to emitting a ton of events in these cases caused by #9250. 
There was an easy fix for this issue that'll greatly reduce the time, though with as much group records as in your case it still isn't enough. So we'll address the events next as soon as possible.

**Closed** 2021-12-10 12:54 UTC
Labels: :bug: bug, :eyes: status: in-review, grid: general, grid: groupby, grid: row-selection, version: 11.1.x, version: 12.1.x
