### ISSUE TITLE
Records are hidden in Last page of igx-Grid and treegrid

### ISSUE THREAD

**Issue by jaya0selva** [IgniteUI/igniteui-angular#6625] opened 2020-02-06 09:36 UTC
### Description  
Describe the issue.
When the records are less in the last page of grid,the records are getting hidden.

 * igniteui-angular version: ^8.2.9
 * browser: Google Chrome

### Steps to reproduce  

1. Adjust the page size to make less records in the last page
2. Move the scroll bar to the end in the first page
3. Navigate to last page

### Result  
Records in the last page are hiding

### Expected result  
All the records in the last page should be displayed

### Attachments  
![image](https://user-images.githubusercontent.com/40403770/73923999-c228e680-48f1-11ea-9935-fff4ef0e7c0d.png)

**Comment by zdrawku** [comment] 2020-02-13 08:32
@jaya0selva I see that you are using the Boston marathon sample. Can you send it over to me with the configuration which is causing this behavior? We did some resizing improvements in the versions after 8.2.9, so could you please update the sample to the latest [8.2.19 ](https://github.com/IgniteUI/igniteui-angular/releases/tag/8.2.19)version as well

**Comment by jaya0selva** [comment] 2020-02-13 11:36
Hi @zdrawku,
PFB the URL.
https://stackblitz.com/edit/angular-xdrmvs

Steps to reproduce:
1. Move the scroll bar to bottom of the page.
![image](https://user-images.githubusercontent.com/40403770/74430515-06ccf880-4e83-11ea-9afe-a255f316e2c6.png)
2. Navigate to last page.
![image](https://user-images.githubusercontent.com/40403770/74430581-25cb8a80-4e83-11ea-87fa-b1d8d5e3d2b7.png)

**Comment by zdrawku** [comment] 2020-02-20 09:55
Thank you for the sample, I can confirm this is a bug.

**Comment by zdrawku** [comment] 2020-02-20 09:56
@radomirchev I am moving this for the next sprint from our team board

**Comment by radomirchev** [comment] 2020-02-20 14:12
@jaya0selva the issue is scheduled for the next sprint.

**Comment by hanastasov** [comment] 2020-02-28 09:01
@jaya0selva issue is resolved in 8.2.16 version.

**Closed by hanastasov** 2020-02-28 09:01 UTC
Labels: bug, grid, status: resolved, version: 8.2.x
