### ISSUE TITLE
Update "data" input property type definitions

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#9101] opened 2021-03-04 11:50 UTC
## Description  
`<igx-grid [data]="data | async" ...>`

When strict mode is enabled and async pipe is used for resolving the data for the igxGrid, igxHierarchicalGrid, igxTreeGird or the igxCombo the following error is thrown: 

error TS2322: Type 'any[] | null' is not assignable to type 'any[]'.
  Type 'null' is not assignable to type 'any[]'.

Currently the following approach can be used as a workaround on application level:

`<igx-grid [data]="$any(data | async)" ...>`

 * igniteui-angular version: 11.1.x, 10.2.x
 * browser: any

**NB: Maybe we should check for other input properties which current type does not accept null.**

## Expected result  
No errors to be thrown when using `[data]="data | async"`.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by damyanpetev** [comment] 2021-03-04 17:01
One more - same applies to the `igxForOf` directive input which is also typed as `any[]`.

Context:
Issue stems from the behavior of the async pipe - until the value is resolved, the pipe returns null
https://github.com/angular/angular/blob/2028a77dc843ddc1b4fedfc843f1b4a4b4c91179/packages/common/src/pipes/async_pipe.ts#L98-L101
Thus, it's type for arrays becomes `any[] | null` which is not compatible with our property type and thus strict checks fail. Same goes for some other pipes as far as I see. 

Looks like a definition like `data?: any[] | null;` will cover most cases, though the uncertainty in the type will surely ripple across the code and will be a bit of a chore to go through.

**Comment by kdinev** [comment] 2021-03-25 12:22
I tried this after merging strict template checks in master and cannot reproduce it. @mmart1n should I close the issue?

**Comment by mmart1n** [comment] 2021-03-25 16:07
> I tried this after merging strict template checks in master and cannot reproduce it. @mmart1n should I close the issue?

I'm still able to reproduce the issue on a project, created with enabled strict mode: ng new [project-name] --strict

Attached you will find a demo project which reproduces the issue.

[remote-strict.zip](https://github.com/IgniteUI/igniteui-angular/files/6206168/remote-strict.zip)

**Closed** 2021-06-02 12:35 UTC
Labels: bug, combo, grid: general, grid: hierarchical-grid, grid: tree-grid, status: resolved, version: 10.2.x, version: 11.1.x, virtualization
