### ISSUE TITLE
When going into edit mode, the row editing overlay is not correctly positioned

### ISSUE THREAD

**Issue by VMihalkov** [IgniteUI/igniteui-angular#3917] opened 2019-02-14 11:48 UTC
## Description  
When going into edit mode, the row editing overlay is not correctly positioned.

 * igniteui-angular version: 7.2.0-beta.2
 * browser: Chrome

## Steps to reproduce  

1. Open gridRowEdit in Angular Dev Samples
2. Double click inside any cell to go into edit mode

## Result  
The row is moved to the left

## Expected result  
The row should be positioned properly

## Attachments  
![roweditissue](https://user-images.githubusercontent.com/12252163/52784382-961bb200-305d-11e9-9f83-05265f4665f8.JPG)

**Comment by ViktorSlavov** [comment] 2019-02-14 14:34
Thanks for pointing this out, @VMihalkov !
This seems to be a bug in the overlay service itself, so this issue is a duplicate of https://github.com/IgniteUI/igniteui-angular/issues/3876

**Comment by ViktorSlavov** [comment] 2019-02-14 14:36
Never mind, we'll fix them with two separate PRs, as the `overflow: auto` bit seems more pressing

**Closed** 2019-02-15 09:33 UTC
Labels: bug, row-editing, severity: medium, status: resolved, version: 7.2.x
