### ISSUE TITLE
Grid doesn't show multi-column headers

### ISSUE THREAD

**Issue by rondo104** [IgniteUI/igniteui-angular#6989] opened 2020-03-27 15:59 UTC
## Description  
Grid doesn't print multi-column headers if  html template use *ngTemplateOutlet

 * igniteui-angular version: 8.2.2 
 * browser: Chrome 

## Steps to reproduce  

Create template recursively from config. Use *ngTemplateOutlet

Code:
```    HTML
<ng-template #recursiveList let-items>
      <ng-container *ngFor="let item of items">
        <ng-container *ngIf="item?.name; then group; else column"></ng-container>
        <ng-template #group>
          <igx-column-group [movable]="true" [pinned]="false" [field]="item.name"
                            header="{{'risk.analysis.grid.header.' + item.name  | translate }}">
            <ng-container *ngIf="item.items && item.items.length">
              <ng-container *ngTemplateOutlet="recursiveList; context:{ $implicit: item.items }"></ng-container>
            </ng-container>
          </igx-column-group>
        </ng-template>
        <ng-template #column>
          <igx-column
            [ngSwitch]="item?.field"
            [field]="item.field"
            header="{{'risk.analysis.grid.header.' + item.field  | translate }}"
            [pinned]='item.pinned'
            [hidden]='item.hidden'
            [disableHiding]="item.disableHiding"
            [resizable]="item.resizable"
            [movable]="item.movable"
            [groupable]="item.groupable"
            [sortable]="item.sortable"
            [dataType]="item.dataType"
            [width]="item.width">
          </igx-column>
        </ng-template>
      </ng-container>
    </ng-template>
    <ng-container *ngTemplateOutlet="recursiveList; context:{ $implicit: tableConfig?.items }"></ng-container>
```

## Result  
![image](https://user-images.githubusercontent.com/13147055/77772890-812b9380-7051-11ea-8b2c-8971e93ace0b.png)

## Expected result  
![image](https://user-images.githubusercontent.com/13147055/77772959-9d2f3500-7051-11ea-8dc3-14dbeb152549.png)

**Comment by zdrawku** [comment] 2020-04-01 11:34
Hey @rondo104, I am marking this as a third party issue, caused by angular - [related issue](https://github.com/angular/angular/issues/14842). 

As Radoslav explained [here](https://github.com/IgniteUI/igniteui-angular/issues/4966#issuecomment-498232941):

> the content children query can't be resolved for a tag/component which is not declared inside the parent content. Thus this thing will never find any column component as there is no column declaration in the context of the igx-column-group:

```html<ng-template #groupTemplate let-col="col">
    <igx-column-group [header]="col.header">
        <ng-container *ngFor="let child of col.children">
            <ng-container *ngTemplateOutlet="templateChooser; context: { col: child }"></ng-container>
        </ng-container>
    </igx-column-group>
</ng-template>
```

The only way to achieve a recursive creation of Column and Group Columns would be by creating a Column elements and replacing them in the `columnList` query of the igxGrid component - [working sample](https://stackblitz.com/edit/angular-recursive-columns-creatoin). It is not by using ngTemplateOutlet and ng container, although it would do the trick for recursive columns creation while we are waiting for Angular to fix their [bug](https://github.com/angular/angular/issues/14842).

**Closed by zdrawku** 2020-04-01 11:34 UTC
Labels: bug, grid, multi-column-headers, print-styles
