### ISSUE TITLE
Clearing date or number column's cell value is not possible.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#4881] opened 2019-05-23 07:15 UTC
## Description  
Describe the issue.

 * igniteui-angular version: 7.2.x, 7.3.x
 * browser: N/A

## Steps to reproduce  

1. Run DEV demos
2. Navigate to Grid Column Moving sample
3. Double-click in a cell in "DateCreated" column
4. Click the "X" button to clear the value
5. Click on another row to commit the change

## Result  
The cell's value is reverted to the initial one.

## Expected result  
The cell should be empty.

## Note:
In a number column, the value is converted to a zero which may not be the desired result.

**Comment by nrobakova** [comment] 2019-07-29 12:14
This bug is fixed only for the date column. For the number column this behavior is by design.
As it is written in the [link](https://www.infragistics.com//angularsite/components/grid/editing.html#grid-cell-editing-and-edit-templates):
"For number data type, default template is using igxInput type="number", so if you try to update cell to a value which can not be parsed to a number your change is going to be discarded, and the value in the cell will be set to 0."

**Closed** 2019-08-05 16:48 UTC
Labels: bug, cell-editing, grid, severity: medium, status: resolved, version: 7.2.x, version: 7.3.x
