### ISSUE TITLE
updateColumns method works only when an empty array is given

### ISSUE THREAD

**Issue by Volen99** [IgniteUI/igniteui-angular#11575] opened 2022-05-17 12:20 UTC
## Description  
Describe the issue.
updateColumns method works only when an empty array is given as a paramater
 `
        const newColumns = []; 
        this.grid1.updateColumns(this.columns);
        this.grid1.cdr.detectChanges();
`

 * igniteui-angular version: 13.1.x

## Steps to reproduce  

1. Please go to this [stackblitz](https://stackblitz.com/edit/angular-bejvgc-nsvgjz?file=package-lock.json)
2. Open dev tools and click Reverse button
3.  Error is shown
![image](https://user-images.githubusercontent.com/41373491/168808318-4b3ba0cd-0d4e-411d-ad4f-81be5070e62e.png)

## Result  
Error is shown and columns are not reversed

## Expected result  
No error should be shown and columns to be reversed

**Comment by amitmoondra** [comment] 2022-05-17 17:50
I am facing the same issue with 13.1.12 version, it works with 13.1.8 but not with 13.1.12 or above.
@hanastasov can this be checked ASAP, we are facing issues and clients are complaining.

**Comment by amitmoondra** [comment] 2022-05-23 19:50
@ChronosSF can I know when will this be done, seems like this is not fixed in version 13.1.6, I checked but fix for this issue is not yet implemented.

**Comment by hanastasov** [comment] 2022-05-26 13:59
The reported is not a bug. The `updateColumns`  is intended only for internal use, also its implementation requires different usage than the provided Stackblitz sample (requires a collection of column objects, instead of plain JSON collection).

**Closed by hanastasov** 2022-05-26 13:59 UTC
Labels: :bug: bug, grid: column-moving, :runner: priority: high, version: 13.1.x, grid
