### ISSUE TITLE
Dialog does not expands with content when templated 

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular#9038] opened 2021-02-22 19:24 UTC
## Description  
Dialog does not expands with content  when templated 

 * igniteui-angular version: 11.1.0
 * browser: 88.0.4324.182

## Steps to reproduce  

1. Open example
- [example](https://stackblitz.com/edit/github-3zfykb?file=src%2Fapp%2Fdialog-sample-3%2Fdialog-sample-3.component.html)
- [example-dialog-11.1.0.zip](https://github.com/IgniteUI/igniteui-angular/files/6024597/sample-dialog-11.1.0.zip)
2. Click on Show Custom Dialog button.

## Result  
The dialog has a maximum width and the content is partially visible.

## Expected result  
The dialog expands with the content.

In version 11.0.7 the dialog was adjusted to the width of the content .

-  [example ](https://stackblitz.com/edit/github-3zfykb-mhjkkr?file=src%2Fapp%2Fdialog-sample-3%2Fdialog-sample-3.component.html)
- [example-dialog-11.0.7.zip](https://github.com/IgniteUI/igniteui-angular/files/6024595/sample-dialog-11.0.7.zip)

An alternative could be adding a field to allow the dialog to expand with the content.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by simeonoff** [comment] 2021-03-01 12:43
Closing as the issue is resolved with [Release 11.1.1](https://github.com/IgniteUI/igniteui-angular/releases/tag/11.1.1).

**Closed by simeonoff** 2021-03-01 12:43 UTC
Labels: bug, dialog, regression, status: resolved, version: 11.1.x
