### ISSUE TITLE
Visual issues with Multi Row Layout and incomplete column layouts in IE11

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#4669] opened 2019-04-30 15:55 UTC
## Description  
Visual issues with Multi Row Layout and incomplete column layouts in IE11

 * igniteui-angular version: 7.3.x
 * browser: IE11

## Steps to reproduce  

1.  If one group has two rows and the others do not, they are displayed as a single row with a blank row below it.
Using the same template from my previous reply:
Note that this issue can be reproduced with and without column pinning
```
        <igx-grid 
        [rowSelectable]="false" 
        #grid
        [data]="data" 
        displayDensity="compact" 
        [width]="'1200px'" 
        [allowFiltering]="true" 
        [paging]='true'
        [filterMode]="'excelStyleFilter'">
            <igx-column-layout #block1>
                <igx-column [rowStart]="1" [colStart]="1" sortable="true" [colEnd]="5" field="ContactName" [width]="'200px'"></igx-column>
                <igx-column [rowStart]="1" [colStart]="5" sortable="true" field="ContactTitle" [width]="'200px'"></igx-column>
                <igx-column [rowStart]="1" [colStart]="6" sortable="true" field="Country"[width]="'200px'"></igx-column>
            </igx-column-layout>
            <igx-column-layout #block2>
                <igx-column [rowStart]="1" [colStart]="1" sortable="true" field="CompanyName"></igx-column>
                <igx-column [rowStart]="1" [colStart]="2" sortable="true" field="PostalCode"></igx-column>
                <igx-column [rowStart]="2" [colStart]="1" sortable="true" [colEnd]="3" field="Fax"></igx-column>
            </igx-column-layout>
            <igx-column-layout #block3 [pinned]="true">
                <igx-column [rowStart]="1" [colStart]="1" sortable="true" [colEnd]="3" field="Phone"[width]="'200px'" ></igx-column>
                <igx-column [rowStart]="1" [colStart]="3" sortable="true" [colEnd]="5" field="City" [width]="'200px'"></igx-column>
                <igx-column [rowStart]="1" [colStart]="5" sortable="true" [colEnd]="7" field="Address" [width]="'200px'"></igx-column>
            </igx-column-layout>
        </igx-grid>
    </section>
```

## Result  
IE renders the column headers like this:

![image](https://user-images.githubusercontent.com/1182001/56975348-4be4a000-6b79-11e9-8ada-a1121d4a5e48.png)

## Expected result  
Grid should be aligned properly

**Comment by MayaKirova** [comment] 2019-05-29 13:01
Currently both header and content in all browsers render an empty space in case no columns are configured to fill that space. For example, here's Chrome:
![image](https://user-images.githubusercontent.com/10397980/58558023-71240700-8228-11e9-9e2d-12043ca9631f.png)

This behavior is consistent with the grid-area class, where if no element is configured to fill a section of the layout an empty space will be displayed.

As we do not explicitly handle invalid layout definitions and let the browser render it as is, this is the expected behavior when an incomplete layout is defined for the grid.

@mpavlinov In my opinion, this should be closed as not a bug.

**Closed** 2019-07-23 11:08 UTC
Labels: grid, multi-row-layout, severity: low, status: not-a-bug, version: 7.3.x
