### ISSUE TITLE
Upgrade to 7.1.3 and 7.1.4 broke [texTop] [textAlign] on Bar Linear Progress 

### ISSUE THREAD

**Issue by corganfuzz** [IgniteUI/igniteui-angular#3862] opened 2019-02-07 18:32 UTC
## Description  
Upgrade to 7.1.3 and 7.1.4 broke [texTop] [textAlign] on Bar Linear Progress, unable to stylize those as well.

I used to have the percentage on top of the bar. Now is underneath the bar without an option to change.

 * igniteui-angular version: 7.1.3,  7.14
 * browser: Chrome

## Steps to reproduce  

1. go to [stackz](https://stackblitz.com/angular/ndbbmjqjenr?file=src%2Fapp%2Flinear-progressbar-sample-2%2Flinear-progressbar-sample-2.component.html) this is the main example of bar linear progress
2. You can see alignment is not working, not center or right 
3. you can also see textop is also not working
4. btw I used ng update igniteui-angular , do I need to clone my code again? going back to 7.1.2 would not work. It's like something got broken internally

## Result  
What is the actual result after following the steps to reproduce?

see pic 
![bugbar](https://user-images.githubusercontent.com/11259414/52434019-05305e00-2ad4-11e9-89fa-d3cecc424db1.jpg)

## Expected result  
What is the expected result after following the steps to reproduce?

percentage on top of the bar, and alignment working

**Comment by simeonoff** [comment] 2019-02-08 15:14
@desig9stein can you take a look?

**Comment by kdinev** [comment] 2019-02-11 11:50
@corganfuzz We will release the fix in `7.1.6` on Friday, 02/15/2019. You don't have to downgrade and you've gone through the correct process for upgrading!

To not commit the `ng update`, all you need to do is revert the `package.json` and `package-lock.json` changes, delete the `node_modules` and do `npm install` to restore the old versions defined in the `package.json`.

**Comment by corganfuzz** [comment] 2019-02-15 20:54
@kdinev upgrade to 7.1.6 did not fix the issue. 

I've tried 2 ways to update to 7.1.6

1. cloned my repo and use ng update igniteui-angular  or
2. cloned again and changed the package.json to 7.1.6

Nome of them worked and the issue persists. This is preventing me to updating to the latest version since there are inside <igx-card> tags and it's the first thing a use will see. Need help.

**Comment by kdinev** [comment] 2019-02-15 21:24
This will be the first thing we will investigate Monday morning. Is anything else broken, or everything else is fine with the project?

**Comment by kdinev** [comment] 2019-02-15 21:26
Oh, I know why. The fix was PRed to master only and not to the `7.1.x` branch. This is my bad. We will merge it in the 7.1.x and I'll publish an emergency 7.1.7 for you. Apologies!

**Comment by corganfuzz** [comment] 2019-02-15 21:37
cool , thanks. will wait until monday.

**Comment by kdinev** [comment] 2019-02-18 08:00
@desig9stein Can you please cherry-pick this fix to `7.1.x`? I'll create a new tag once it's merged.

**Comment by kdinev** [comment] 2019-02-18 10:00
@corganfuzz I just tagged `7.1.7`. Let me know if the issue is fixed.

**Closed by kdinev** 2019-02-18 10:00 UTC
Labels: bug, progress-bar, regression, severity: medium, status: resolved, styling, version: 7.1.4
