### ISSUE TITLE
When a resizable column has [maxWidth], the temporary resize indicator is misaligned during resizing.

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#3945] opened 2019-02-18 16:38 UTC
## Description  
If a column has [maxWidth] defined, when the user tries to resize it, the temporary resizing indicator is misaligned. This seems to be a regression - when testing with version 7.1.3, the issue does not reproduce.

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Run the attached isolated sample.
2. Try to resize the "Contact Name" column and make it smaller by dragging the right end of its header to the left. On the screenshot below during the drag the mouse cursor is where the red circle is, but the indicator is in the middle of the previous column.

## Result  
While dragging, the temporary resizing indicator is misaligned and is displayed on the previous column.

## Expected result  
The resizing indicator should be at the position of the mouse cursor.

## Attachments  

![sketch](https://user-images.githubusercontent.com/18643062/52964545-369a0b00-33ab-11e9-82c6-a07f5c5d8352.png)

[igxGridResizingSample.zip](https://github.com/IgniteUI/igniteui-angular/files/2876586/igxGridResizingSample.zip)

**Comment by SAndreeva** [comment] 2019-02-27 16:05
Duplicate of #3908

**Closed by SAndreeva** 2019-02-27 16:05 UTC
Labels: bug, grid, regression, resizing, severity: medium, status: in-review, version: 7.2.x
