### ISSUE TITLE
List item in Bootstrap

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#11114] opened 2022-02-28 14:38 UTC
## Is your feature request related to a problem? Please describe.
1. List item has no border-bottom in Bootstrap theme.
2. List item background in Bootstrap theme resolves to `--igx-grays-900-contrast`.

## Describe the solution you'd like
1. List item has `border-bottom: .0625rem solid hsla(var(--igc-gray-300), var(--igc-gray-a))` in WC.
2. List item has `background: hsla(var(--igc-surface-500), var(--igc-surface-a))` in WC.

**Comment by didimmova** [comment] 2022-03-15 12:48
@wnvko The border-bottom problem was resolved in [this issue](https://github.com/IgniteUI/igniteui-angular/issues/11101) and as I can see in the current web components code the background of the list items is contrast-color(gray, 900) and the border is 1px. Please check both repositories again and answer if the issue is still valid.

**Closed** 2022-03-16 08:36 UTC
Labels: list, :white_check_mark: status: resolved, :toolbox: feature-request, bootstrap-theme
