### ISSUE TITLE
Issue with export of csv file on data grid

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#6673] opened 2020-02-12 10:36 UTC
## Description  
Is there any data limitation on export to csv? we are trying to export around 500000 records from grid and it gets hanged. totally unresponsive. What is best practice to follow for export from grid? and any other workaround for this issue? 
 
 * igniteui-angular version: 
 * browser:  Chrome

## Steps to reproduce  
Export large data from data grid

## Result  
screens becomes unresponsive

## Expected result  
it should export all data to csv

**Comment by zdrawku** [comment] 2020-04-13 13:01
When it comes to data export by passing the Grid to the service, it is important to configure proper Exporter options as the process takes into account features like filtering and column hiding, and also you might consider skipping columns having templates that are not exposing any data, to reduce iterations.

Keep in mind that you can pass Grid's data directly to the export data handler, instead of using the actual Grid. This might have a positive performance impact as well.

As for the actual performance, exporting more than 500 000 rows will take more than 3 minutes, the following results are observed with 20 columns and:
- 10 000 records, exported for less than 3 seconds
- 100 000 records, exported for less than 30 seconds
- 500 000 records, exported for less than 3 minutes
- 1 000 000 records, exported for less than 10 minutes.

I am closing this issue as it's not a bug. You can log a [documentation issue](https://github.com/IgniteUI/igniteui-docfx) to update [the topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/exporter_csv.html) with Known Limitations section instead.

**Comment by DiyanDimitrov** [comment] 2020-04-15 13:28
I have reopened the issue in order to investigate if there is something we could do to improve the Excel exporter performance.

**Comment by igdmdimitrov** [comment] 2020-04-27 12:07
Hi @deepakvia,

I'm working on improving the export experience for large data. I tested exporting on grid with 500 000 rows and 20 columns and on my machine the CSV file was generated in less than 10 seconds. Was the file exported in your case or the page froze and didn't generated a file? Let me know if you remember anything else.

Regards,
Dimitar

**Comment by deepakvia** [comment] 2020-04-28 05:26
Hi Dimitar,

Yes the page froze and didn't generated a file.

Thanks
Deepak

**Closed** 2020-07-14 13:37 UTC
Labels: bug, exporters, priority: high, status: resolved, version: 8.2.x, version: 9.0.x, version: 9.1.x
