### ISSUE TITLE
The row editing "Done" button is unreachable using Tab to navigate around on Safari.

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#8417] opened 2020-10-19 15:40 UTC
## Description  
The user cannot reach the "Done" button using the Tab button to navigate and the focus is lost at some point and is does not return to the row in edit more.

 * igniteui-angular version: 10.1.x
 * browser: Safari

## Steps to reproduce  

1. Open [RowEditing](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_editing.html) on Safari browser only.
2. Click on a cell.
3. Press Enter to enter edit mode.
4. Try to reach the "Done" button using the keyboard navigation.

## Result  
The row editing "Done" button is unreachable using keyboard navigation and the navigation does not wrap to the same row afterwards if the user keep pressing Tab.

## Expected result  
The row editing "Done" button should be reachable and pressing Tab should wrap to the row in edit mode.

## Attachments  
![MacRowEditNavigation](https://user-images.githubusercontent.com/3768136/96473383-40d47280-123a-11eb-87ba-d78e75ee5229.gif)

**Comment by Lipata** [comment] 2020-10-19 15:48
Duplicate of https://github.com/IgniteUI/igniteui-angular/issues/8306

**Closed by Lipata** 2020-10-19 15:48 UTC
Labels: browser: Safari, bug, env: MacOS, keyboard-navigation, row-editing, severity: low, status: in-review, version: 10.1.x
