### ISSUE TITLE
Grid should not report "new value" in cell edit exit event when edit is canceled

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-angular#12568] opened 2023-01-23 21:02 UTC
## Description  
If a cell edit is canceled (for example by pressing the escape key) when the cell edit exit event is called the event args contain the edited value in the "newValue" property even though this value is not the true value. 
 

## Steps to reproduce  
create a grid and handle the cellEditExit event then type a value into one of the columns and press escape. For example in the following sample. double click in the price column and change 18 to 23 then press escape

https://stackblitz.com/edit/angular-jf8qui?file=src/app/grid/grid-editing-events/grid-editing-events.component.ts

## Result  
The cell edit exit event reports the old value as 18 and the new value as 23

## Expected
the cell edit exit event does not report the new value as 23. the new value should either not be reported or it should be the current value of 18.

**Comment by hanastasov** [comment] 2023-03-02 15:51
The [Editing spec](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Editing) says the following:

![image](https://user-images.githubusercontent.com/14248932/222477990-5c541f30-9d2b-4686-81d4-cac2c9334226.png)

If a user wants to discard a value that he has typed, is it expected for us to keep this value and emit it in subsequent events? I am asking in terms of design experience. @sdimchevski any thoughts?

The question is how the statement "Escape key discards/reverts cell changes" is understood:
1) "Escape key discards/reverts cell changes" changes the value in the input back to the original value
2) "Escape key discards/reverts cell changes" does not commit the value typed, just like what Sorting/Filtering.etc does according to the highlights in the table above.

**Comment by hanastasov** [comment] 2023-03-17 09:03
> The [Editing spec](https://github.com/IgniteUI/igniteui-angular/wiki/Grid-Editing) says the following:
> 
> ![image](https://user-images.githubusercontent.com/14248932/222477990-5c541f30-9d2b-4686-81d4-cac2c9334226.png)
> 
> If a user wants to discard a value that he has typed, is it expected for us to keep this value and emit it in subsequent events? I am asking in terms of design experience. @sdimchevski any thoughts?
> 
> The question is how the statement "Escape key discards/reverts cell changes" is understood:
> 
> 1. "Escape key discards/reverts cell changes" changes the value in the input back to the original value
> 2. "Escape key discards/reverts cell changes" does not commit the value typed, just like what Sorting/Filtering.etc does according to the highlights in the table above.

@sdimchevski did you have the time to look at this?

**Comment by sdimchevski** [comment] 2023-03-17 10:14
@hanastasov In terms of user experience and design, option 1 is generally better:

"Escape key discards/reverts cell changes" changes the value in the input back to the original value.

**Comment by ddincheva** [comment] 2023-04-06 07:19
The events themselves just provide certain information to the developer at a certain moment and in some cases prevent an action to be completed. The grid actually performs a certain behavior which is described in the table above. So currently when Escape is pressed when a cell or row is edited the grid discard and reverts the changes you can see in the gifs below:
![EscapeCellBehavior](https://user-images.githubusercontent.com/34240583/230303045-e8fb76f3-d804-4ccb-b3af-a1181249a8e2.gif)
![EscapeRowBehavior](https://user-images.githubusercontent.com/34240583/230303067-954fe06c-2c16-4a4b-addf-5d7b747c6d1f.gif)
So from the comments above I am not sure what change exactly in the current behavior you suggest !?

**Comment by hanastasov** [comment] 2023-07-07 10:27
Closing as not a bug.

If ESC aims to just discard the value , it would not go and exit edit mode.
Since ESC exists edit mode, it makes sense to keep the value that was entered in the event arguments.

**Closed by hanastasov** 2023-07-07 10:27 UTC
Labels: :bug: bug, :white_check_mark: status: resolved, grid: cell-editing
