### ISSUE TITLE
Filter icon not showing in ExcelStyleFiltering

### ISSUE THREAD

**Issue by ssg127** [IgniteUI/igniteui-angular#13073] opened 2023-06-01 08:53 UTC
I have upgraded from angular 12 to 13 and so has ignite. I followed the ignite guide but when I updated I noticed that the filter icon is not displayed. I have seen that it is the 'igxprefix', if I remove it from the console it shows correctly.

* "@infragistics/igniteui-angular": "^13.2.24",
* chrome

Not working:
![image](https://github.com/IgniteUI/igniteui-angular/assets/36885861/16cc3798-f448-489a-aed7-c92d0788848b)
![image](https://github.com/IgniteUI/igniteui-angular/assets/36885861/aa3ae696-aa34-4d2b-b914-a76ab5d12cb4)

But if I remove igxprefix it works:
![image](https://github.com/IgniteUI/igniteui-angular/assets/36885861/2050ff83-a572-4d4c-8c12-25f07c6d4f0d)
![image](https://github.com/IgniteUI/igniteui-angular/assets/36885861/8c380708-0702-4187-9aec-f22193a53baf)

I don't know what to do, in version 12 it worked correctly and I haven't touched anything about the filters.

**Comment by simeonoff** [comment] 2023-06-13 07:54
I tried to reproduce this on my end and I couldn't. It might me something related to how styles are imported in your app. If you can create a stackblitz sample, it can be of great help.

Meanwhile, can you try adding this to the stylesheet of the component that declares the grid and its filtering.

```css
[igxPrefix].material-icons.igx-icon,
[igxSuffix].material-icons.igx-icon {
    font-family: "Material Icons";
}
```

**Comment by ssg127** [comment] 2023-06-13 08:51
Hi @simeonoff, It's a big project so I can't upload it to stackblitz. I've seen that if I add the font-family to the icon it works:
![image](https://github.com/IgniteUI/igniteui-angular/assets/36885861/e5ef8aa2-430e-4707-a5c4-559d76c02e8e)

I have seen that the font-family is taken from this variable:
![image](https://github.com/IgniteUI/igniteui-angular/assets/36885861/c5e1ec18-910d-4eef-8e5c-17bb9efa911d)

Which has the following value:
![image](https://github.com/IgniteUI/igniteui-angular/assets/36885861/adb1eaa8-afd8-4180-b7b7-4f8fcce12343)

This is because in my styles I have the following:
`@include typography(
  $font-family: "'Open Sans', sans-serif",
);`


If I remove this styles it works:
![image](https://github.com/IgniteUI/igniteui-angular/assets/36885861/25250b90-0903-4ca8-9292-60d09645adb0)

But I need all the content shown in ignite to be in Open Sans font, in older versions this was the way to do it, has something changed?

**Comment by simeonoff** [comment] 2023-06-13 13:37
Even with the suggested code snipped for typography, I could not reproduce it on my end. For me the `font-family` remains `Material Icons` while everything else is updated to 'Open Sans'.

**Comment by ssg127** [comment] 2023-06-13 15:22
In your image I can see that the _icon-theme overwrites the _input-group-theme, but in my case the opposite happens, the _input-group-theme is the one that overwrites it as you can see in the following screenshot:
![image](https://github.com/IgniteUI/igniteui-angular/assets/36885861/dbaccfc6-b204-481f-b55f-66f0f8dec4f8)

I don't have anything else that can change those styles. For the example did you upgrade from angular 12 to 13 or did you directly use an application with angular 13?

**Comment by simeonoff** [comment] 2023-06-15 11:17
I can't see how updating vs using a clean install could affect this. There are no changes in typography between 12 and 13 that could alter the behavior. If you can reproduce this in a standalone example, we can investigate further. Otherwise, I can't really deduce just from screenshots what could be causing this issue as I can't reproduce.

**Comment by simeonoff** [comment] 2023-06-23 07:51
Closing as not reproducible.

**Closed by simeonoff** 2023-06-23 07:51 UTC
Labels: :bug: bug, :framed_picture: icon, input-group, grid: excel-style-filtering, :eyes: status: in-review
