### ISSUE TITLE
Possible memory leak when opening Dialogs several times

### ISSUE THREAD

**Issue by m4yorga** [IgniteUI/igniteui-angular#11086] opened 2022-02-23 14:37 UTC
## Description  
I think there's a memory leak when opening an igxDialog several times.
The issue can be easily replicated in this Stackblitz: [Dialog Memory Leak (Issue For Ignite) - StackBlitz](https://stackblitz.com/edit/github-hwzhn1-ygogzy)

 * igniteui-angular version: ^12.2.3
 * browser: not specific to a browser but it was tested in Microsoft Edge Version 98.0.1108.56 (Official build) (64-bit)

## Steps to reproduce  

1. Open the stackblitz
2. Take a heap snapshot using Dev Tools
3. Click the **SIMULATE 30 OPENINGS** button
4. Take another heap snapshot using Dev Tools
5. Notice that the amount of allocated memory increased
6. Repeat steps 3 and 4 and the memory will always increase

## Result  
The amount of allocated memory is always increasing, even after forcing a Garbage Collection.

Screenshot of several heap snapshots I took, you can see the memory value always increases:
![image](https://user-images.githubusercontent.com/4580348/155339681-1684929c-59b2-4074-80da-850dc2f84b63.png)

Also attaching an Allocation Timeline that shows there are detached HtmlDivElements, I inspected them and they correspond to each dialog instance.
![image](https://user-images.githubusercontent.com/4580348/155339953-01753cf1-685a-4614-ab70-ad2f8bd0f378.png)

## Expected result  
The igxDialog instances should be properly disposed after the dialog is closed, allocated memory should not increase.
FYI, the component that holds my igxDialog is properly disposed with *ngIf

**Comment by m4yorga** [comment] 2022-03-19 08:06
Hello @Lipata , @ChronosSF , is there any update regarding this possible issue? Thanks much

**Comment by m4yorga** [comment] 2022-03-21 14:35
Thanks @Lipata

**Comment by m4yorga** [comment] 2022-04-24 12:59
Hello @Lipata , @ChronosSF , any update or work around? We would like to be able to dispose the components holding our dialogs.
Thanks in advance.

**Comment by m4yorga** [comment] 2022-05-19 20:33
Hello @Lipata , @ChronosSF , any update or work around?

**Comment by Lipata** [comment] 2022-05-20 06:05
Hi, @m4yorga. The bug is assigned and we will update you when we find the cause.

**Comment by valadzhov** [comment] 2022-05-27 13:53
The issue is fixed in version 12.3.25 and above.

**Closed by valadzhov** 2022-05-27 13:53 UTC
Labels: :bug: bug, :white_check_mark: status: resolved
