### ISSUE TITLE
Build fails in "strictTemplates" mode for <igx-column [dataType]="'number'">

### ISSUE THREAD

**Issue by catull** [IgniteUI/igniteui-angular#6636] opened 2020-02-08 19:34 UTC
## Description
Setting this in `tsconfig.json`
```json
{
  "angularCompilerOptions": {
    "enableIvy": true,
    "fullTemplateTypeCheck": true,
    "preserveWhitespaces": false,
    "strictInjectionParameters": true,
    "strictTemplates": true
  },
 .......
}
```
causes a build error for
```html
<igx-column [header]="'Total'" [field]="'total'" [filterable]="true" [dataType]="'number'"> </igx-column>
```
Setting `"strictTemplates": false` avoids the build failure described above.

 * igniteui-angular version: 9.0.0-rc.2
 * browser: build issue

## Steps to reproduce  

1. Try with `"strictTemplates": true`
2. Experience the error
3. Try with `"strictTemplates": false`
4. The build does not stumble.

## Result
Build failure
```log
src/app/pages/home/statistics/statistics-monthly.component.html:13:88 - error TS2322: Type '"number"' is not assignable to type 'DataType'.

13       <igx-column [header]="'Total'" [field]="'total'" [filterable]="true" [dataType]="'number'"> </igx-column>
```

## Expected result
Strict template mode should be possible.

**Comment by catull** [comment] 2020-07-25 17:13
Any news here ?
I'd like to switch on stricter mode, but this bug prevents me from doing so.

**Comment by catull** [comment] 2020-07-25 17:14
This is still the case in Angular 9.1 and Angular 10.

**Comment by damyanpetev** [comment] 2020-08-06 12:28
Alright, so the basic issue is that in TypeScript enums with string values will not accept the string value itself (unlike numbers).

I've looked at issues like https://github.com/Microsoft/TypeScript/issues/14352 and one option is to union type our enum inputs with string, but I'm not super fond of the idea because it looses the fixed set of values the enum gives us.
Also, from what I see in https://github.com/microsoft/TypeScript/issues/17690#issuecomment-321319291 the behavior is by design - i.e. only the enum itself should be used, not the underlying value (which is considered hidden and subject to changes) and that makes a lot of sense actually.

Because it's incredibly clunky to use the actual enum in the template (must be assigned to component property) we're not the only ones facing this issue - https://github.com/angular/angular/issues/35363, and at least for now it doesn't seem like much can can/will be done in this direction.

In essence - we should be using full union types on all string `@Input` properties. To maintain backwards compatibility, we can keep existing enums as exported constants (see below), so `Enum.Prop` continues to work in existing apps.

This solution came from one of the above issues to a way to create "enums" before they were introduced in TypeScript:
https://github.com/microsoft/TypeScript/issues/3192#issuecomment-261720275

Here's an example [TypeScript Playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBMAdgVwLZwMo2GAKgTzGDgG8BYAKDmsxgENY4BeOAcg1YBpKa4BBAMYwAlgDdhMfMzZ8uPGgBFgA4QGdhERNNYK5VGgFFEAE20HWlAL6VQkRkjRwAcmgJFS86lgbwWARm59akERcUlpACZA3iUVdU1pAGZowxNpABYrSgB6bLgYAAtiNVVkYgBaOAB3aABrVTgElFQAI2AoVQAuSgFNVXhmgDUGTudXQmIWCIBuHLyW5HhjCGBVRFZ4GqhauAAzaDh+qGFEAHMunr74I5PTozRhqFGsHDdJuAAiPg-ZikocgBUAJ4AMwEAANosNIhRgBhKDAOjYOB0ODIRDQ-ITPYHQrFRBgRYNAAUwAAdKcyXAAAasArQYQAL009HBrDgAB82KJ2iIBHQ2Zy4GSydSAJQguC4Apqap0KQ3M4NflaNoo1TqU6IYCmGAQOBgKAQIiwYSrRq7fIyhqSIhU3D61B0E70E5wFp0AS1KoMYzKiCoMBI4QtYTgiT4aKggWqfW2aDwPGfByoD5wXqIfp0RDwOgNVEe9QCRotABWyhgnEO+up91QZIACkawNT0yyTmUbfqtjs3aA1CIziiwGBVGTJQ2MKNpbLZfSqghmg0qu1iAIEUide7gPsEdvbnAXUbjMgBFu3W8MOvhGAYCDspRduihJjULUUwAeXAIEDYEwNEg4AAbROYxQFGRVTgAXVGABVOBLCreDQD-P1DhgY4zgAPmJEBpzFUg4ARGBkCgLQQGmBDLkzeBYV9E4BWkN8U2JcggmcBMClGVgnD0XgMAgRYuLYDgUmoAw8xgbjzDEuAAHVViktg5IsChLDFX5bWIOioGMBjwWkYktIgS0dL0xABTFID33wEysSIOyzP0qDfn+CgM36RpwWMOtYU0HlYDheiLIMlgnJCskJP6X4PKWYQESELBMNOPgNWELUgt0-TpA+DAfmozyqiNM4ktuTLzMYlhcrk-K-goJ9EBfBJsH6YlRAFMpyv0gi2N4VQqgkAQCjgNqOuAHrPF4dM8204KBTJJxOO6djeH5VRZqyiKoqkybVpmuBwvmhT+mWqazrbTMIXJcEIFOUbIXG3bzpaDdal+c64DA3Y6GQcEdpW87CiNBdDvBMljpgd6aGsNSgA) so you can get a feel how this behaves. The role of the `mkenum` function is to force the string value type to use the specific string itself - so `North: "N"` instead of `North: string`. Those are also critical for the next step that extract them from the constant's type to create the string union.

In our case, for example the enum:
```ts
export enum DataType {
    String = 'string',
    Number = 'number',
    Boolean = 'boolean',
    Date = 'date'
}
// in IgxColumnComponent:
@Input()
    public dataType: DataType = DataType.String;
```
becomes:
```ts
export const DataType = mkenum({
    String: 'string',
    Number: 'number',
    Boolean: 'boolean',
    Date: 'date'
});
export type DataType = (typeof DataType)[keyof typeof DataType];
```
(as of recent - I think Typescript 3.8-9) types can also be exported so the single import gives you both:
![image](https://user-images.githubusercontent.com/3198469/89531060-42c09500-d7f8-11ea-85df-8b4fda30c80a.png)
and the property code (and client apps for that matter) can continue using the "enums" as before, except they don't have to.
![image](https://user-images.githubusercontent.com/3198469/89531178-7e5b5f00-d7f8-11ea-8932-e3b9230d6808.png)
![image](https://user-images.githubusercontent.com/3198469/89531201-87e4c700-d7f8-11ea-99a5-39558be5a172.png)

@rkaraivanov Thoughts?

Keep in mind this should **only** be applied to enums with string values used on `@Input` properties. The ones under complex objects not meant for the template (like some direction in the overlay settings is probably fine). Also be mindful of the types - last time I checked a type definition becomes type declare in d.ts and that's global. I'm hoping the export will help, but haven't tested. So do check we're not polluting the global namespace with types and if we can't avoid - make sure those are prefixed (not like `DataType`..)

**Comment by rkaraivanov** [comment] 2020-08-07 06:29
@damyanpetev 
This looks good enough for me, given the option to have some backwards compatibility with the existing string enumerations and convenient enough for users of the product. As you've mentioned this will target only **public** string enumerations and hopefully future development will rely on string unions instead of string enumerations.

**Closed** 2020-09-02 09:09 UTC
Labels: bug, grid, status: resolved, version: 9.0.x, version: 9.1.x

**Comment by kdinev** [comment] 2020-09-10 12:05
@mmart1n Please pull this in `9.1.x`. `10.0.x` is out of maintenance,
