### ISSUE TITLE
igx-grid: `pinned` property doesn't work when `width` property is set together.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4125] opened 2019-03-01 02:02 UTC
## Description  
When `pinned` and `width` properties are set to `igx-column`, the column is not pinned. 

 * igniteui-angular version: from 7.1.2 to 7.1.8, 7.2.0-beta.x
 * browser: N/A

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-pinning-issue.

## Result  
"ID" column is not pinned. If removing `width` property, "ID" column is pinned.

## Expected result  
"ID" column should be pinned.

## Attachments  
https://stackblitz.com/edit/igx-grid-pinning-issue

**Comment by kdinev** [comment] 2019-03-01 09:25
@tkiryu This is by design. Check the console message.
![image](https://user-images.githubusercontent.com/1472513/53628807-ae223280-3c14-11e9-9151-42de35ab7f9d.png)

**Comment by tkiryu** [comment] 2019-03-01 09:40
@kdinev , I don't get it. 

The width of "ID" column is only `100px`. Whereas, the width of `igx-grid` is `100%`.

I don't think the width of "ID" column can exceed the width of `igx-grid`. What's more, these configuration had worked until 7.1.1. 

Could you reopen this issue and look into it again, please?

**Comment by kdinev** [comment] 2019-03-01 10:12
@tkiryu I thought this is reproducible only in the small stackblitz window. Now I see that you get this even if you open the app in full screen mode. Reopening and marking as regression!

**Comment by tkiryu** [comment] 2019-03-04 11:02
@kdinev , thank you so much!

**Comment by mpavlinov** [comment] 2019-03-06 07:54
This is duplicate of #3774

**Comment by kdinev** [comment] 2019-03-07 13:52
Closing this issue in favor of #3774

**Closed** 2019-03-07 13:52 UTC
Labels: bug, column-pinning, duplicate, grid, regression, severity: medium, status: resolved, version: 7.1.x
