### ISSUE TITLE
has no exported member 'AnimationTransitionEvent' error after upgrade to Angular 6

### ISSUE THREAD

**Issue by tkumark** [IgniteUI/igniteui-angular#2790] opened 2018-10-22 00:59 UTC
I am using "igniteui-angular": "5.3.1", and recently upgraded my project from Angular 5 to Angular 6. after which when building my project I am getting the following error

> ERROR in node_modules/igniteui-angular/snackbar/snackbar.component.d.ts(1,10): error TS2305: Module '"D:/myproject/ClientApp/node_modules/@angular/core/core"' has no exported member 'AnimationTransitionEvent'.

In angular.json if i remove 

`"aot": true,`

Then the project builds properly. To what version should I upgrade to ?
In my project I am using
`import { IgxGridModule } from 'igniteui-angular/grid';`

 When I upgraded to a higher version
`"igniteui-angular": "6.1.7",`
 I get another error that grid is not found.

> ERROR in src\app\app.module.ts(54,5): Error during template compile of 'AppModule'
>   Could not resolve igniteui-angular/grid relative to D:/myproject/ClientApp/src/app/app.module.ts..
> src/app/clients-j/clients-j.module.ts(6,31): error TS2307: Cannot find module 'igniteui-angular/grid'.
> src/app/app.module.ts(6,31): error TS2307: Cannot find module 'igniteui-angular/grid'.

**Comment by kdinev** [comment] 2018-10-22 10:42
Closing this as duplicate of #2789 

I have responded in #2789

**Closed by kdinev** 2018-10-22 10:42 UTC
