### ISSUE TITLE
Color Palettes with CSS Variables

### ISSUE THREAD

**Issue by obedurena** [IgniteUI/igniteui-angular#8341] opened 2020-10-09 16:21 UTC
## How to use CSS Variables only when applying a component theme?  

We need to be able to switch the colors of our app at runtime. To achieve this with Angular Material we are generating color palettes in our app.component.ts and storing them as CSS variables. We then store them in SASS variables and pass that to Angular's palettes/themes functions. This works just fine because we are able to pass fully generated color palettes to Angular.

The problem is: when we try to generate palettes for Infragistic's components, it tries to generate colors based on those CSS Variables, what obviously fails. To mitigate that we then, instead of calling igx-palette() are creating an object which has the same properties as the one returned by igx-palette.

igx-palette only seems to generate palettes for primary, secondary and grays. When the theme for a component is generated then text-contrast() is called to generate a contrast color which then fails, because the palettes do not contain actual color values, but CSS Variables. We get many warnings similar to: 

`WARNING: Expected color for $background/$foreground but got var(--theme-secondary-50)/white. The contrast color can't be calculated automatically.
    node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 189:9     text-contrast()
    node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 207:17    igx-contrast-color()
    node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 459:26    resolve-value()
    node_modules\@infragistics\igniteui-angular\lib\core\styles\base\utilities\_functions.scss 515:48    apply-palette()
    node_modules\@infragistics\igniteui-angular\lib\core\styles\components\grid\_grid-theme.scss 231:13  igx-grid-theme()
    src\assets\styles\theme\my-grid-theme.scss 36:22                                                @import
    src\assets\styles\theme\my-grid-theme-class.scss 1:9                                            @import
    src\app\components\paged-grid\paged-grid.component.scss 2:9                                          root stylesheet`

How can we generate color palettes at runtime for the Infragistics components?

 * igniteui-angular version: 10.1.4

**Comment by simeonoff** [comment] 2020-12-07 09:38
Closing as it's a duplicate of #8342

**Closed by simeonoff** 2020-12-07 09:38 UTC
Labels: question, status: in-review
