### ISSUE TITLE
igx-grid sticky header

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1394] opened 2018-05-28 13:37 UTC
### Description  
Is sticky headers possible in the igx-grid? Like https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_sticky_header

**Comment by zdrawku** [comment] 2018-05-28 14:29
In addition, each igxGrid header element is "sticky", I mean, it will be always visible on scrolling.

https://stackblitz.com/edit/igx-grid-filtering?embed=1&file=app/data.ts

**Comment by zdrawku** [comment] 2018-05-30 12:45
@Eralmidia do you have any further questions on this?

**Comment by Eralmidia** [comment] 2018-05-30 12:56
No, thank you. I'll try to implement this at a later date :)

**Comment by zdrawku** [comment] 2018-05-30 13:17
Okay, what about the "sticky" part? I didn't understand quite well, do you want to "stick" a row, or you meant the header itself?

I want just to clarify the whole question in order not to mislead you somehow :)

**Comment by Eralmidia** [comment] 2019-01-16 09:33
Hi @zdrawku 

An old issue, but I would like to reopen this to see if this is possible or can be added as a feature request for the current version of the igx-grid.

By default the igx-grid scrolls within the grid. That works well if the grid is the only thing on the page. But we ofte have situations like the following mockup: https://www.w3schools.com/code/tryit.asp?filename=FZ9JVFCT5YGU

The red area on the top, is some content not related to the grid. Since we need to support a variaty of different screen sizes, there is no way to tell how much space will be avaiable for the igx-grid below the other content. That means we need a scrollbar on the page. When the grid also uses a scrollbar, we end up with a double scrollbar on the page, which isn't very user friendly.

What I would like to be able to do is for the grid to take up as much space as it wants on the page, and when you scroll down, the header is "sticky", as shown in the link above. When you scroll down, the header is always visible.

**Comment by Eralmidia** [comment] 2019-01-17 07:53
@kdinev Is it possible to accomplish anything on this issue?

**Comment by kdinev** [comment] 2019-01-17 08:31
@Eralmidia Out of the box, the grid can be configured to take as much space as the data in it takes, however making the header sticky would be a custom solution in this case. I see it happening by detecting the scroll events on the window, and creating a clone of the header, when scrolling below the point where the header is visible, and positioning it on top of the grid. We can try to create a sample that shows how you can do this. 

The problem would be the header interactivity, however. A clone of the header would be a visual clone, but all sorting, filtering, and other triggers would not go along. Another option would be to apply custom positioning of the header elements, by making them position: fixed.

**Comment by Eralmidia** [comment] 2019-01-17 08:37
Yes, but I think it would be just fine that the interactivity is left at the top.

A sample would be great, thank you

**Comment by Eralmidia** [comment] 2019-01-17 09:52
Thanks

There is a couple of issues here tho:
1. If I now try to add in some content above the grid https://stackblitz.com/edit/angular-4dcgwz-rebukn?file=src%2Fapp%2Fgrid%2Fgrid-sorting-sample%2Fgrid-sorting-sample.component.html This breaks the positioning of the fixed header.
2. It seems like scrolling when when the mouse is over the grid doesn't really work.

**Comment by kdinev** [comment] 2019-01-17 09:59
@Eralmidia The grid takes over the scroll events so virtualization works and doesn't propagate down to the window scroll, which would result in double scrolling. We may be able to resolve this by not handling any scroll when there's no scrollbar @ChronosSF. 

As for the content on top, unless you want to make that fixed too, then simple `position: fixed` no longer suffices. It would be more complex, as the scroll position would also have to be handled, and the position fixed would have to be applied with `top: 0`, but only after the scroll top exceeds the height of the content on top.

**Comment by Eralmidia** [comment] 2019-01-17 10:14
@kdinev If you could take a look at the scrolling issue, that would be great.

As for the header position, I can see that I will have to implement a custom solution in some way. Having the content above fixed would kinda take us back to square one, and we might as well just use scollbars in the grid. Also, we might have situations where we have more than one igx-grid, that would also complicate things. I guess I need to find a general way to determine if the grid is in view, and that this can't be handled by the grid itself. Thanks for the assist.

**Comment by Eralmidia** [comment] 2019-01-30 07:07
@kdinev Perhaps convert this to a bug/feature request regarding the issue with scrolling, as the sticky header is no longer a relevant discussion?

**Comment by kdinev** [comment] 2019-01-30 09:10
@ChronosSF Did you log an issue about this already?

**Comment by ChronosSF** [comment] 2019-01-30 13:35
After looking into the cause I logged it as #3769 .

**Comment by kdinev** [comment] 2019-01-31 22:11
I'll close this issue. Follow #3769

**Closed by kdinev** 2019-01-31 22:11 UTC
Labels: grid, question
