### ISSUE TITLE
When page zoom is decreased, the column in grid is hiding

### ISSUE THREAD

**Issue by jaya0selva** [IgniteUI/igniteui-angular#6627] opened 2020-02-06 10:15 UTC
## Description  
Describe the issue.
Move the horizontal scroll bar to the right, then decrease the zoom % in chrome, the columns in the left side is not displaying and the horizontal scroll is disappearing.

 * igniteui-angular version: ^8.2.9
 * browser: Chrome

## Steps to reproduce  

1.Move the horizontal scroll bar to the right
2.Decrease the zoom % in chrome.

## Result  
the columns in the left side is not displaying and the horizontal scroll is disappearing.

## Expected result  
Grid should refresh based on the Zoom %

## Attachments  
![image](https://user-images.githubusercontent.com/40403770/73927596-ad4f5180-48f7-11ea-8c3d-b55f99d808c2.png)

**Comment by zdrawku** [comment] 2020-02-13 08:42
@jaya0selva I am unable to reproduce the issue with the latest version of 8.2. Could you send me a sample that is showing the problem?

**Comment by jaya0selva** [comment] 2020-02-13 11:42
Hi @zdrawku ,
PFB the url to test.
https://stackblitz.com/edit/angular-xdrmvs

Step 1: Move the Horizontal scroll bar to right.
![image](https://user-images.githubusercontent.com/40403770/74430879-c15cfb00-4e83-11ea-89ce-bf78dff7dddd.png)
Step 2: Decrease the page size till the Horizontal scroll bar hides.
![image](https://user-images.githubusercontent.com/40403770/74430954-f0736c80-4e83-11ea-8c67-3ea9b99e2d9b.png)

**Comment by zdrawku** [comment] 2020-02-20 11:57
Similar to https://github.com/IgniteUI/igniteui-angular/issues/6625. @radomirchev again I am moving this to be discussed for the next sprint planning

**Closed** 2020-03-06 14:22 UTC
Labels: bug, grid, status: resolved, version: 8.2.x
