### ISSUE TITLE
How to create empty stack

### ISSUE THREAD

**Issue by pavan6014** [IgniteUI/igniteui-angular#10773] opened 2021-12-30 05:58 UTC
## Current Behavior:
By default if stack is empty ( panes: [] array empty) it will not display the placeholder for entire area even though you specified size of splitPane, like below.

type: IgcDockManagerPaneType.splitPane,
orientation: IgcSplitPaneOrientation.vertical,
size: 500,

## Expected behavior: 
If size is defined even though no items inside panel array, it should be display empty stack with out any tabs.
It should occupy the width (size: 500) specified in the layout config, below is the screen shot for your reference.

type: IgcDockManagerPaneType.splitPane,
orientation: IgcSplitPaneOrientation.vertical,
size: 500,

![image](https://user-images.githubusercontent.com/26575620/147725672-b7f25e80-65d7-4185-bbcf-c55e17dcb65d.png)

## Real time scenario
Lets take one real time scenario, if we are building house with 2 bed rooms with specified dimensions.
If no items placed inside each bedrooms (array of objects), bedroom dimensions remains same.

## Describe the solution you'd like
If "tabGroupPane" is defined in the layout configuration and panel is empty (panel: []), lets display placeholder for tabGroupPane with default with size:500 as per below config.

type: IgcDockManagerPaneType.splitPane,
orientation: IgcSplitPaneOrientation.vertical,
size: 500,

**Comment by ddaribo** [comment] 2021-12-30 07:47
Closing this issue, as it is a duplicate of #[18](https://github.com/IgniteUI/igniteui-dockmanager/issues/18) and is related to the dock manager.

**Closed by ddaribo** 2021-12-30 07:47 UTC
Labels: :eyes: status: in-review, :toolbox: feature-request
