### ISSUE TITLE
Igx grid: Validation support

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#9653] opened 2021-06-04 06:28 UTC
## Is your feature request related to a problem? Please describe.
The old jquery based ignite grids had builtin validation support. Unless I'm missing something, this does not seem to have made it into the igx-grid yet.
![image](https://user-images.githubusercontent.com/12936286/120755902-dc3aff00-c50e-11eb-8b74-e1cfd1ab4fc1.png)

## Describe the solution you'd like
Standard filters for required fields (not empty, required length (specified length for text), email validation, number input etc, pluss the option to add custom validator methods.

**Comment by Eralmidia** [comment] 2021-06-04 06:32
I see now that there #6501 describes validation. Would this include some builtin standard validations? Also, 6501 seems to have been inactive for quite some time 😛

**Comment by radomirchev** [comment] 2021-07-06 08:53
HI @Eralmidia, I am closing this issue as a duplicate of #6501 . #6501 is still active though with lower priority. Please follow it of for future updates. Once the issue is schedule for development, I will update it and add it to [IgniteUI Angular ROADMAP](https://github.com/IgniteUI/igniteui-angular/blob/master/ROADMAP.md).

**Closed by radomirchev** 2021-07-06 08:53 UTC
Labels: duplicate, feature-request, status: in-review
