### ISSUE TITLE
igxMask puts focus at the end of the input mask when the input is focused

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#7182] opened 2020-04-23 07:51 UTC
## Description  
The whole text of the mask, or the beginning are supposed to be focused, when focus is moved inside an input with igxMask. Currently the end is focused.

 * igniteui-angular version: 9.0.8
 * browser: all

## Steps to reproduce  

1. Define an input with a mask
```html

      <igx-input-group class="order-form-input" type="border">
        <igx-prefix>
          <igx-icon title="Телефон">phone</igx-icon>
        </igx-prefix>
        <igx-prefix>
          +359
        </igx-prefix>
        <input id="orderPhone"
               #orderPhone
               class="input-phone-number"
               name="orderPhone"
               igxInput
               [igxMask]="'000 00 00 00'"
               placeholder="--- -- -- --"
               [(ngModel)]="order.phoneNumber" />
        <igx-suffix *ngIf="orderPhone.value" (click)="order.phoneNumber = null">
          <igx-icon>clear</igx-icon>
        </igx-suffix>
      </igx-input-group>
```
2. Focus it

## Result  
I have to manually return the caret at the beginning of the input after focus.

## Expected result  
The focus should be handled correctly.

**Comment by Lipata** [comment] 2020-04-23 08:15
I think this is duplicate of #6012

**Comment by damyanpetev** [comment] 2020-04-23 11:47
@kdinev While adding `[igxTextSelection]="true"` should work, I also don't mind baking this in the directive, as long as we are happy with the "select all" behavior. Not a huge fan of adding another prop to control though, which is why the extra directive works out, but I agree - it's not discoverable and not too nice as experience

**Comment by kdinev** [comment] 2020-04-24 07:28
@damyanpetev As long as the `igxTextSelection` is documented and there's an example with it in the `igxMask` documentation, there's no need to change anything in the mask.

**Comment by Lipata** [comment] 2020-05-07 19:11
Closing that in the favor of updates in the [samples](https://github.com/IgniteUI/igniteui-angular-samples/issues/1966) and [topic](https://github.com/IgniteUI/igniteui-docfx/issues/1907).

**Closed** 2020-05-07 19:12 UTC
Labels: bug, mask-editor, severity: high, text-selection, version: 9.0.x
