### ISSUE TITLE
Scroll position is persisted between pages

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular#6011] opened 2019-10-18 13:45 UTC
## Description  
When paging is enabled, scrolling in the first page results in scrolling in the second one too, even if it was not yet visited.

 * igniteui-angular version: 8.2.0
 * browser: IE Edge 79 canary

## Steps to reproduce  

1. Open /hierarchical-grid/hierarchical-grid-moving
2. Select 500 items per page
3. Scroll to the middle of the grid
4. Go to the second page
5. Observe how the scroll position has changed, although the user is visiting the page for the first time

## Result  
The scroll position persist between pages

## Expected result  
The scroll position has to be unique for each page

**Comment by ChronosSF** [comment] 2020-01-06 10:02
Duplicate of #5944

**Closed by ChronosSF** 2020-01-06 10:02 UTC
Labels: bug, paging, scroll, version: 9.0.x
