### ISSUE TITLE
Label is not visible when changing input type from border to fluent

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#7781] opened 2020-07-13 13:13 UTC
## Description  
Label is not visible when changing input type from border to fluent.

 * igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open the sample: https://stackblitz.com/edit/github-yhhxcs-nvnbeq
2. Change the type to 'fluent'

## Result  
Label is gone.

## Expected result  
There is a label.

**Comment by simeonoff** [comment] 2020-07-14 06:53
I think this has a lot to do with the conditional template of the input-group. The label changes its position in the DOM tree based on the `type` property. We need to investigate if this is an Angular issue or an issue with the logic of the component.

**Comment by simeonoff** [comment] 2020-07-27 07:28
Closing as it's a duplicate of #7455

**Closed by simeonoff** 2020-07-27 07:28 UTC
Labels: bug, input-group, priority: medium, status: in-review
