### ISSUE TITLE
Undesired behavior when unpinning the last pinned column after scrolling 

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#1193] opened 2018-04-26 16:06 UTC
### Description  
Undesired behaviors when unpinning the last pinned column after scrolling 

### Steps to reproduce  

1. Run **Grid Column Resizing** demo.
2. Use the buttons below the grid to pin consecutively ContactName, ContactTitle and Address columns.
3. Scroll to the end of the unpinned area.
4. Unpin the Address column.

### Result  
Column is not unpinned. Thumb scrolls back to the beginning. Scrolling the unpinned area again causes some undesired behaviors.

### Expected result  
Column is unpinned. Unpinned area can be scrolled with no side effects.
![pinning](https://user-images.githubusercontent.com/7972965/39317606-b35a0a30-4984-11e8-9704-da79a2aaafe6.png)

**Comment by ChronosSF** [comment] 2018-04-27 08:01
Likely duplicate of #1136

**Comment by MayaKirova** [comment] 2018-04-30 11:36
Dupicate of #1136. Same error is thrown.
Closing as duplicate.

**Closed by MayaKirova** 2018-04-30 11:36 UTC
Labels: bug, duplicate, grid, pinning, severity: high, status: in-review, version: 5.3.x
