### ISSUE TITLE
Icon button color is overridden by theme color

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#13977] opened 2024-03-07 12:25 UTC
## Description  

 * igniteui-angular version: 17.1.x
 * browser: all

## Steps to reproduce  

1.  Add an icon button and set its color to a custom color, let's say Secondary-500
2.  Add a navigation bar and change the color of the button icon in the navbar to the same color

## Result  
The icon button in the navbar is always black, the theme overrides the custom color set.
 
![image](https://github.com/IgniteUI/igniteui-angular/assets/34240583/21ed23f2-50d0-4bd2-bcc3-bf622d752f1b)

## Expected result  
The set colors should be applied

NOTE:
The isssue is related with this change https://github.com/IgniteUI/igniteui-angular/pull/13759

**Comment by SisIvanova** [comment] 2024-06-19 08:39
@ddincheva This issue has been fixed with the navbar theme changes in this [PR](https://github.com/IgniteUI/igniteui-angular/pull/14126).
The problem can now be reproduced only in version 17.1.x but it's ok in 17.2.x, 18.0.x and master. 

<img width="1728" alt="Screenshot 2024-06-19 at 11 38 04 AM" src="https://github.com/IgniteUI/igniteui-angular/assets/59446295/59ff35f0-3617-479e-8621-9f8bce9add85">

**Comment by simeonoff** [comment] 2024-08-08 08:07
@hanastasov Is the issue still reproducible? As Sisi stated, it has been fixed in 18.0 and 18.1.x.

**Comment by hanastasov** [comment] 2024-08-08 13:59
> @hanastasov Is the issue still reproducible? As Sisi stated, it has been fixed in 18.0 and 18.1.x.

I assigned it to you, as you have been the one fixing this issue with PR https://github.com/IgniteUI/igniteui-angular/pull/14126. However, I have not verified whicj version works and which does not, since Sisi already did it.

**Comment by simeonoff** [comment] 2024-08-08 16:18
Then I'm closing the issue.

**Closed by simeonoff** 2024-08-08 16:18 UTC
Labels: :bug: bug, :new: status: new, version: 17.1.x
