### ISSUE TITLE
Sorting a column when on the last page in an igxGrid resets the vertical scrollbar if using MRL

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular#4651] opened 2019-04-25 07:18 UTC
## Description  
If a user changes the page and then sorts a column, the vertical scrollbar gets reset if the igxGrid has MRL.

 * igniteui-angular version: 7.3.x
 * browser: N/A

## Steps to reproduce  

1. Run the attached sample with latest master
2. Open http://localhost:4200/
3. Go to page 2
4. Scroll to the bottom
5. Sort the "City" column several times

## Result  
The vertical scrollbar gets reset, or changes its position

## Expected result  
The vertical scrollbar should not get reset when a user sorts a column. 

## Attachments  

[igxGridMRLSortingPaging.zip](https://github.com/IgniteUI/igniteui-angular/files/3115611/igxGridMRLSortingPaging.zip)

![vScrollReset](https://user-images.githubusercontent.com/18643062/56716465-23a50d80-6743-11e9-9c28-d14848225f10.gif)

**Comment by skrustev** [comment] 2019-05-22 14:41
This seems to be also already fixed in the latest 7.3.x branch.
@PavlovVasil  Could you verify that also.

**Comment by MayaKirova** [comment] 2019-07-23 08:16
This no longer reproduces in 7.3.x, 8.0.x and master.

**Closed by MayaKirova** 2019-07-23 08:16 UTC
Labels: bug, multi-row-layout, paging, severity: medium, sorting, status: already-fixed, version: 7.3.x
