### ISSUE TITLE
In Persistent State directive isnt column group stored?

### ISSUE THREAD

**Issue by amitmoondra** [IgniteUI/igniteui-angular#8516] opened 2020-11-03 16:37 UTC
I am using igxGridState directive to store the state, but found one issue which is i am not able to reapply column group header again after the state data is applied, can you guide me in the right direction please

**Comment by amitmoondra** [comment] 2020-11-03 18:57
Can you provide me an example of how to restore multi column header/column grouping when saving data in state

**Comment by hanastasov** [comment] 2020-11-04 09:47
@amitmoondra, I am marking this as a feature request.

Meanwhile, you can either 

1. skip restoring columns when Multi Column Headers are available (State Persistence will still properly restore sorting, filtering, etc in a child column).

or

2. Implement custom managing of the columns (keep the column configuration and create grid columns dinamically from it, as shown in [this sample](https://stackblitz.com/edit/angular-recursive-columns-creation-gcc26m?file=src/app/grid/multi-column-header-template/multi-column-header-template.ts)

**Comment by amitmoondra** [comment] 2020-11-04 13:05
Hi @hanastasov ,
I did implement the second way of creating columns, which is fine worked.
But now while applying the state after creating column dynamically, how would i achieve that?
still the issue here is reapplying the state => if i just recreated the columns the state is lost completely of columns isnt it.
I want to be able to reset grouping and such after reappyling the column state.

**Comment by hanastasov** [comment] 2020-11-04 13:51
When you get/set the state of the grid, exclude the `columns` from it. try to store your columns config elsewhere, and try to recreate them on ngAfterViewInit opn your own, using the code provided.

After columns are recretared, you can restore the grid state using the `setState` Api.

Something similar to [this](https://multi-column-save-state-recursive-columns-creation-jc3kaz.stackblitz.io).

**Comment by amitmoondra** [comment] 2020-11-04 14:43
Yeah i figured that out, apologies for not informing before. Already done that and it works perfectly.

**Comment by amitmoondra** [comment] 2020-11-04 16:08
I have successfully implemented using the work around way, I hope this feature request is done soon, as this would be very helpful to be stored in state and can be very useful in many cases or other users as well.
I hope this ticket wont be closed until the feature request is completed right?

**Comment by hanastasov** [comment] 2020-11-04 16:13
I am glad the suggested works for you. Yes, the issue will stay opened until resolved.

**Comment by EddyNll** [comment] 2021-08-16 13:55
Is there any information on when this issue will be resolved/planned?

**Comment by radomirchev** [comment] 2021-08-23 11:11
Hi @EddyNll, the issue is in the planning for the next Sprint, starting on 30th of Aug.

**Closed** 2021-09-10 14:49 UTC
Labels: status: resolved, feature-request, grid: multi-column-headers, grid: state-persistence
