### ISSUE TITLE
Using excelStyleFiltering with uniqueColumnValuesStrategy throws an error

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#8178] opened 2020-09-18 07:22 UTC
## Description  
If we try to filter an igxColumn through the excelStyleFiltering and we have provided a uniqueColumnValueStrategy to the igxGrid an error is thrown. See attachments.

 * igniteui-angular version: 10.1.x
 * browser: any

## Steps to reproduce  

1. Open the attached sample https://stackblitz.com/edit/excel-style-filtering-ignore-case-workaround
2. Try to filter any of the columns

## Result  
Cannot read property 'dataType' of null error is thrown.

## Expected result  
No errors to be thrown.

## Attachments  
![excelStyleFiltering cannot read datatype of null](https://user-images.githubusercontent.com/44684385/93568364-b7aaf100-f998-11ea-9d14-fbbbbe9def1f.gif)

**Comment by DiyanDimitrov** [comment] 2020-10-27 12:22
@astaev, Could you please check if this issue is resolved by the fix of #8388.

**Comment by astaev** [comment] 2020-10-28 12:11
@mmart1n, @DiyanDimitrov 
The issue is not reproducible with 10.1.11 version, which contains the fix for #8388.

**Closed** 2020-10-28 12:23 UTC
Labels: bug, excel-style-filtering, grid, status: already-fixed, version: 10.1.x
