### ISSUE TITLE
Missing row edit border if the next Group is collapsed.

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular#2844] opened 2018-10-26 11:02 UTC
### Description  
Missing row edit overlay border if the next Group is collapsed.
* Reproducible with Dev samples.

### Steps to reproduce  - Refer to screenshot
1. Group by several columns.
2. Expand a group and start row editing in the last row.
### Result
-One of the row edit borders never appears, if the next Group below (UnitsInStock:6) is collapsed.
-If scroll down/up it never appears.

3.Cancel the editing.
4.Expand the next group (UnitsInStock:6).
5.Enter edit mode for the same row as before.
6.Scroll down/up.
### Result
The border appears/disappears.

7.Collapse the next group (UnitsInStock:6) and scroll down/up.
### Result
At some point the border disappears and the previous state is reproduced.

### Expected result  
Border should be visible at all times.

### Attachments  
![image](https://user-images.githubusercontent.com/4296944/47562469-3fac2b80-d927-11e8-9757-f0f3c023689d.png)

**Comment by Lipata** [comment] 2018-11-20 07:59
Duplicate of #3049

**Closed by Lipata** 2018-11-20 07:59 UTC
Labels: bug, duplicate, grid, row-editing, version: 6.2.x
