### ISSUE TITLE
Unable to use percentage width for igx-grid

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1474] opened 2018-06-05 18:55 UTC
### Description  
Are there currently any known issues with percentage width for the igx-grid? I'm having a hard time getting this to work properly.

I have defined the following simple grid:
![image](https://user-images.githubusercontent.com/12936286/40996272-b20a7650-6901-11e8-8d90-f4f1c771fbce.png)

This works as expected:
![image](https://user-images.githubusercontent.com/12936286/40996328-dd6df42a-6901-11e8-9ab7-439fb3027a53.png)

However, if I try to use percentage for the width, like this:
![image](https://user-images.githubusercontent.com/12936286/40996426-00ba7430-6902-11e8-8060-565edcfad386.png)

I, for some reason, end up with this:
![image](https://user-images.githubusercontent.com/12936286/40996583-723e94b0-6902-11e8-9015-11281ff35238.png)

The igx-grid__thead, igx-grid__tbody ect seems to be set in pixels instead of percentage. As you can see, the grid itself has the correct size, but not the content.

I have tried to reproduce this on a fork of the stackbliz sample on https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html#data-grid, but it seems to work fine in the sample.

**Comment by zdrawku** [comment] 2018-06-06 07:10
Could you share with us both samples. First thing that I would check is the product version, I guess you are using 6.0.0 for both?

**Comment by Eralmidia** [comment] 2018-06-06 07:49
I have set up a stackbliz. For some reason, I can're reproduce the same issue I'm seeing in our dev, but this sample also show that there is some issue: https://stackblitz.com/edit/angular-pmxpyk-ishzfs?file=app%2Fgrid%2Fgrid.component.html

As you can see, the grid rows are not rendered. If you however move them out of the wrapping divs, they do render (I'm testing on Chrome atm).

Yes, we're on 6.0
![image](https://user-images.githubusercontent.com/12936286/41023424-a8df3e42-696c-11e8-8376-fa0a1dcee20d.png)

**Comment by Aleksandyr** [comment] 2018-06-07 08:40
@Eralmidia We were unable to reproduce the issue with the widths you have.
As for the height firstly you haven't set height on the grid or on the parent that's why the rows are not visible. You can refer to the edited [sample ](https://stackblitz.com/edit/angular-pmxpyk-zlnhge) to see that with set height everything works fine.
Secondly I would like to point out that we do not support % width per column so this could be one of the problems you have with the widths because whenever you set some width per column into percentage it preserves it as pixels. Please make sure you have considered the things I have pointed out and be sure you have edited your sample correctly. On the other hand we have to consider the update of the grid documentation with these details.

**Comment by Eralmidia** [comment] 2018-06-08 06:06
Hi Aleksandyr

Thank you, I will make a note of the things you mentioned, and the increase in documentation is welcome. But a followup to this: if you can't set percentage for columns, how exactly are you able to make a responsive design, where a table suits different screen sizes and devices?

Also, unfortunately, this only solves the examples of Stackblitz, and not my original issue. I'm still seeing unstability in our dev environment. Do you have any other things for me to check out? As mentioned in the first post, I'm not only seeing issues with columns as percentage, but the grid itself. Setting the grid in px renderes it nicely, setting it to percent does not. And if I try to render the following simple test grid:
![image](https://user-images.githubusercontent.com/12936286/41141428-31e51398-6af2-11e8-9fef-1de8231b5e66.png)
with a data source of
![image](https://user-images.githubusercontent.com/12936286/41141462-53662e58-6af2-11e8-999a-cbb3f995f030.png)
I'm getting the following error:
![image](https://user-images.githubusercontent.com/12936286/41141504-70763948-6af2-11e8-95e5-007cd4a152f0.png)

It seems like the grid is unable to read the data:
![image](https://user-images.githubusercontent.com/12936286/41141575-be85187a-6af2-11e8-9b73-0204981292ef.png)

**Comment by Aleksandyr** [comment] 2018-06-11 13:11
Hello @Eralmidia 
The responsiveness is based on the view port of the grid. As you may noticed you are allowed to set width into percentage per grid but not per column which means that the displayContainer of the grid become responsive and whenever you try to resize you will notice that the columns remain the same.

Sorry I couldn't reproduce your problem with the width set into percentage and the error which is thrown from the code above. I tested the approaches many times and every time it worked fine.
I can propose you to send me an isolated working sample which reproduces your issues so I could see clearly what exactly the problem. Till than I am unable to guess what happened.

**Comment by Aleksandyr** [comment] 2018-06-11 14:24
@Eralmidia I would like to inform you that the set of percentage per column is supported but only when all of the columns are declared into percentage. But then you won't have horizontal virtualization because the sum of the all column widths would make 100% which would be the whole width of the grid. Respectively you won't be able to pin or resize columns. These features won't be available just because the columns will fit the whole grid so you won't need pining as for the resizing we do not support resizing per column which width is declared into percentages.

**Comment by Eralmidia** [comment] 2018-06-12 07:06
Unfortunately reproducing this in an isolated sample doesn't seem to be possible. As of now, I'll just have to stick to the following hack, which seems to work:
![image](https://user-images.githubusercontent.com/12936286/41274909-6c7eba2e-6e1f-11e8-90f2-e92e39cc3d7d.png)

Triggering a window resize does for some reason render the grid at correct width when using percentage width.

I'll try to dig more into it, and also await the next release, to see if anything changes then. Feel free to close this issue if you do not consider it a valid issue. If not I'll report back if I find anything that might help anyone encountering this later on.

**Comment by zdrawku** [comment] 2018-06-12 12:07
@Eralmidia, my suggestion is to use grid.reflow() method:

```
   /**
     * Recalculates grid width/height dimensions. Should be run when changing DOM elements dimentions manually that affect the grid's size.
     */
    public reflow() {
        this.calculateGridSizes();
    }
```

**Comment by Eralmidia** [comment] 2018-06-12 12:56
Like this?
![image](https://user-images.githubusercontent.com/12936286/41291728-c8199bc0-6e50-11e8-8268-4af8b299538e.png)

It doesn't seem to have any effect...

**Comment by Aleksandyr** [comment] 2018-06-12 13:10
@Eralmidia This won't work because **onColumnInit** is trigger on [ngAfterContentInit](https://angular.io/api/core/AfterContentInit) which is triggered before the initialization of the DOM. Could you please try to subscribe for [ngAfterViewInit](https://angular.io/api/core/AfterViewInit) which is triggered after the initialization of the whole view of the component. There you can try to **reflow** the grid.

**Comment by Eralmidia** [comment] 2018-06-12 13:30
Thank you. This actually made me discover something intereseting. There seems to be some kind of timing issue here. This code does not work:
![image](https://user-images.githubusercontent.com/12936286/41293279-22c7bc60-6e55-11e8-9eda-027034e477f7.png)
Resulting in the grid rows looking like this:
![image](https://user-images.githubusercontent.com/12936286/41293364-5a589762-6e55-11e8-8a5d-2901e046a20a.png)

However, if I do this:
![image](https://user-images.githubusercontent.com/12936286/41293421-8241c03c-6e55-11e8-8349-7ddfe091437f.png)

The grid renderes just fine:
![image](https://user-images.githubusercontent.com/12936286/41293461-97bf4eb6-6e55-11e8-9b10-97f5f7e747ee.png)

**Comment by Aleksandyr** [comment] 2018-06-13 06:46
@Eralmidia I could assure you that this is not a problem with the grid. It seems that this problem is on level application so you could take some time of investigating what could cause it. You can try to investigate whether this issue is not caused by some third party library.

**Comment by Eralmidia** [comment] 2018-06-13 12:41
I'm sorry, I don't understand what you mean by that last part: "whether some other component do not shrink the grid by getting from the content where the grid is". We do use a navigation drawer for a left hand side menu, but I tried removing it and nothing changed. I'll try to search some more. It does actually work even with 
![image](https://user-images.githubusercontent.com/12936286/41351508-dcd55650-6f16-11e8-877b-059302c2037b.png)

so all it needs, seems to be a single tick delay for some reason.

**Comment by Aleksandyr** [comment] 2018-06-14 07:08
@Eralmidia I think in your case the navigation drawer is not a problem as you said that you tried without this component. So it seems that this is the solution for your scenario. I'm happy that we have found a solution for you, so if you haven't further questions we could close the issue as resolved.

**Closed** 2018-06-14 07:31 UTC
Labels: bug, grid, status: in-review, version: 6.1.x
