### ISSUE TITLE
igxGrid demo country name blocked by flag

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-angular#557] opened 2018-02-08 01:33 UTC
### Description  
At any resolution, in the last column of the igxGrid demo the country name is covered by the flag. At some resolutions the name is abbreviated with ellipses, but in those cases the ellipses are covered over as well.

### Steps to reproduce  

1. https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
2. ...
3. profit

### Result  
country names covered by flag in each row

### Expected result  
country name shows below flag

**Comment by SlavUI** [comment] 2018-02-08 09:13
Hi John we are in any way redoing the Sample of the grid so soon there will be a new Grid Demo.

**Comment by kdinev** [comment] 2018-02-08 13:35
I don't see this behavior though:

![image](https://user-images.githubusercontent.com/1472513/35975507-ac36fc08-0ce5-11e8-9d4c-1560b1465f58.png)

**Comment by SlavUI** [comment] 2018-02-09 11:55
@jVanZwieten we can't reproduce the issue and I have tried all available browsers :) closing reopen if necessary.

**Closed by SlavUI** 2018-02-09 11:55 UTC

**Comment by zdrawku** [comment] 2018-02-09 15:37
The same issue was logged already IgniteUI/igniteui-angular-samples#3. The new sample based on the latest code wont have this misalignment issue.
