### ISSUE TITLE
[igx-datepicker] DatePicker field in grid cannot be scrolled with Page UP/DOWN

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-angular#5613] opened 2019-08-07 13:51 UTC
## Description  
When a date-picker editor is opened inside of an igx-grid and the grid has a scroll bar, using `Page Up` / `Page Down` to navigate the months in the date-picker causes the grid to scroll and close the date-picker calendar.

 * igniteui-angular version: 8.1.x
 * browser: N/A

## Steps to reproduce  

1. Go to the [grid editing demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html)
2. Start editing the `Order Date` column of the first row
3. Open the date-picker calendar drop down
4. Navigate to the previous month with `Page Up` (this works, since the grid is scrolled to top)
5. Navigate to the next month with `Page Down`

## Result  
The grid scrolls to the bottom and the date-picker closes.
You can see that the month page has changed during the date-picker closing animation.

## Expected result  
The grid does not scroll.
The calendar's month properly changes.

**Comment by nrobakova** [comment] 2019-08-08 09:00
This issue is duplicate of the the bug #4587

**Closed** 2019-08-08 13:15 UTC
Labels: bug, cell-editing, date-picker, duplicate, grid, hierarchical-grid, severity: low, status: in-review, tree-grid, version: 8.1.x, version: 8.2.x
