### ISSUE TITLE
igx-accordion single branch expand has a slight jump when opening a new panel

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#10902] opened 2022-01-25 13:22 UTC
## Description  
When opening a new section of the `igx-accordion`, with single branch expand enabled, a slight visual jump is observed when the opening and closing animations are finishing.

 * igniteui-angular version: 13.0.x
 * browser: Chrome

## Steps to reproduce  

1. Open https://www.infragistics.com/angular-demos/layouts/accordion-sample-1
2. Enable single branch expand
3. Open the first panel and then open the fourth panel.

## Result  
The whole component has a slight jump at the end of the animations.

## Expected result  
The transitions should end smoothly.

**NOTE**: I'm pretty certain this is caused by the additional margins applied to the open panel.

**Comment by kdinev** [comment] 2022-01-25 13:29
I'm pretty certain this is caused by the additional margins applied to the open panel.

**Comment by teodosiah** [comment] 2022-01-26 15:23
Since I have determined that the jump is caused by padding applied to the igx-expansion-panel-body in the demos, I've created a [new issue](https://github.com/IgniteUI/igniteui-angular-samples/issues/2916) in the samples repo and will close this one.

**Closed by teodosiah** 2022-01-26 15:23 UTC
Labels: :bug: bug, :eyes: status: in-review, :firecracker: severity: medium, accordion
