### ISSUE TITLE
Moving is not working as expected when using virtualized columns

### ISSUE THREAD

**Issue by SebastianCarreira** [IgniteUI/igniteui-angular#11291] opened 2022-03-25 17:50 UTC
## Description  
Describe the issue.

 * igniteui-angular version: 13.1.x
 * browser: Chrome/Edge

## Steps to reproduce  

1. Open the following example: https://stackblitz.com/edit/angular-dftekt-rw3jyd?file=src/app/grid/grid-moving-sample/grid-moving-sample.component.html
2. Scroll to the "header20" column (to get some columns virtualized)
3. Move "header21" column to the left
![chrome_XjNGzzHov5](https://user-images.githubusercontent.com/38963991/160174634-594fc322-a999-4cfa-a948-a7c132fce223.gif)

## Result  
It seems to move, but then it goes back to its old position.

## Expected result  
It should be moved as expected. 

## Attachments  
Might be related to: https://github.com/IgniteUI/igniteui-angular/issues/11116

**Comment by MayaKirova** [comment] 2022-03-28 07:56
@dkamburov This seems to be a duplicate of https://github.com/IgniteUI/igniteui-angular/issues/11116
This is already fixed in 13.1.x

**Closed** 2022-04-11 10:40 UTC
Labels: :bug: bug, status: already-fixed
