### ISSUE TITLE
igx-datePicker layout is off when "vertical" input is set to true.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#716] opened 2018-03-07 05:42 UTC
### Description  
igx-datePicker layout is off when `vertical` input is set to true.
```
<igx-datePicker [vertical]="true"></igx-datePicker>
```

### Result  
![image](https://user-images.githubusercontent.com/15909409/37075057-46dffc40-2213-11e8-9eff-8da960839974.png)

### Expected result  
![image](https://user-images.githubusercontent.com/15909409/37075457-2b49b320-2215-11e8-84b1-6dccef63de88.png)

### Attachments  
Here is a reproducible sample. 
[igx-date-picker.zip](https://github.com/IgniteUI/igniteui-angular/files/1787906/igx-date-picker.zip)

**Comment by kdinev** [comment] 2018-03-07 09:26
Is this reproducible in all browsers?

**Comment by kdinev** [comment] 2018-03-07 09:47
@tkiryu The `vertical` option is undocumented because of this issue. We're aware of it. Thanks for logging it, but undocumented options should not be used.

**Comment by tkiryu** [comment] 2018-03-07 10:52
@kdinev, thank you for your information.

Yeah, I know `vertical` is not documented, but  I'm creating a sample app, which needs to use `vertical` option, and I found the issue. That's why I logged it just in case.

Thanks for your time for taking care of this issue.

**Comment by rkaraivanov** [comment] 2018-03-15 08:25
Closed via #770

**Closed by rkaraivanov** 2018-03-15 08:25 UTC
Labels: bug, date-picker, regression, severity: high
