### ISSUE TITLE
HierarchicalGrid's layout is broken when press shift +tab

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular#4277] opened 2019-03-12 06:49 UTC
## Description  
HierarchicalGrid's layout is broken when trying to navigate from first cell to the filtering chips in the headers.
 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  

1. Open [Hierarchical Gird MCH sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/multi_column_headers.html)
2. Pin the first column group
3. Click over the first cell in the grid
4. Press shift + tab

## Result  
![image](https://user-images.githubusercontent.com/34240583/54180011-21446800-44a3-11e9-82d3-ad907f0eb47d.png)

## Expected result  
![image](https://user-images.githubusercontent.com/34240583/54180050-42a55400-44a3-11e9-802f-e9198f3712e5.png)

**Comment by skrustev** [comment] 2019-03-12 16:02
@ddincheva This seems to be already fixed on staging.

**Comment by ddincheva** [comment] 2019-03-13 06:35
@skrustev i think is still reproducible .. this is screenshot from today of staging 
![image](https://user-images.githubusercontent.com/34240583/54258274-cf671500-456a-11e9-8e65-4c6657ebbe3c.png)

**Comment by skrustev** [comment] 2019-03-13 09:49
@ddincheva Yes looked at it and I was able to reproduce it this time. Thanks.

**Comment by skrustev** [comment] 2019-03-14 17:21
Since there is an ongoing refactoring of the filtering navigation it should resolved in PR #4267

**Closed** 2019-04-01 14:02 UTC
Labels: bug, column-pinning, hierarchical-grid, severity: medium, status: resolved, version: 7.2.x
