### ISSUE TITLE
On IE11, igxGrid does not show its vertical scrollbar next to data row when grid width is set in pixel

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#4536] opened 2019-04-15 02:07 UTC
## Description  
When grid width is set in pixel, grid's vertical scrollbar is not rendered next to data row. 
(Setting grid width in % does not cause the issue.)

 * igniteui-angular version: 7.2.4
 * browser: IE11

## Steps to reproduce  

1. Run the attached sample
2. Observe the vertical scrollbar

## Result  
The vertical scrollbar of the grid is not next to the data row. Here is the screenshot of it.
![image](https://user-images.githubusercontent.com/14340675/56103527-534b5d00-5f6e-11e9-82c4-dc3b014a03f0.png)

## Expected result  
The vertical scrollbar is next to the grid data row.

## Attachments  
[app1.zip](https://github.com/IgniteUI/igniteui-angular/files/3078195/app1.zip)

**Comment by ChronosSF** [comment] 2019-11-27 13:50
@radomirchev , the reported issue is resolved, however, if you run the sample on IE11, the horizontal scrollbar container incorrectly spans across the whole width of the page. This is because it has 100% width and is a child of a container with "display: grid". 

To resolve this we should either use "display: block" (or some other workaround for IE11) - @simeonoff may be able to comment or that. Or we should strictly set the width of elements such as that horizontal scrollbar.

I am attaching a sample with updated refs. Please, let me know if we should apply a code fix for this.

**Comment by ChronosSF** [comment] 2019-11-27 13:55
![Capture1](https://user-images.githubusercontent.com/2188411/69729058-575b7200-112e-11ea-9cfb-6bca22f19b38.PNG)
![Capture2](https://user-images.githubusercontent.com/2188411/69729059-588c9f00-112e-11ea-8ea3-6fa029d5f527.PNG)
[app1.zip](https://github.com/IgniteUI/igniteui-angular/files/3897121/app1.zip)

**Comment by desig9stein** [comment] 2019-12-02 13:50
> In Angular, most of the styles are prefixed implicitly thanks to the Autoprefixer plugin.
> For prefixing grid layouts, however, you need to enable the Autoprefixer grid property with the comment `/* autoprefixer grid:on */.`

We have that in our documentation, [click here](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html)

You need to add  `/* autoprefixer grid: on */ ` somewhere above the igx-core()  in order to get the appropriate styling for IE11.

I am closing the issue since this is not a bug!

**Comment by desig9stein** [comment] 2019-12-02 13:55
@ChronosSF Can you verify and close the issue?

**Comment by ChronosSF** [comment] 2019-12-02 13:57
Yes, I'll handle it from here, thanks!

**Comment by ChronosSF** [comment] 2019-12-02 14:35
Yes, works perfectly with autoprefixer, didn't know about this

**Closed by ChronosSF** 2019-12-02 14:35 UTC
Labels: browser: ie-11, grid, scroll, severity: medium, status: resolved
