### ISSUE TITLE
Grid-Master-Detail does not show any arrow or detail?

### ISSUE THREAD

**Issue by Mateen858** [IgniteUI/igniteui-angular#7369] opened 2020-05-19 10:09 UTC
I am using Grid-Master-Detail. There is a directive IgxGridDetail. where to find this directive? Because I am unable to show any detail and I believe its due to missing this directive. 
Help please

**Comment by hanastasov** [comment] 2020-05-21 07:36
Duplicate of #7374

**Closed by hanastasov** 2020-05-21 07:36 UTC
Labels: question
