### ISSUE TITLE
TreeGrid ESF column moving throws an error

### ISSUE THREAD

**Issue by onlyexeption** [IgniteUI/igniteui-angular#9410] opened 2021-04-21 10:28 UTC
### Description  
When moving the first column via ESF, moving it back in its starting position throws an error in the console. Also, the column gets back to its place when focusing out of the ESF when. Both scenarios can be reproduced by moving it at least two times.

### Steps to reproduce  

1. Open the tree grid [excel style filtering sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/excel-style-filtering)
2. In the first demo, open the ESF on column Product ID
3. Move it right 2 times
4. Move it left

### Result  
An error is thrown in the console and the column gets back to its place.

### Expected result  
Should move column correctly.

### NOTE 
This is reproducible for a column with cell template that contains `*ngIf` only with enabled Ivy.

### Attachments  
![image](https://user-images.githubusercontent.com/19392175/115539101-41ab9700-a2a5-11eb-9da6-d6ea443db7b7.png)

**Comment by DiyanDimitrov** [comment] 2021-04-23 13:02
@ChronosSF, could you please look at this issue since it is related to the Column Moving?

**Comment by hanastasov** [comment] 2021-05-26 06:36
The grid `columnList`, which is manipulated when moving a column, when resetting grid columns collection from grid state, etc,. is resolved by a @ContentChildren collection, which is a dynamic query by Angular definiton. This means that this query is resolved after a change detection. Angular lists some of the most common issues with dynamic queries here, where we read:

> Code depending on a query result can suddenly stop working as soon as an *ngIf or an *ngFor is added to a template.

Angular claims to have made changes that resolved the issue in version 9, but everything explained in this article seems exactly what happens. Unfortunately I have been not able to reproduce this in a new isolated sample yet. There is also a difference in computations between Ivy and ViewEngine, this is why issue is only reproduced when Ivy is used. Stackblitz do not use Ivy by default, and the same samples work ok in Stackblitz.

Thus, I am suggesting to use the workaround that was recommended in #8129: use the columns template setter to assign templates:

```html
<igx-grid #grid1 [data]="data" height="400px" width="100%" [autoGenerate]="false">
  <ng-container *ngFor="let column of columns">
      <igx-column [field]="column.fieldKey" [header]="column.headerText" [dataType]="column.dataType"
           [headerTemplate]="headerTemplate"
          [cellTemplate]="cellTemplate" >
      </igx-column>
  </ng-container>
</igx-grid>

<ng-template let-value #cellTemplate>
  <div>{{ value }}</div>
</ng-template>
```

**Closed** 2021-05-26 07:47 UTC
Labels: grid: column-moving, ivy, status: in-review
