### ISSUE TITLE
Last column header is a bit wider than the cells

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#1230] opened 2018-05-02 16:03 UTC
### Description  
Last column header is a bit wider than the cells.

### Steps to reproduce  

1. Go to [https://stackblitz.com/edit/angular-d6mf92](https://stackblitz.com/edit/angular-d6mf92)
2. Observe last column header and cells.

### Result  
Header is wider than the cells.

### Expected result  
Header and cells are equal in width.

**Comment by hanastasov** [comment] 2018-05-03 08:06
Related to https://github.com/IgniteUI/igniteui-angular/issues/1115

**Comment by bkulov** [comment] 2018-11-30 11:36
I'm closing this issue because it's a duplicate of #1115.

**Closed by bkulov** 2018-11-30 11:36 UTC
Labels: duplicate, grid, severity: medium, status: not-a-bug, version: 6.1.x
