### ISSUE TITLE
Date Picker with type="box" is not aligned properly

### ISSUE THREAD

**Issue by Svetloslav15** [IgniteUI/igniteui-angular#10964] opened 2022-02-08 08:20 UTC
## Description  
When we use dataPicker with type="box", data is not aligned properly with calendar icon.

## Result  
Data is misaligned

## Expected result  
Icon and data should be aligned in one line

## Attachments  
![image](https://user-images.githubusercontent.com/33124382/152946037-9e9ce063-06d4-4d52-8db4-24612f23d750.png)

**Comment by kdinev** [comment] 2022-05-10 11:55
@simeonoff I'm not able to reproduce the exact behavior from the screenshot, but I still see some slight misalignment. Also the picker becomes rather big when a label is added:

![image](https://user-images.githubusercontent.com/1472513/167622641-4f082df0-79ed-4a37-8aab-cad04318360b.png)
![image](https://user-images.githubusercontent.com/1472513/167622672-051b6eb6-eeb4-4cc0-875d-a088ad0cce54.png)

**Comment by desig9stein** [comment] 2022-05-11 13:07
@Svetloslav15 I also can't reproduce the behavior from your screenshot. Can you give me more info, what browser did you use and what version of the product?

@kdinev I can't reproduce the behavior from your screenshots also. Can you share that stackblitz sample?

Here is a screenshot from the dev-demos master branch.
<img width="665" alt="Screenshot 2022-05-11 at 15 58 27" src="https://user-images.githubusercontent.com/21260963/167856246-5c14ef09-9c49-432b-97a2-a2c262787978.png">

**Comment by simeonoff** [comment] 2022-05-12 07:55
> 

I betcha the "misalignment" is not misalignment at all but a label consisting of empty spaces.

**Comment by kdinev** [comment] 2022-05-16 10:13
@desig9stein Here's the [stackblitz](https://stackblitz.com/edit/angular-dmpm2a?file=src/app/datepicker-sample-1/datepicker-sample-1.component.html) I was looking at. It's the very first sample in the date picker topic.

**Comment by desig9stein** [comment] 2022-05-16 11:45
@kdinev for some reason the igxlabel directive is not working correctly, the `igx-input-group__label` class Is missing from the label.
 I think it will be better to create a separate issue for that.

**Comment by kdinev** [comment] 2022-05-16 12:09
@desig9stein There is no point to close this one and open another one. We can just change the title and description of this issue?

**Comment by desig9stein** [comment] 2022-05-16 12:37
@kdinev I just added `IgxInputGroupModule` inside the `app.module.ts` and everything started to work just fine. However, I am not sure if this is the correct solution. If that solution is OK, don't you think it will be better to create an issue in the samples repo to update all samples as we may have more?

**Comment by kdinev** [comment] 2022-05-16 12:40
Sounds like a component issue to me... The datepicker module should include everything it needs. @Lipata can you comment on this?

**Closed** 2023-04-28 14:45 UTC
Labels: :bug: bug, styling, :firecracker: severity: medium, :white_check_mark: status: resolved, :date: date-picker, version: 15.1.x
