### ISSUE TITLE
Deprecation message shown when opening the autocomplete drop-down list

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-angular#4189] opened 2019-03-06 09:34 UTC
## Description  
When you open the drop-down list using the arrow keys or by typing inside the input the following message is shown:
_IgxDropDownItemBase.isFocused: IgxDropDownItemBase `isFocused` property is depracated.
Use `focused` instead._

 * igniteui-angular version: 7.2.x
 * browser: N/A

## Steps to reproduce  

1. Focus the autocomplete input
2. Press "Arrow Down" or type "a"
3. Take a look at the Console

## Result  
_IgxDropDownItemBase.isFocused: IgxDropDownItemBase `isFocused` property is depracated.
Use `focused` instead._

## Expected result  
No deprecation message is shown

**Comment by ViktorSlavov** [comment] 2019-03-07 08:46
Duplicate of https://github.com/IgniteUI/igniteui-angular/issues/4167, closing

**Closed by ViktorSlavov** 2019-03-07 08:46 UTC
Labels: autocomplete, bug, severity: low, status: in-review, version: 7.2.x
