### ISSUE TITLE
Igx-grid editable don't lose the focus, show this message "You have 0 changes in this row", when we click on button "skip_next"

### ISSUE THREAD

**Issue by MiguelPetrotec** [IgniteUI/igniteui-angular#8711] opened 2020-12-14 16:02 UTC
## Description  
Don't lose the focus, show this message "You have 0 changes in this row", when we click on button "skip_next".

I only have 1 editable column in this grid and I have navigation on this screens and I the context of the firstly edited screen passes over the other screens.
The best thing is when some lost focus or something must save of allow to ask to the user if he wants to save of discard.

Look at the video to see the behavior:
https://www.loom.com/share/b65c1110663c4c98a783481f252dfa82

 * igniteui-angular version:  "@infragistics/igniteui-angular": "^10.2.5",
 * browser: Chrome

**Comment by MiguelPetrotec** [comment] 2021-01-08 13:52
I have a editable grid with active row edit, I change the data and the edit mode stays active.

**Comment by damyanpetev** [comment] 2021-01-11 13:30
## Steps to reproduce

1. Open this sample [https://stackblitz.com/edit/github-rsraq7](https://stackblitz.com/edit/github-rsraq7?file=src%2Fapp%2Fgrid%2Fgrid-row-editing-sample%2Fgrid-row-editing-sample.component.ts)
2. Start row editing on a record (e.g. change ReorderLevel on Aniseed Syrup on row with ID 3)
3. Click the Change data button

## Result  
Grid row editing (guessing same w/ cell) remains active after a complete data change, which IMO leave the editing (thus the Grid itself) in an invalid state, since the edit is still tied to it's old row ID and can cause unexpected behavior.

## Expected result  
I would expect the grid editing to exit when the data changes as I see no reason for it to remains active in such case.

**Comment by Aleksandyr** [comment] 2021-06-09 08:26
@MiguelPetrotec after further investigation, it turns out that the potential change that could fix your issue interferes with the remote grid virtualization which has been described [here](https://github.com/IgniteUI/igniteui-angular/pull/8782#issuecomment-760154666)

The workaround we could provide you is to invoke [endEdit](https://www.infragistics.com/products/ignite-ui-angular/docs/typescript/latest/classes/igxgridcomponent.html#endedit) when changing your data, so you can exit the edit mode and decide if you would like to commit the changes or not.

**Comment by Aleksandyr** [comment] 2021-06-14 07:12
@MiguelPetrotec If there are no questions we are going to close this issue and consider it as resolved?

**Closed** 2021-06-21 07:08 UTC
Labels: bug, grid: cell-editing, grid: general, grid: row-editing, version: 10.2.x, version: 11.0.x
