### ISSUE TITLE
Igx-combobox dropdown goes to the top of view while scrolling the page.

### ISSUE THREAD

**Issue by Vighnesha2801** [IgniteUI/igniteui-angular#12718] opened 2023-03-06 12:51 UTC
## Description  
Describe the issue.
Here, We are using igx-combo inside the igx-grid-excel-style-filtering. So, whenever we try to scroll the page the dropdown sticks to the top of the view.
**_html_**:- 
`<igx-grid-excel-style-filtering>
<igx-combo
            [overlaySettings]="getCustomOverlay(combo)"
            [data]="data"  
            [valueKey]="'name'"
            [displayKey]="'name'"                   
            [filterable]="false"
            #combo
            [(ngModel)]="selectedData"
            (ngModelChange)="updateOption($event, column);"></igx-combo>
</igx-grid-excel-style-filtering>`

**_typescript_**:-
getCustomOverlay(combo: IgxComboComponent): OverlaySettings {
        const positionSettings: PositionSettings = {
            horizontalDirection: HorizontalAlignment.Left,
            horizontalStartPoint: HorizontalAlignment.Right,
            verticalDirection: VerticalAlignment.Bottom,
            verticalStartPoint: VerticalAlignment.Bottom,
        };
        return {
            target: combo.inputGroup.element.nativeElement,
            positionStrategy: new ConnectedPositioningStrategy(positionSettings),
            scrollStrategy: new AbsoluteScrollStrategy()
        };
    }

 * igniteui-angular version: 13.2.4
 * browser: 110.0.5481.178

## Result  
What is the actual result after following the steps to reproduce?
The dropdown gets attached to top of the view.

## Expected result  
What is the expected result after following the steps to reproduce?
The dropdown should be closed when the web is scrolled

## Attachments  
Attach a sample if available, and screenshots, if applicable.  [](url)

[igx-combo.webm](https://user-images.githubusercontent.com/121025954/223106221-8aacbc28-b18d-4ea3-af58-4773971b2f6b.webm)

**Comment by Vighnesha2801** [comment] 2023-03-15 12:21
@JamesBender @kaznovac @brianlagunas Any update on this issue?

**Comment by kaznovac** [comment] 2023-03-15 13:40
Hi @Vighnesha2801 (sorry if I'm being excessively directive, or pointing to overly obvious state) this is an open-source project, I'm sure maintainers will be happy to accept a Pull request according to the [Contributing Guide](https://github.com/IgniteUI/igniteui-angular/blob/dc629406d515546d58140407f4840c1f0aa5eb5a/.github/CONTRIBUTING.md).

However, if you need immediate support you can always purchase support contact from the company behind the project [here](https://www.infragistics.com/how-to-buy/product-pricing).

Calling out recent/random contributors won't rise this issue's priority.

**Comment by Vighnesha2801** [comment] 2023-03-15 14:03
We have already purchased the support. So, where should I raise this issue? @kaznovac

**Comment by ChronosSF** [comment] 2023-03-15 14:32
@Vighnesha2801 , you can submit a support case here: https://account.infragistics.com/support-cases

However, this indeed looks like a bug which we'll have to investigate and fix. Support may be able to offer a workaround that could help if the issue is time-sensitive.

I should also point out that 13.2 is not longer supported so any fix will be released for 14.2 and 15.0 only. Do you have plans to upgrade to later versions of Angular?

**Comment by onlyexeption** [comment] 2023-04-06 08:31
@Vighnesha2801 I've had a thorough look into your issue. I suppose you're using the combo in one of the excel style filtering templates. Since you're using a component that the grid does not know about, you should also handle it's closing by closing it whenever the excel style filter closes. Unfortunately, this is currently unachievable as the ESF lacks any exposed events for closure. To address this issue, I suggest  you submit a [feature request](https://github.com/IgniteUI/igniteui-angular/issues/new?assignees=&labels=%3Atoolbox%3A+feature-request%2C%3Anew%3A+status%3A+new&template=feature_request.md&title=) to expose this event in the ESF.

**Closed** 2023-04-18 11:36 UTC
Labels: status: not-a-bug, combo, grid: excel-style-filtering, version: 13.2.x
