### ISSUE TITLE
[IgxGrid] Selecting an item from IgxDropDown embedded in the cell is not reflected immediately from the second time.

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-angular#7898] opened 2020-07-31 04:30 UTC
## Description  
[IgxGrid] Selecting an item from IgxDropDown embedded in the cell is not reflected immediately from the second time.

 * igniteui-angular version: 10.0.5
 * browser: Chrome

## Steps to reproduce  

1. Open the Demo sample in the https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html.
Link to the Stackblitz sample: https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-editing

2. Double-click an "Available At" cell and choose one of the items.

3. Click another "Available At" cell and choose one of the items.

## Result  
The selected item does not look selected. The text in the cell is not updated.
Note: If you move the mouse cursor to the header area, the view is updated and the selected item is selected in the view, too.

## Expected result  
The selected item looks selected and the text in the cell is also updated.

**Comment by ddincheva** [comment] 2020-10-22 10:32
Hello @norikois ,
The problem that you described is no longer reproducible in our latest versions: 10.2.0 and 10.1.10; but I have noticed that an error is thrown by the IgxComboComponent in version 9.1.21; Here are the steps to reproduce the problem:
1. Open the following [sample](https://stackblitz.com/edit/github-autpbn?file=src/app/grid/grid-editing-sample/grid-editing-sample.component.html)
2. Open in edit mode some cell from the column Available At
3 Open the combo and select a few items
4. Over some other cell 
5. Observe the browsers console

![image](https://user-images.githubusercontent.com/34240583/96859999-e2420b00-146a-11eb-94f0-22f5626666c0.png)

**Comment by valadzhov** [comment] 2020-11-20 10:38
Closing the issue since it is fixed in #8468.

**Closed by valadzhov** 2020-11-20 10:38 UTC
Labels: bug, combo, grid, severity: medium, status: in-development, version: 10.2.x, version: 11.0.x
