### ISSUE TITLE
When dynamically created the igx-linear-bar is not applying its values when there is animation

### ISSUE THREAD

**Issue by dkamburov** [IgniteUI/igniteui-angular#1068] opened 2018-04-19 11:14 UTC
### Description  
The igx-linear-bar is not applying its correct values when used as a template in igxCell and its animations are enabled.

### Steps to reproduce  

1. Open https://stackblitz.com/edit/crm-landing-page-4rd4yl
2. Scroll to Ratio column
3. Navigate or scroll a bit in a way that Ratio column will remain into view

### Result  
The igx-linear-bar is changing its values.

### Expected result  
The igx-linear-bar should be retained.

### Attachments  
![image](https://user-images.githubusercontent.com/1182001/38988404-b9cdd13e-43db-11e8-99a1-2d8134cafae7.png)

**Comment by zdrawku** [comment] 2018-05-21 12:07
Related to https://github.com/IgniteUI/igniteui-angular/issues/1362. The current issue could be fixed with the fixes that was included in the latest version of the Virtualization. This should be tested again.

@tiliev could you please check if the issue is still reproducable.

**Comment by sboykova** [comment] 2018-07-19 14:06
Currently, the Ratio column is empty.
![ratio](https://user-images.githubusercontent.com/11226391/42947469-0e286ef6-8b76-11e8-95c5-d356627e1021.png)

**Comment by Aleksandyr** [comment] 2019-09-27 11:59
The issue is not reproducible anymore with the latest 8.2.0.

**Closed** 2019-09-27 11:59 UTC
Labels: bug, grid, severity: low, status: in-review, version: 7.1.x
