### ISSUE TITLE
Wrong cell focus after cell editing

### ISSUE THREAD

**Issue by RolandTa** [IgniteUI/igniteui-angular#6517] opened 2020-01-22 16:42 UTC
## Description  
Tab movement after cell changes on a grid with a sorting expression will not focus the correct row.

 * igniteui-angular version: 9.0.0-beta.3
 * browser: Chrome 79.0.3945.130

## Steps to reproduce  
https://stackblitz.com/edit/angular-vrmqat
1. Change the productname from "Chang" to "AAA"
2. Tab to the next cell

## Result  
The selected editable cell after the tab movement will remain on the same rowIndex. Additionally the shown value in the editbox will show the wrong value of the old rowdata.

## Expected result  
The cell selection after tab movement should be based on the rowID and not the rowIndex. ie. the editable row should be maintained.

## Attachments  
https://stackblitz.com/edit/angular-vrmqat

**Comment by ddincheva** [comment] 2020-01-24 08:09
Hello @RolandTa ,
The behavior that you described is by design. When we have sorting or filtering applied and change the value in cell that belongs to a column, which is filtered or sorted and press tab the next cell from the same row index in set in edit mode. If this behavior do not fulfill your use case you can easily change that by customizing default grid keyboard navigation as is described in[ our documentation](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/keyboard_navigation.html#custom-keyboard-navigation).
The other problem that you report that the value of the next cell which is set in edit mode is a bug, which should be fixed in PR #6534 .

**Closed** 2020-01-27 15:45 UTC
Labels: bug, grid, status: resolved, version: 9.0.x
