### ISSUE TITLE
With search API, rows are not fully scrolled into view when few summary results are used (fewer than by default)

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#1375] opened 2018-05-22 11:00 UTC
### Description  
With search API, rows are not fully scrolled into view when few summary results are used (fewer than by default)

**NOTES:**
For example if we have 2-3 summaries and try to scroll to a specific row (internally through API), not the entire row gets scrolled into view.

### Steps to reproduce  

1. Download and run the attached sample application.
2. Type "fin" in the input below the grid.
3. Press "Arrow Down" 3 or more times.

### Result  
The bottom record is **not** fully in view.

### Expected result  
The bottom record is fully in view.

### Attachments  

![scroll](https://user-images.githubusercontent.com/12784974/40358550-3f1edff8-5dc8-11e8-8fec-b0aca5be5c90.gif)
[igxGridSample.zip](https://github.com/IgniteUI/igniteui-angular/files/2026280/igxGridSample.zip)

**Comment by skrustev** [comment] 2018-07-25 14:33
This seems to be duplicate with issue #1886

**Comment by ChronosSF** [comment] 2018-07-26 08:49
@tachojelev , please check if the issue is duplicate to #1886 and close it if this is the case.

**Comment by tachojelev** [comment] 2018-07-26 12:34
I checked this issue and it is still reproduced. (Decrementing the grid's height in the sample with 20-30px will reproduce it even more severely)

**Closed** 2018-07-26 13:41 UTC
Labels: bug, duplicate, grid, severity: medium, status: in-review, summaries, version: 6.1.x
