### ISSUE TITLE
Pending changes count is not properly updated when after the last change the focus is shifted to the overlay buttons.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular#3984] opened 2019-02-22 10:04 UTC
## Description  
Pending changes count is not properly updated after changing the value of the last (or first) field and shifting the focus to the Cancel & Done buttons via Tab (Shift + Tab).

 * igniteui-angular version: 7.2.x, 7.1.x
 * browser: N/A

## Steps to reproduce  

1. Run Grid Row Editing Dev demo
2. Enter edit mode on any row
3. Edit the last cell
4. Press "Tab" to shift the focus to the Cancel button 
5. Note the count of changes

## Result  
The count remains 0 (unchanged).

## Expected result  
The count should be updated to 1.

**Comment by bazal4o** [comment] 2019-02-26 09:52
When the last cell is tabbed out and the "Done/Cancel" buttons are highlighted the last cell on the row is left in edit mode, because if no cell is in edit mode the edit row should be closed. If you hit tab 3 times to focus the first cell on the row - the count is updated correctly. If you Shift + Tab the last cell the count is calculated correctly.

**Comment by gedinakova** [comment] 2019-02-26 11:37
The cell does retain the editing class but technically it is not in edit mode as one cannot change its value after tabbing out, so I would expect the change to be counted.

**Comment by bazal4o** [comment] 2019-02-27 07:48
I think we need to clarification from the UX team, because if a cell exits edit mode - none of the cells on the row will be in edit mode which by design should close the row edit, but keyboard navigation requires (by design) going to Done and Cancel buttons. Tabbing out from the cell removes the focus from the cell which automatically prevents it from being edited. 
@StefanIvanov any thoughts on this ?

**Comment by StefanIvanov** [comment] 2019-02-27 08:18
I think that @gedinakova has a good point and the count should be updated also when the focus leaves the cell as she correctly pointed out. The edit mode is not visually shown to the user and the described situation will definitely cause frustration, which we want to avoid.

**Closed** 2019-07-01 17:16 UTC
Labels: feature, grid, row-editing, severity: medium, status: resolved, version: 8.0.x
