### ISSUE TITLE
[chrome][igx-grid] any event handlers attached to column header template won't work when movable = true.

### ISSUE THREAD

**Issue by tkiryu** [IgniteUI/igniteui-angular#4480] opened 2019-04-07 16:12 UTC
## Description  
Any event handlers attached to column header template won't work when movable = true on Chrome. I think this is related to #4376.

 * igniteui-angular version: 7.2.4
 * browser: Chrome 73

## Steps to reproduce  

1. Go to https://stackblitz.com/edit/igx-grid-column-header-event-handling-issue-when-movable
2. Click a pin icon on column header.
3. Click a button on  column header.

## Result  
2. The column won't be pinned.
3. An alert won't show.

## Expected result  
2. The column should be pinned.
3. An alert should show.

**Comment by SAndreeva** [comment] 2019-04-10 14:57
@tkiryu, you are right, the issue is related to #4376. The root cause for this behavior however are some changes introduced with the latest version of Chrome  and there is no completely clean fix from our side. As a workaround I would offer setting the draggable attribute to false on the desired elements in the template. See the modified sample:
https://stackblitz.com/edit/igx-grid-column-header-event-handling-issue-when-movable-uudkih?file=src/app/grid/grid-sample-pinning/grid-pinning.component.html

**Comment by bkulov** [comment] 2019-04-22 07:10
I'm closing this issue as it's third party issue and there is a workaround.

**Closed by bkulov** 2019-04-22 07:10 UTC
Labels: bug, grid, severity: medium, status: not-to-fix, version: 7.2.x
