### ISSUE TITLE
When a cell in pinned column is selected the text is not correct

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#3356] opened 2018-12-07 14:44 UTC
### Description  
Describe the issue.

 * igniteui-angular version: 7.0.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridColumnPinning
2. Scroll horizontal
3. Click on cell in column Contact title

This issue is similar to issue #3163, but now it happens only for selected cell

### Result  
Cell text is not correct

### Expected result  
Cell text should be correct

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/49653890-eca5b800-fa3e-11e8-8c5e-6a3b532073b9.png)

**Comment by simeonoff** [comment] 2018-12-10 09:07
I am closing this as it's a duplicate of #3163

**Closed by simeonoff** 2018-12-10 09:07 UTC
Labels: grid, pinning, severity: high, styling, version: 7.0.x
