### ISSUE TITLE
igx-input-group throws an error inside an expansion panel

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#11318] opened 2022-03-31 08:49 UTC
## Description  
The `igx-input-group` takes its child input directive as a static content child and throws an exception if the input group is placed inside a component like the `igx-expansion-panel`.

 * igniteui-angular version: 13.1.7
 * browser: all

## Steps to reproduce  

1. Create an input group inside an expansion panel
```html
<igx-expansion-panel-body>
  <igx-input-group type="border" class="user-input_1">
    <input type="text" [required]="false" igxInput />
    <label igxLabel>Year</label>
  </igx-input-group>
</igx-expansion-panel-body>
```
2. Run the application
3. You can do the same by using the [App Builder](https://appbuilder.indigo.design/) to and dropping an expansion panel and an input group as content of the panel.

## Result  
Exception is thrown.

## Expected result  
There should be no exception.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/161015681-ab21dfe0-b4d8-4a62-960d-a043e95ef499.png)

**Comment by wnvko** [comment] 2022-04-01 11:18
Actually the issue is in the `Text Area` component. Steps to reproduce:
1. Drop text are on design surface in AppBuilder.
2. Generate Angular application.
3. Run the application.

Will fix this in Angular library definitions.

**Comment by wnvko** [comment] 2022-04-04 07:10
Fixed in CodeGen

**Closed** 2022-04-04 07:11 UTC
Labels: :bug: bug, :fire: severity: high, :white_check_mark: status: resolved, input-group, version: 13.1.x
