### ISSUE TITLE
Build warning on SASS - [WARNING] Expected identifier but found ":"

### ISSUE THREAD

**Issue by ricardosaracino** [IgniteUI/igniteui-angular#11282] opened 2022-03-24 20:27 UTC
## Description  

I am seeing this warning in my build

```
Warning: ▲ [WARNING] Expected identifier but found ":"

    styles.f54eadddfc18812a.css:37987:2:
      37987 │   : var(--igx--);
            ╵   ^
```

 * igniteui-angular version: 
```
  "dependencies": {
    "@angular/animations": "^13.2.5",
    "@angular/cdk": "^13.2.5",
    "@angular/common": "^13.2.5",
    "@angular/compiler": "^13.2.5",
    "@angular/core": "^13.2.5",
    "@angular/forms": "^13.2.5",
    "@angular/material": "^13.2.5",
    "@angular/platform-browser": "^13.2.5",
    "@angular/platform-browser-dynamic": "^13.2.5",
    "@angular/router": "^13.2.5",
    "@fontsource/titillium-web": "^4.5.2",
    "@fortawesome/fontawesome-free": "^6.0.0",
    "@infragistics/igniteui-angular": "13.1.0",
    "@ngrx/effects": "^13.0.2",
    "@ngrx/router-store": "^13.0.2",
    "@ngrx/schematics": "^13.0.2",
    "@ngrx/store": "^13.0.2",
    "@ngrx/store-devtools": "^13.0.2",
    "@ngx-translate/core": "^14.0.0",
    "@ngx-translate/http-loader": "^7.0.0",
    "angular-mentions": "^1.4.0",
    "bootstrap": "^5.1.3",
    "date-fns": "^2.28.0",
    "jszip": "^3.7.1",
    "lodash.isequal": "^4.5.0",
    "material-icons": "^1.10.7",
    "ngx-permissions": "^13.0.1",
    "rxjs": "~7.5.4",
    "zone.js": "~0.11.4"
  },
```

## Steps to reproduce  

1. Step 1
2. Step 2
3. ...

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
What is the expected result after following the steps to reproduce?

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by didimmova** [comment] 2022-03-28 07:25
Can you please provide steps to reproduce the problem?

**Comment by simeonoff** [comment] 2022-03-28 07:33
Closing as it's a duplicate of #11288

**Closed by simeonoff** 2022-03-28 07:33 UTC
Labels: :bug: bug, :hammer_and_wrench: status: in-development
