### ISSUE TITLE
Cell content overlaps the cell

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#1769] opened 2018-06-28 06:54 UTC
### Steps to reproduce  

1. Go to https://stackblitz.com/angular/dknvxamllrr
2. Enter some text in the search area, for example "Airlines"

### Result  
See how the content in the last cell stars overlapping the cell.

**Comment by gedinakova** [comment] 2018-07-06 07:42
Fixed by https://github.com/IgniteUI/igniteui-angular/pull/1901

**Comment by DDavidkov** [comment] 2018-07-06 10:57
Yeah, once you update the dependencies in stackblitz, the issue is no longer reproducible.

**Closed by DDavidkov** 2018-07-06 10:57 UTC
Labels: bug, global-search, grid, severity: low, status: already-fixed, status: resolved, styling, version: 6.1.x
