### ISSUE TITLE
In Edge when page is scrolled resize indicator position is not correct

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#4067] opened 2019-02-27 09:20 UTC
## Description  
In Edge when page is scrolled resize indicator position is not correct

 * igniteui-angular version: 7.2
 * browser: Edge

## Steps to reproduce  

1. Open dev sample gridColumnMoving
2. Scroll down the page
3.Start resizing a column

This bug can be related to the bug #3908 

## Result  
Resize indicator starts from second row

## Expected result  
Resize indicator should starts at the column

## Attachments  
Attach a sample if available, and screenshots, if applicable.  

![image](https://user-images.githubusercontent.com/11463104/53479311-6f0fa800-3a81-11e9-8a05-10c8f4a6e5eb.png)

**Comment by SAndreeva** [comment] 2019-02-27 16:06
Duplicate of #3908

**Closed by SAndreeva** 2019-02-27 16:06 UTC
Labels: browser: edge, bug, grid, resizing, severity: medium, version: 7.2.x
