### ISSUE TITLE
IE 11 Grid width in iframe is broken

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular#1330] opened 2018-05-16 12:03 UTC
### Description  
When opening a grid in a StackBlitz, we always get a grid with width "100%"

### Steps to reproduce  

1. Open https://stackblitz.com/edit/ie11-broken-grid in IE 11

### Result  
The grid has a width 100px.

### Expected result  
The grid should be wider.

### Explanation
This happens because of this [line](https://github.com/IgniteUI/igniteui-angular/blob/master/src/grid/grid.component.ts#L1018). 
Basically when I execute 
```
document.defaultView.getComputedStyle(document.getElementById("igx-grid-0")).getPropertyValue("width");
```
in Chrome, Firefox and Edge I get `708px`:

![github-gulp](https://user-images.githubusercontent.com/6439482/40115665-dd8262b8-5919-11e8-8b17-e1a0f3a2b282.PNG)

in IE 11 I get `100%`:

![ie-11](https://user-images.githubusercontent.com/6439482/40115679-ec8b49aa-5919-11e8-90fe-936cecd832e3.PNG)

After that in the method we have `parseInt(computed.getPropertyValue("width"), 10);` which makes the grid `100px` wide.

**Comment by tiliev** [comment] 2018-05-18 09:04
The issue is reproducible only in StackBlitz, I wasn't able to reproduce it in a controlled environment. It seems `document.defaultView.getComputedStyle` is called when the styles are not yet computed. the `display` CSS property of the grid is `grid` and this does not trigger computation when the method is called. If the `display` is `block` or `inline-block` the computation will be forced and the method will return the correct value. This however cannot help in our case.
What we can do is to add condition in [this ](https://github.com/IgniteUI/igniteui-angular/blob/master/src/grid/grid.component.ts#L1017)method. If the `getComputedStyle` returns %, get the `width` from `getBoundingClientRect().width`:

![fix](https://user-images.githubusercontent.com/6439482/40226079-726ae6dc-5a93-11e8-8e51-055804cccf86.PNG)

This would work in theory. Could be tested with tagged version only.

We have a similar issue in Firefox, but only with grids which do not have a width in px. It fixes itself after resize. [Sample](https://stackblitz.com/edit/grid-sorting-firefox-broken). Unfortunately `getBoundingClientRect().width` does not return the correct width in Firefox, there is a slight difference, but it is better than broken.

I am not aware of any workarounds for IE, for Firefox we could set width on the grids.

@MayaKirova, please share thoughts if you have something you add.
@rkaraivanov, please make a decision on how to proceed with this.

**Comment by zdrawku** [comment] 2018-08-29 08:07
After further discussion it was decided **not to include** the fix in the angular product, we are going to think of another way to handle this stackblitz issue because of the importance for IE 11 users, event the fact that we tried almost everything.

@tiliev you can go ahead and close this issue as not a bug, for this repository, and add/reopen another issue in the docfx/samples repo.

**Closed** 2018-08-29 08:18 UTC
Labels: browser: ie-11, bug, grid, severity: medium, status: in-development
