### ISSUE TITLE
Grid: Pinned column headers appear on top of filter menu

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/igniteui-angular#1078] opened 2018-04-19 19:57 UTC
### Description  
On a grid with pinned and filterable columns, when an unpinned column's filter is activated, it is displayed below the pinned column header.

### Steps to reproduce  
1. Pin a column
2. Make/Find an filterable column (pinned or unpinned)
3. Move the unpinned column as close as possible to the pinned one
4. Click on the icon to activate the filter menu

### Result  
the filter menu is displayed below the pinned column header

### Expected result  
the filter menu should be displayed above any column header.

### Attachments  
https://stackblitz.com/edit/crm-grid-sample-demo
<img width="321" alt="screen shot 2018-04-19 at 17 18 09" src="https://user-images.githubusercontent.com/13866657/39014777-001e7222-4424-11e8-8ea1-82929a2a3cf4.png">

**Comment by tachojelev** [comment] 2018-04-20 06:05
The issue seems to be a duplicate of this one - #978

**Comment by SlavUI** [comment] 2018-04-20 06:13
Closing as duplicate

**Comment by simeonoff** [comment] 2018-04-20 07:28
@tachojelev and @SlavUI No, it's not. The scenario is different. In the case above the filtering UI above is hidden by the pinned column headers. #978 describes a situation in which the filtering UI of a pinned column is covered by the header of its left sibling.

**Closed** 2018-04-21 11:15 UTC
Labels: enhancement, grid, version: 5.3.x
