### ISSUE TITLE
DatePicker: the width of the component changes after the date is set

### ISSUE THREAD

**Issue by andiesm813** [IgniteUI/igniteui-angular#11007] opened 2022-02-14 15:57 UTC
## Description  
This issue was found inside AppBuilder.
If i have a date picker in dropdown mode, and i set a date, its width increases to fit the "clear" (X) icon.
Javier Coitino reviewed this bug i created for the AppBuilder team, and he said the bug is in the Angular component behavior.

See attachment. This is the app in AppBuilder where an example of the bug is shown:
https://appbuilder.indigo.design/app/igs3w4vs5oti

## Expected result  
The Clear icon should apear within the area of the picker and not make it wider. The Ignite UI component behavior should be changed, so it allocates empty space for the clear button when no values are set (date is empty).

## Attachments  
https://user-images.githubusercontent.com/86068582/153899049-3ef51623-41e7-43f3-b7b5-85836a8a20e2.mp4

**Comment by desig9stein** [comment] 2022-05-13 08:32
@andiesm813 I don't think there is a problem with the component. I do believe that this is normal behavior for an item that is inside a flex container, in my opinion, this is expected behavior and it's not a bug.

**Comment by desig9stein** [comment] 2022-12-02 10:11
@zdrawku @simeonoff can we close this since it's not a bug?

**Closed** 2022-12-05 08:21 UTC
Labels: styling, status: not-to-fix, :firecracker: severity: medium, :date: date-picker, status: not-a-bug, version: 13.1.x
