### ISSUE TITLE
Violations in the verbose hindering the performance of the grid 

### ISSUE THREAD

**Issue by gabriel4gitcode** [IgniteUI/igniteui-angular#8474] opened 2020-10-28 09:01 UTC
## Description  
Too many violations of loading grid data. 

 * igniteui-angular version: 10.1
 * browser:  Chrome

## Steps to reproduce  

On loading content in lazy loading and non-lazy loading grid, the verbose shows too many violations warning. This does not affect the flow of the application but it does hinder the performance. For a lazy loading grid and a chunk size of say 50, the grid loads only after it loads the violations which will be around 160. For each row, there are 3 violations mainly - wheel, touchstart and touchmove.  

## Expected result  
Expecting to show no warning. 

Can this be fixed somehow? Or any workaround for it? 

![image](https://user-images.githubusercontent.com/72977481/97413862-48c29f80-1929-11eb-8dc5-dccd54fff1a8.png)

The above image shows violations for 11 rows. This increases if we increase the chunk size

**Comment by rkaraivanov** [comment] 2020-11-05 13:27
@gabriel4gitcode 
> For a lazy loading grid and a chunk size of say 50, the grid loads only after it loads the violations which will be around 160

Can you clarify what you mean by that? These are warnings in the browser console when the log level is set to `verbose`. Does that really affect your performance?

As for the warnings themselves.

Our virtualization piece uses an additional helper directive which tries to simulate scroll inertia on certain devices (as the virtualized container is not a natively scrollable). As such touch and wheel events are handled by us and we attach the respective event handler we do so without the `passive` option set. This, mind you, is by ECMA specification, but certain browsers (Chrome/Firefox) has opted certain events (touch) to be passive by default as to not clog the main thread. 
This is fine, until you want to call `preventDefault` in the event handler of a passive event listeners which gets you:
![image](https://user-images.githubusercontent.com/20106115/98246423-f1e94580-1f7a-11eb-96ad-f71f5d0d10ad.png)

Essentially, we would be transforming the warning into an error. So no, currently there is no easy workaround as we do have logic that calls `event.preventDefault()` inside the virtualization code.

**Comment by manuprathab** [comment] 2020-11-11 07:26
> ## Description
> Too many violations of loading grid data.
> 
> * igniteui-angular version: 10.1
> * browser:  Chrome
> 
> ## Steps to reproduce
> On loading content in lazy loading and non-lazy loading grid, the verbose shows too many violations warning. This does not affect the flow of the application but it does hinder the performance. For a lazy loading grid and a chunk size of say 50, the grid loads only after it loads the violations which will be around 160. For each row, there are 3 violations mainly - wheel, touchstart and touchmove.
> 
> ## Expected result
> Expecting to show no warning.
> 
> Can this be fixed somehow? Or any workaround for it?
> 
> ![image](https://user-images.githubusercontent.com/72977481/97413862-48c29f80-1929-11eb-8dc5-dccd54fff1a8.png)
> 
> The above image shows violations for 11 rows. This increases if we increase the chunk size

As this ticket closed, did you get clear feedback and get the performance issue clarified. We have the same issue but still struggling to find out the reason, and I can't find anything useful on this ticket.

**Comment by manuprathab** [comment] 2020-11-11 07:50
[lazy-loading-grid-01.zip](https://github.com/IgniteUI/igniteui-angular/files/5522598/lazy-loading-grid-01.zip)
I'm attaching the sample project file, as requested by 'Desislava Dincheva', please have a look and the issue is not gets reproduced all the time, when I refresh for a couple of times sometimes, it delays showing the content even after getting the data from the service(you can see the count of warnings gets increased and after finishing it the content shows), but sometimes it renders fast enough. Our chunk size is 100, and in this sample the total data is 77, so tried the chunk size as 70, if possible try to use a different service with more data. If you still can't see the issue, I'll take a video and share it so that it'll be very clear !

**Comment by manuprathab** [comment] 2020-11-13 14:36
[ignite.zip](https://github.com/IgniteUI/igniteui-angular/files/5537387/ignite.zip)

Here are some more clues and clear steps about the issue, also we have noted the core statement which makes the issue.

In this updated sample project(basically in all your samples), you can find 'this.grid.totalItemCount = data["@odata.count"];' (grid-sample-4.component.ts - line 52). This is the main issue in our application, when we comment out this line, the grid renders super fast, when this line is there, it takes some time to render the result as in the attached video.

In the attached video, you can see the time the service returns the data, after time point 00:03, and renders the data at 00:05, more precisely you can see that in the network tab. This is for a small amount of data of total of 77 records and chunk 20, in our original use case, we have 100s of records and chunk size is thus 100.

Also attaching the saved profile from the 'Performance' tab of chrome. Hope that will help to find the issue.

**Comment by ChronosSF** [comment] 2020-11-16 14:32
Hi @manuprathab ,

In remote virtualization the grid renders all the data you provide for it.

In your case if you want to make requests @ 100 record chunks, you can do that and reduce the amount of requests this way but in this case you should slice that data to a reasonable amount when you return it to the grid. Then cache the rest so that it is available and you don't have to make a request until the end-user reaches row # 101 for example. If you let all 100 records get assigned as the grid data source, the grid will render all of them which takes a lot of time. Ideally you want to pass only the amount of records that could be visible at once +1 to the grid. That's the amount virtualization is optimized for. For the aforementioned sample this amount is just 10 records.

The reason the sample works better than in your case is that Northwind would only ever return 20 records no matter what arguments you use to request data with (this is to save server costs I assume). If you service correctly returns 100 records when you make such a request, your sample will take 5 times as long to load just because there are that many more records to render.

Hope this helps explain the reason for this behavior.

**Comment by manuprathab** [comment] 2020-11-16 15:11
> Hi @manuprathab ,
> 
> With remote virtualization the grid renders all the data you provide for it.
> 
> In your case if you want to make requests @ 100 record chunks, you can do that and reduce the amount of requests this way but in this case you should slice that data to a reasonable amount when you return it to the grid. Then cache the rest so that it is available and you don't have to make a request until the end-user reaches row # 101 for example. If you let all 100 records get assigned as the grid data source, the grid will render all of them which takes a lot of time. Ideally you want to pass only the amount of records that could be visible at once +1 to the grid. That's the amount virtualization is optimized for. For the aforementioned sample this amount is just 10 records.
> 
> The reason this sample works better than your application is that Northwind would only ever return 20 records no matter what arguments you use to request data with (this is to save server costs I assume). If you service correctly returns 100 records when you make such a request, your sample will take 5 times as long to load just because there are that many more records to render.
> 
> Hope this helps explain the reason for this behavior.

Sorry, I hope the issue here is something else. Because the same was working for a long time, and recently it shows this kind of issue. Not sure about the version update or something, but the same was working fine earlier.

**Comment by manuprathab** [comment] 2020-11-17 15:19
[lazy-loading-grid-03.zip](https://github.com/IgniteUI/igniteui-angular/files/5554353/lazy-loading-grid-03.zip)
We have added a version-03 of the sample project, with more data(from the service), more close to our usecase. Now if you run this project, while checking the network tab, you can clearly see the time taken to render the grid after getting the data from service.

**Comment by ddincheva** [comment] 2020-11-18 08:10
@manuprathab , can you please tell us the exact version of the product where you say that in the described scenario the problem was not reproducible? Also what are the grid dimensions in your application and how many visible row do you have?

**Comment by ChronosSF** [comment] 2020-11-18 12:05
@manuprathab , your latest sample represents the exact point I was trying to make. If you inspect the grid after it gets some data loaded you'll notice there are 100 rows in the DOM. For this grid you only want 10 rows in the DOM for the best performance.

You can achieve it by changing:

```typescript
this._data.next(data.value);
```

In the `getData` method of the `RemoteServiceVirt` class to:

```
this._data.next(this._cachedData.slice(startIndex, startIndex + 10));
```

Only making the grid load 10 of the 100 records sent by the server. All 100 records are cached in _cachedData, mind you so the grid will get them from there while scrolling to the 100th record, only forcing another request after that.

**Comment by manuprathab** [comment] 2020-11-18 12:09
> @manuprathab , can you please tell us the exact version of the product where you say that in the described scenario the problem was not reproducible? Also what are the grid dimensions in your application and how many visible row do you have?

"@infragistics/igniteui-angular": "^10.1.6",

This is the version we are using and in terms of dimension, we show almost the entire screen space. there is only a collapsible panel on the left side.

**Comment by manuprathab** [comment] 2020-11-18 12:14
> @manuprathab , your latest sample represents the exact point I was trying to make. If you inspect the grid after it gets some data loaded you'll notice there are 100 rows in the DOM. For this grid you only want 10 rows in the DOM for the best performance.
> 
> You can achieve it by changing:
> 
> ```ts
> this._data.next(data.value);
> ```
> 
> In the `getData` method of the `RemoteServiceVirt` class to:
> 
> ```ts
> this._data.next(this._cachedData.slice(startIndex, startIndex + 10));
> ```
> 
> Only making the grid load 10 of the 100 records sent by the server. All 100 records are cached in _cachedData, mind you so the grid will get them from there while scrolling to the 100th record, only forcing another request after that.

@ChronosSF , we know that. But for better and smooth scrolling in terms of user perspective, we are instructed to use the cache as 100, otherwise, there will be a service call for each mouse wheel scroll or the normal scroll with scrollbar. Also, we are caching the response in the same way as in the samples, and service requests will be initiated for the first time only(for the whole data).

Also as I already told you, there was no such issue in an earlier version, we got this kind of performance issue very recently.

**Comment by manuprathab** [comment] 2020-11-18 12:16
> @manuprathab , can you please tell us the exact version of the product where you say that in the described scenario the problem was not reproducible? Also, what are the grid dimensions in your application and how many visible row do you have?

@ddincheva, you didn't get it reproduced with the latest version of sample code which I have shared 'lazy-loading-grid-03.zip' ??? That's very strange!!!

**Comment by ddincheva** [comment] 2020-11-18 12:53
> > @manuprathab , can you please tell us the exact version of the product where you say that in the described scenario the problem was not reproducible? Also, what are the grid dimensions in your application and how many visible row do you have?
> 
> @ddincheva, you didn't get it reproduced with the latest version of sample code which I have shared 'lazy-loading-grid-03.zip' ??? That's very strange!!!

That wasn't my question! I saw the problem that you described. But you claim that in an earlier version of the product your scenario was working just fine, so I would like you to share with us in which version was that?!

**Comment by manuprathab** [comment] 2020-11-18 13:54
> > > @manuprathab , can you please tell us the exact version of the product where you say that in the described scenario the problem was not reproducible? Also, what are the grid dimensions in your application and how many visible row do you have?
> > 
> > 
> > @ddincheva, you didn't get it reproduced with the latest version of sample code which I have shared 'lazy-loading-grid-03.zip' ??? That's very strange!!!
> 
> That wasn't my question! I saw the problem that you described. But you claim that in an earlier version of the product your scenario was working just fine, so I would like you to share with us in which version was that?!

Ok, I got you. Sorry, I didn't notice the version, because we have upgraded the versions many times and we have noticed this issue recently only. The reason behind it is, we were concentrating on the other features and were using non-lazy loading mode at that time. But as you could see the issue, and if you can proceed with a solution it'll be fine, or if you really think the worked version will help you better, we'll try to downgrade checking the git versions and will let you know! As we are busy now, not sure about when we can check in that way.

**Comment by ddincheva** [comment] 2020-11-27 10:04
Hello @manuprathab ,
I managed to test your scenario in our major versions back to 8.2.x and the overall performance is the same. The problem that you experienced @ChronosSF has already described why is happening and a possible solution for that. 
To sum up, you can either reduce the chuck size that you are setting to the grid and perform caching in your application in order to reduce the number of request to your data service or you can also try to get your whole data at once and assign it to the grid so the grid can calculate the optimal chunk size for itself.

**Closed by ddincheva** 2020-11-27 10:04 UTC
Labels: status: in-development, status: in-review
