### ISSUE TITLE
Grid first row is hidden behind grid header

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#844] opened 2018-03-27 11:40 UTC
### 
If the grid has SELECT for rows per page after the user pick something for example 10 rows per page
This adds some negative margin-top to the first row and the user is no longer able to see that row

### Steps to reproduce  
1. Create grid which has at least 15 or more rows
2. Enable paging=" true" 
3. Select to see 10 rows per page
4. Scroll to the bottom of the grid using a mouse wheel or keyboard nav
5. Scroll back to see the first row of the grid

### Result  
The first row goes under the grid header.
The user can't navigate to that row either with mouse or keyboard navigation

### Expected result  
The user should be able to reach The first-row with mouse and keyboard navigation

### Attachments  
![screenshot-2018-3-27 igniteui for angular samples 2](https://user-images.githubusercontent.com/21260963/37965141-b7cd6f8c-31cc-11e8-96a1-4494f3e3c306.png)

**Comment by Aleksandyr** [comment] 2018-04-05 11:15
@desig9stein Unable to reproduce with the latest changes related to the virtualization.

**Comment by SlavUI** [comment] 2018-04-05 11:16
Closing reopen if needed

**Closed by SlavUI** 2018-04-05 11:16 UTC
Labels: bug, grid
