### ISSUE TITLE
Tabbar alignment off for the Phone Contacts tab in the Angular Tabbar

### ISSUE THREAD

**Issue by MikeTechSpeak** [IgniteUI/igniteui-angular#671] opened 2018-02-26 17:18 UTC
### Description  
TabBar alignment off for the contacts tab. 
This is likely a control issue and not the CLI, but logging it here because even if it is determined to be not a bug in the control, the CLI sample looks bad as is, and should be corrected. 

### Steps to reproduce  
Use the cli to create a new project and add a tabbar template to it
Click through the tabs

### Result  
The first tab, the phone contact tab, the tabbar is indented
Note, if you add a lot of text, such that it word wraps it will look correctly. 

### Expected result  
The tabbar positioning should not change per tab, regardless of content. 

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by gedinakova** [comment] 2018-03-01 13:50
This is not a tabbar issue. The problem is with the tab component created in the CLI. As the application centers its components by default (uses igxLayoutJustify="center"), the smaller width of the first tab's content, compared to the paragraphs on the second and third tabs, causes the misalignment described here. Updating the tab-content class with max-width of around 700px resolves the issue:
.tab-content {
    padding: 16px;
    max-width: 700px;
}

Reassigning to PwnJS.

**Comment by SlavUI** [comment] 2018-04-19 10:52
Closing this one reopen if needed

**Closed by SlavUI** 2018-04-19 10:52 UTC
Labels: bottom-nav, bug, severity: medium
