### ISSUE TITLE
Angular Grid Records per page drop down issue

### ISSUE THREAD

**Issue by deepakvia** [IgniteUI/igniteui-angular#7595] opened 2020-06-15 11:04 UTC
## Description  
When grid is opened in full screen mode, Grids Records per page drop down is not opening properly. Please check attached file. 

 * igniteui-angular version: 8.2
 * browser: 

## Steps to reproduce  
Run attached zip file with sample application.

## Result  
What is the actual result after following the steps to reproduce?

## Expected result  
It should show dropdown list properly. 

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
[GridDemoApp.zip](https://github.com/IgniteUI/igniteui-angular/files/4779796/GridDemoApp.zip)

**Comment by deepakvia** [comment] 2020-06-22 12:08
Hi Team,

please update on this issue. 

Thanks
Deepak

**Comment by skrustev** [comment] 2020-06-23 14:35
Hello @deepakvia,
May I ask why you are using a separate package for fullscreen and not using the default provided by the browser fullscreen capability by pressing F11 or the respective API?

I am asking because it seems that the way the `screenfull` package is forcing full screen seem to be interfering with the per page orverlay.

**Comment by skrustev** [comment] 2020-06-23 15:26
Hello @deepakvia,
This seems to be cause by the use of the third party `screenfull` package, because it renders only the grid wrapper element while the grid perPage dropdown is rendered outside the grid in the body. 

This seem to be already addressed in our latest branch though as the dropdown will render inside the grid by default and that should fix it in this case. It will be available for our next major version.

**Comment by skrustev** [comment] 2020-06-23 15:27
Hello @deepakvia,
Your issue seems to be caused by the use of the third party screenfull package, because it renders only the grid wrapper element while the grid perPage dropdown is rendered outside the grid in the body.

This has already been addressed in our latest branch though as the dropdown will render inside the grid by default and that should fix it in this case. It will be available for our next major version.

**Closed** 2020-08-19 14:56 UTC
Labels: bug, grid, paging, status: third-party-issue, version: 8.2.x
