### ISSUE TITLE
How to add columns to grid part of a custom component?

### ISSUE THREAD

**Issue by eestein** [IgniteUI/igniteui-angular#5286] opened 2019-07-03 11:09 UTC
## Question  
I've created a custom paged grid, like this:

```html
<igx-grid #grid id="paged-grid-{{counter}}" [data]="data" width="960px" height="gridHeight" [paging]="true"
    [perPage]="perPage">
    <ng-content></ng-content>
</igx-grid>
<ng-template #customPager>
    <button [disabled]="isFirstPage" (click)="paginate(0, false)" igxButton="icon" igxRipple igxRippleCentered="true">
        <igx-icon fontSet="material">first_page</igx-icon>
    </button>
    <button [disabled]="isFirstPage" (click)="previousPage()" igxButton="icon" igxRipple igxRippleCentered="true">
        <igx-icon fontSet="material">chevron_left</igx-icon>
    </button>
    <span>{{currentPage + 1}} of {{totalPages}}</span>
    <button [disabled]="isLastPage" (click)="nextPage()" igxRipple igxRippleCentered="true" igxButton="icon">
        <igx-icon fontSet="material">chevron_right</igx-icon>
    </button>
    <button [disabled]="isLastPage" (click)="paginate(totalPages - 1, false)" igxButton="icon" igxRipple
        igxRippleCentered="true">
        <igx-icon fontSet="material">last_page</igx-icon>
    </button>
    <select style="margin-left: 1rem;" (change)="perPage = parseToInt($event.target.value);">
        <option [value]="val" [selected]="perPage == val" *ngFor="let val of [5, 10, 15, 25, 50, 100, 500]">{{val}}
        </option>
    </select>
</ng-template>
```

When I try to use it like this (`sl-paged-grid`):

```html
<sl-paged-grid [resource]="shareholderResource" [perPage]="pageSize">
    <igx-column field="id" [sortable]="true" [header]="idHeader"></igx-column>
    <igx-column field="displayName" [sortable]="true" [header]="nameHeader"></igx-column>
    <igx-column field="totalSharesPercent" [sortable]="true" [header]="totalSharesPercentHeader">
        <ng-template igxCell let-totalSharesPercent>
            {{totalSharesPercent}}%
        </ng-template>
    </igx-column>
</sl-paged-grid>
```

This is the error:

> ERROR Error: "Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[IgxGridComponent -> GridBaseAPIService]: 
  StaticInjectorError(Platform: core)[IgxGridComponent -> GridBaseAPIService]: 
    NullInjectorError: No provider for GridBaseAPIService!

If I move the columns definition to the custom component (sl-paged-grid) it works. But obviously that's not an option, since it's a custom component I need to be able to define columns per requesting component.

How can I make this work?

 * igniteui-angular version: 8.0.1
 * browser: Firefox

**Comment by kdinev** [comment] 2019-07-04 07:28
@eestein My suggestion is to move your column definitions to array of objects defined in your component, and then to `*ngFor` the columns from the objects. Adding a column would then be as easy as pushing an object into your columns array. You can use this sample as reference for how to define columns this way: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid.html#state-persistence

**Comment by eestein** [comment] 2019-07-04 10:40
@kdinev is there no way to do it with ng-content? That'll help me to maintain igniteui's pattern. Also, using your suggestion, how would I go by in regards to template columns?

**Comment by kdinev** [comment] 2019-07-04 11:52
@eestein The problem is that the `igx-column` definitions are not content. They are just used as meta to generate content according to. As for the templates, you can still define conditional templates, based on your column definitions.

This will be rendered only for the column with field "totalSharesPercent".
```html
<ng-template *ngIf="column.field === 'totalSharesPercent'" igxCell>
  ...
</ng-template>
```

**Comment by eestein** [comment] 2019-07-04 12:08
I'm going to have to be pretty specific about those template columns following your suggestion. Which will prevent me from using custom templates from anywhere paged grid component is called. For every new template, I'm gonna have to head over to paged grid and add the new template. That's not ideal.

Thanks.

**Comment by kdinev** [comment] 2019-07-08 06:59
@eestein I will have @rkaraivanov and @ChronosSF look into your request to see if there's a way to make this work when wrapped in another component, but for now you would have to use the suggestion that I gave you.

**Comment by ChronosSF** [comment] 2019-10-23 07:24
@kdinev , @radomirchev , apart from allowing external templates for columns I am not sure what else we can do for this scenario. Something like this:

```html
<ng-template igxColumnTemplate forField="totalSharesPercent">
</ng-template>
```

I am not sure it would make much difference in the customer's case though. Let me know what you think.

**Comment by rkaraivanov** [comment] 2020-01-06 08:16
I'm closing this issue.
Even if we make the DI services optional there will still be the problem with the content projection of the columns. 
The other approach is going back to #4966 but we've already rejected it.

**Closed by rkaraivanov** 2020-01-06 08:16 UTC
Labels: grid, question
