### ISSUE TITLE
When in the tree grid are pinned columns and scroll horizontal the cells text is over the pinned text

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#3163] opened 2018-11-27 07:39 UTC
### Description  
When in the tree grid are pinned columns and scroll horizontal the cells text is over the pinned text

 * igniteui-angular version: 6.2.x 7.0.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample treeGrid
2. Expand row ANATR
3. Scroll horizontal

### Result  
The cells text is over the pinned text.

### Expected result  
Scrolling should not change pinned column text

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/49065937-2ea55180-f228-11e8-8c21-8f07ec411a13.png)

**Comment by DiyanDimitrov** [comment] 2018-11-27 12:31
This issue is probably a design issue since the selected cell background is semi-transparent. Note that this is not specific to the tree grid, it is reproducible for a normal grid too.

**Comment by rkaraivanov** [comment] 2018-12-05 17:11
Closed via #3195

**Closed by rkaraivanov** 2018-12-05 17:11 UTC
Labels: pinning, regression, severity: high, status: resolved, tree-grid, version: 6.2.x, version: 7.0.x
