### ISSUE TITLE
igx-timepicker  In dropdown mode if we click cancel button without selecting any value null values are displaying

### ISSUE THREAD

**Issue by sjPrajwal** [IgniteUI/igniteui-angular#6494] opened 2020-01-20 09:04 UTC
## Description  
In Dropdown mode if we click cancel button without selecting any value null values are displaying and after that can't select any time.

 * igniteui-angular version: 4.3.3
 * browser: Chrome

## Steps to reproduce  
Active dropdown mode and give min and max values
1. open the timepicker in dropdown mode
2.  click on cancel button and notice the input field value, null will display
3. again clear field and try to select the time again still it will display null.

## Result  
on cancel, time picker taking null values

## Expected result  
on cancel, time picker shouldn't take any values.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment] 2020-01-20 12:41
Hi, @sjPrajwal.

I'm trying to reproduce your problem and I'm using the following [demo](https://stackblitz.com/edit/time-picker-mix-max?file=src/app/timepicker-sample-8/timepicker-sample-8.component.html). When I follow your steps I see an error, but in the input I see the following value: `NaN:NaN AM`. Please tell me if this is what you see, or if the problem is different, please modify the demo that I'm sending you. Thank you in advance!

**Comment by sjPrajwal** [comment] 2020-01-20 15:58
Hi team,

Yes, issue is same as produced by you, please fix it asap.


Regards,
Prajwal.

**Comment by sjPrajwal** [comment] 2020-01-23 05:37
Hi @Lipata @jackofdiamond5 ,
any updates on the issue..?

**Comment by jackofdiamond5** [comment] 2020-01-23 08:50
Hi @sjPrajwal, 

Please excuse our delayed response. We have moved this issue to our next sprint where we will take a closer look at how we may fix it. In the meantime, we remain open for any additional questions or comments you might have.

**Comment by sjPrajwal** [comment] 2020-02-04 08:15
Hi @jackofdiamond5 ,
Any updates on the issue reported...?
I am looking status resolved..

**Comment by Lipata** [comment] 2020-02-05 07:44
Hi, @sjPrajwal. We are currently making code review and verifying the issue. Expect that this will be part of our 8.2.19 and 8.1.24 releases, next Monday.

**Comment by sjPrajwal** [comment] 2020-02-05 07:48
Hi Nikolay,

Thank you very much for your reply.

I found one more issue.
can i ask here only.

Regards,
Prajwal.

**Comment by Lipata** [comment] 2020-02-05 08:09
Hi, @sjPrajwal.

If it is #6585, we are checking it and we will write in the corresponding issue. If the issue you are experiencing is another one and is not also related to the current one, we prefer a new issue with demo (e.g. in StackBlitz). Thank you, @sjPrajwal.

**Comment by sjPrajwal** [comment] 2020-02-05 08:41
Hi Nikolay,

i am asking  #6585
<https://github.com/IgniteUI/igniteui-angular/issues/6585> issue only,
waiting for your reply.

Thanks a lot.

**Comment by sjPrajwal** [comment] 2020-02-11 11:35
Hi @Lipata ,
Any updates regarding this bug??

**Comment by Lipata** [comment] 2020-02-11 19:09
Hi, @sjPrajwal.

We currently released 8.2.19 and 8.1.24, the packages that I have mentioned. However, because of the official Angular 9 release last week, we needed to hold some of our PR and the first release our Angular 9 compatible version. In addition to that our 8.2.x and 8.1.x and 9.0.x should be synchronized and currently, the fix is not still merged. Please expect the fix in the next versions and thank you for the patience!

**Closed** 2020-02-17 13:35 UTC
Labels: bug, severity: medium, status: resolved, time-picker, version: 8.1.x, version: 8.2.x, version: 9.0.x

**Comment by Lipata** [comment] 2020-02-19 16:00
@sjPrajwal you can use [igniteui-angular@8.2.20](https://github.com/IgniteUI/igniteui-angular/releases/tag/8.2.20) or [igniteui-angular@9.0.2](https://github.com/IgniteUI/igniteui-angular/releases/tag/9.0.2)
