### ISSUE TITLE
Make Custom Grid summaries able to read more than column data

### ISSUE THREAD

**Issue by VirtualisProject** [IgniteUI/igniteui-angular#6214] opened 2019-11-27 11:33 UTC
## Is your feature request related to a problem? Please describe.
I'm currently working on implementing a grid summaries for my igx-grid. This grid in particular grid  have the following columns:

- Total units
- First pass count (how many of the total units that passed the test in the first run)
- Yield (percentage value of passed units)

I want to have a summary for average yield, but I cannot simply take the average of the 'Yield' columb for the summary, because the 'Average yield' is determined by the number to total units / first pass count. 

Therefore, i as a developer, i would like to be able to send in input parameters to custom grid summary's, so that i can make sure that IgxSummaryResult.summaryResult returns the correct value.

![image](https://user-images.githubusercontent.com/43247999/69720004-faea5980-1111-11ea-9e1e-6edee873c151.png)

## Describe the solution you'd like
Make grid summaries templateble in the Igx-column / igx-grid

**Comment by zdrawku** [comment] 2019-11-27 12:01
Hey @VirtualisProject, all data records are accessible from each column, so you can do whatever is needed with it. Two additional optional parameters are introduced in the IgxSummaryOperand `operate` method.

Example:

```typescript
class MySummary extends IgxNumberSummaryOperand {
    constructor() {
        super();
    }
    operate(columnData: any[], allGridData = [], fieldName?): IgxSummaryResult[] {
        const result = super.operate(allData.map(r => r[fieldName]));
        result.push({ key: 'test', label: 'Total Discounted', summaryResult: allData.filter((rec) => rec.Discontinued).length });
        return result;
    }
}
```

[Working sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection.html#showcase-applications)

**Comment by kdinev** [comment] 2019-11-28 08:35
Duplicate of #5754

**Comment by zdrawku** [comment] 2019-12-18 09:40
Sample - https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/summaries.html#custom-summaries-which-access-all-grid-data

**Closed by zdrawku** 2019-12-18 09:40 UTC
Labels: duplicate, feature-request
