### ISSUE TITLE
IgxGrid rows are not rendered correctly when cell container changes its height by changing column width

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular#6324] opened 2019-12-10 04:17 UTC
## Description  
IgxGrid rows are not rendered correctly when cell container changes its height by changing column width

 * igniteui-angular version: 8.2.12
 * browser: Chrome

## Steps to reproduce  

1. Sort by 'id' column
2. Narrow 'name' column to its minimum width
3. Scroll down to the bottom and scroll up to somewhere in the middle
4. Widen 'name' column
The behavior is not reproducible all the time. So please repeat the steps several times.

## Result  
A white space appears at the bottom of the grid

## Expected result  
Rows should be rendered on the white space.

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![IgxGrid_RowsRenderingIssue2](https://user-images.githubusercontent.com/14340675/70592058-baafce80-1c1b-11ea-8afb-616d68a48ac3.gif)

[igx-grid-rows-rendering-issue.zip](https://github.com/IgniteUI/igniteui-angular/files/3942990/igx-grid-rows-rendering-issue.zip)

**Comment by rkaraivanov** [comment] 2019-12-10 07:49
@ymita 
Not a bug IMO.
Once you re-template the cell you overwrite our default template which applies the overflow text style.
If you don't want the text content to re-flow on resizing and expand the rows, you can apply our ellipsis mix-in on your template.

```sass
// app.component.scss
@import "~igniteui-angular/lib/core/styles/themes/index"

.template {
    @include ellipsis()
}
```

```html
<!-- app.component.html -->
<igx-column ...>
    <ng-template igxCell let-cell="cell">
      <div class="template">{{cell.value}}</div>
    </ng-template>
</igx-column>
```

**Comment by kdinev** [comment] 2019-12-10 12:23
@ymita If the behavior is not reproducible every time, then does the view get corrected upon a further resize?

**Comment by ymita** [comment] 2019-12-11 04:44
@kdinev After resizing column, if row height becomes changed, rows are rendered correctly. Please see the updated gif file. I also updated the steps to reproduce the issue more easily.

**Comment by kdinev** [comment] 2019-12-11 08:24
@ymita Upon scroll, the correct number of rows should also get rendered after the issue appears. We try to prevent an excessive number of change detection calls to achieve optimal performance of the grid. As far as I can see, the issue hits an edge case change detection remains one cycle behind, but would be ran upon the next interaction. I'm marking this as low. We will take a look at it, but if the fix is too risky to hurts the general performance, then we would prefer to not implement it.

**Closed** 2020-01-30 18:32 UTC
Labels: bug, grid, resizing, severity: low, status: resolved, version: 8.2.12
