### ISSUE TITLE
Grid's hiding and excel dropdowns reopen after already being opened. 

### ISSUE THREAD

**Issue by MartinKamenov** [IgniteUI/igniteui-angular#4085] opened 2019-02-27 14:21 UTC
## Description  
After hiding/excel dropdown was open and user tries to close it, the dropdown is reopened instead closed.

 * igniteui-angular version: 7.2.x
 * browser: all

## Steps to reproduce  

1. Open Toolbar dev sample. (also reproduced on staging:
https://staging.infragistics.local/products/ignite-ui-angular/angular/components/hierarchicalgrid/column_hiding.html)

2. Click on the hiding button in the grid's toolbar, which should open the dropdown.
3. Click again on the same button and observe the behavior.

## Result  
The dropdown reopens.

## Expected result  
Instead the hiding dropdown should close.

## Attachments  
![hidingdropdown](https://user-images.githubusercontent.com/24592428/53496350-929b1880-3aaa-11e9-8b3e-519fe92204de.gif)

**Comment by gedinakova** [comment] 2019-02-27 14:25
@MartinKamenov This is a duplicate of https://github.com/IgniteUI/igniteui-angular/issues/4045 which is already resolved and will be available in next beta.

**Comment by MartinKamenov** [comment] 2019-02-27 14:31
@gedinakova 
Yes, seems that in the newest version issue is not reproduced.

**Closed** 2019-02-27 14:41 UTC
Labels: bug, duplicate, grid, grid-toolbar, severity: medium, status: resolved, version: 7.2.x
