### ISSUE TITLE
hierarchical grid hides parent row when collapsing child row

### ISSUE THREAD

**Issue by CoderBN1** [IgniteUI/igniteui-angular#6462] opened 2020-01-14 11:23 UTC
## Description
When setting the height attribute of a hierarchical grid and open an island  with 3 rows and open the 3 rows (there are also islands) and scroll down to see all opend rows so the first island row isn't seen in the grid window and clicking the collaps button to close the 3 island rows instantly the window is high enough to show all entries and im not able to scroll up so the parent island is not seeable and reachable anymore.

When not setting the height parameter all is working fine.  

 * igniteui-angular version: 8.2.15 , 8.1.21
 * browser: firefox, chrom with latest versions

**Comment by ChronosSF** [comment] 2020-01-14 11:51
Thank you for the bug report! Is it possible to share a small sample reproducing this? What do you set the height to so that it reproduces?

**Comment by CoderBN1** [comment] 2020-01-14 13:40
The height Attribute is set to 700 

height="700"

//app.component.ts
`import {Component} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'ngtest';

  singers = [{
    "Artist": "Naomí Yepes",
    "Photo": "assets/images/hgrid/naomi.png",
    "Debut": "2011",
    "Grammy Nominations": 6,
    "Grammy Awards": 0,
    "Tours": [{
      "Tour": "Faithful Tour",
      "Started on": "Sep-12",
      "Location": "Worldwide",
      "Headliner": "NO",
      "Toured by": "Naomí Yepes"
    }],
    "Albums": [{
      "Album": "Dream Driven",
      "Launch Date": new Date("August 25, 2014"),
      "Billboard Review": "81",
      "US Billboard 200": "1",
      "Artist": "Naomí Yepes",
      "Songs": [{
        "No.": "1",
        "Title": "Intro",
        "Released": "*",
        "Genre": "*",
        "Album": "Dream Driven"
      }]
    },
      {
        "Album": "Dream Driven",
        "Launch Date": new Date("August 25, 2014"),
        "Billboard Review": "81",
        "US Billboard 200": "1",
        "Artist": "Naomí Yepes",
        "Songs": [{
          "No.": "1",
          "Title": "Intro",
          "Released": "*",
          "Genre": "*",
          "Album": "Dream Driven"
        }]
      },
      {
        "Album": "Dream Driven",
        "Launch Date": new Date("August 25, 2014"),
        "Billboard Review": "81",
        "US Billboard 200": "1",
        "Artist": "Naomí Yepes",
        "Songs": [{
          "No.": "1",
          "Title": "Intro",
          "Released": "*",
          "Genre": "*",
          "Album": "Dream Driven"
        }]
      },
      {
        "Album": "Dream Driven",
        "Launch Date": new Date("August 25, 2014"),
        "Billboard Review": "81",
        "US Billboard 200": "1",
        "Artist": "Naomí Yepes",
        "Songs": [{
          "No.": "1",
          "Title": "Intro",
          "Released": "*",
          "Genre": "*",
          "Album": "Dream Driven"
        }]
      },
      {
        "Album": "Dream Driven",
        "Launch Date": new Date("August 25, 2014"),
        "Billboard Review": "81",
        "US Billboard 200": "1",
        "Artist": "Naomí Yepes",
        "Songs": [{
          "No.": "1",
          "Title": "Intro",
          "Released": "*",
          "Genre": "*",
          "Album": "Dream Driven"
        }]
      }]
  }];

}
`

// app.component.html

`<igx-hierarchical-grid #hierarchicalGrid [data]="singers" [autoGenerate]="true"
height="700">
  <igx-row-island [key]="'Albums'" [autoGenerate]="true">
    <igx-row-island [key]="'Songs'" [autoGenerate]="true">
    </igx-row-island>
  </igx-row-island>
  <igx-row-island [key]="'Tours'" [autoGenerate]="true">
  </igx-row-island>
</igx-hierarchical-grid>`

**Comment by MayaKirova** [comment] 2020-01-14 14:33
@CoderBN1 I’ve created a stackblitz sample based on your description which you can refer to here:
https://stackblitz.com/edit/angular-svbpl3
The sample uses version 8.2.15.

I have attempted to reproduce your issue using the following steps:
1)	Expand first row (Naomi Yepes)
2)	Expand all rows in first child grid.
3)	Scroll grid to the bottom.
4)	Collapse all via the parent grid header collapse button.

Using those steps I was no able to reproduce this issue. When testing this on my side the grid was scrolled back to the top showing the collapsed parent grid row.

![sample](https://user-images.githubusercontent.com/10397980/72352696-6650b080-36eb-11ea-8dab-8af88820f798.gif)


Please refer to the sample and let me know if you are able to replicate the issue using that sample.
If the sample is not an accurate representation of your scenario please feel free to modify it and share it so that it reproduces your issue.
If the steps are not exactly the same as what you do to reproduce this then please share the exact steps and/or a gif that shows the exact interactions.

**Comment by CoderBN1** [comment] 2020-01-14 14:57
So well using Mozilla FireFox:
![giphy](https://user-images.githubusercontent.com/45229647/72354656-6a2e0400-36e6-11ea-863d-627477a4f82c.gif)

**Comment by MayaKirova** [comment] 2020-01-14 15:35
@CoderBN1 Thank you for the additional information. This appears to be specific to FireFox (does not seem to reproduce in other browsers).
It seems to be related to another FireFox specific issue that is already resolved:
https://github.com/IgniteUI/igniteui-angular/issues/6369
The fix solves this issue as well and it will be included in one of the next version releases.

**Comment by ChronosSF** [comment] 2020-01-23 13:45
@CoderBN1 , the issue should be resolved in the latest 8.2.16 version. Please, let us know if you still experience it after upgrading.

**Closed by ChronosSF** 2020-01-23 13:45 UTC
Labels: browser: firefox, bug, hierarchical-grid, status: resolved
