### ISSUE TITLE
Cell edited style is black and text is not visible

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular#2853] opened 2018-10-26 16:21 UTC
### Description  
When there is transactions or row editing enabled for the grid, the cells that have new, pending values are not visible, when not focused.

### Steps to reproduce  

1. Open Grid Row Editing sample
2. In "Grid with rowEditing and with transactions" edit some cell value.
3. Focus another cell

### Result  
The edit cell value is not visible, cause it is black and the cell background is also black

### Expected result  
Cell that is edited and not focused should have visible value

![image](https://user-images.githubusercontent.com/2621802/47579298-371e1a00-d954-11e8-8499-021beacfa9c4.png)

![image](https://user-images.githubusercontent.com/2621802/47579312-42714580-d954-11e8-9a4e-60636d233ee3.png)

**Comment by desig9stein** [comment] 2018-11-22 14:33
The issue is fixed with https://github.com/IgniteUI/igniteui-angular/pull/3106

**Closed** 2018-11-22 14:34 UTC
Labels: dark-green-theme, version: 6.2.x
