### ISSUE TITLE
When scrolling, igxGrid selection scrolls.

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-angular#775] opened 2018-03-15 15:18 UTC
### Description  
When scrolling, the grid shows a different row selected to keep the selection style in view.

### Steps to reproduce  

1. clone, run: https://github.com/jVanZwieten/simple-igxGrid
2. select a cell, a row will show selected style
3. scroll

### Result  
Selection style moves across rows to stay in its relative position within visible rows.

### Expected result  
The same row stays visibly selected.

**Comment by kdinev** [comment] 2018-03-15 16:04
@jVanZwieten We actually considered this expected. However this is not going to be the case with the row selection. Why is this an issue for you and how critical is it to you?

**Comment by SlavUI** [comment] 2018-03-16 09:22
@jVanZwieten i have installed the sample but there is no Grid there and i can't reproduce the issue :)

**Comment by jVanZwieten** [comment] 2018-03-16 13:20
@SlavUI  Darn, forgot to push that.

Anyway, all the sample is is the stock grid added with the ig cli.

**Comment by jVanZwieten** [comment] 2018-03-16 13:21
@kdinev it's not critical to me ATM, just unexpected and unhelpful to the user. If we're going to fix it when row selection is implemented then that's great.

**Comment by ChronosSF** [comment] 2018-04-10 11:47
Assigning myself to check if this works when Row Selection makes into 5.3.x . Related to #812

**Comment by ChronosSF** [comment] 2018-04-24 13:09
Closing as this works with the new cell selection behavior introduced with row selection

**Closed by ChronosSF** 2018-04-24 13:09 UTC
Labels: grid, question, version: 5.3.x, virtualization
