### ISSUE TITLE
When scroll with the mouse wheel the value in datePicker editor for edited cell is empty

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular#2958] opened 2018-11-07 09:42 UTC
### Description  
When scroll with the mouse wheel the value in datePicker editor for edited cell is empty

 * igniteui-angular version: 6.2.x
 * browser: N/A

### Steps to reproduce  

1. Open dev sample gridCellEditing
2. Open a cell in column OrderDate in edit mode
3. Scroll with the mouse wheel

This issue is related to the issue #2535

### Result  
Value in the datePicker is empty

### Expected result  
Value should be correct

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/48123212-073f1280-e282-11e8-8150-a45754cf8f00.png)

**Comment by tachojelev** [comment] 2018-11-08 11:34
The issue is **not** reproduced in **6.1.x**.

**Comment by tachojelev** [comment] 2018-11-14 11:39
A possible fix for this issue would be invoking the **detectChanges()** method at the end of the **onScroll()** method of the **IgxGridForOfDirective**, however this should not be necessary since the **IgxGridBaseComponent's** verticalScrollHandler invokes the onScroll method and the detectChanges method successively.
This is why since the issue is reproduced with the scroll wheel, we may want to take a look at the **IgxScrollInertiaDirective** to resolve this issue instead of using detectChanges.

**Closed** 2018-12-07 08:11 UTC
Labels: bug, cell-editing, grid, regression, severity: medium, status: resolved, version: 6.2.x
