### ISSUE TITLE
IgxHierarchicalGrid: on the second level or further the row editing overlay disappears when scrolling

### ISSUE THREAD

**Issue by viktorkombov** [IgniteUI/igniteui-angular#9917] opened 2021-07-25 10:51 UTC
## Description  
If a row that is not on the root level is being edited and the grid is being scrolled the row editing overlay will be disappearing.

 * igniteui-angular version: 12.0.7
 * browser: all

## Steps to reproduce  

1. Open the first demo of the Hierarchical Grid Row Adding topic – [here ](https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/row-adding)
2. Expand the second row.
3. Start editing a row on the second level of the grid.
4. Scroll the grid.

## Result  
The row editing overlay is disappearing.

## Expected result  
The row editing overlay should be visible.

## Attachments  
![hgrid-scroll-on-second-level](https://user-images.githubusercontent.com/75325639/126896237-13aa1266-b14a-4946-bbec-fdc84a498f2a.gif)

**Comment by damyanpetev** [comment] 2021-07-27 11:16
After looking into this to see if the issue is with the row edit overlay setup or the Hierarchical Grid - it's kind of both, but mostly the overlay. The issue is specific to child grids with couple/no rows hitting this check:
https://github.com/IgniteUI/igniteui-angular/blob/976fb707e376fd6a70019dfc266abc0d95b235e1/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L5801-L5802
and assigning the main grid outlet instead because of it:
https://github.com/IgniteUI/igniteui-angular/blob/976fb707e376fd6a70019dfc266abc0d95b235e1/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L7233-L7239
This is done on purpose, as it's assumed the grid won't have enough space to show the row edit overlay in its default outlet which is inside the [t]body. This is fine for Grid and Tree Grid, however in the Hierarchical we redirect the main outlet of child grids to the root one:
https://github.com/IgniteUI/igniteui-angular/blob/976fb707e376fd6a70019dfc266abc0d95b235e1/projects/igniteui-angular/src/lib/grids/hierarchical-grid/hierarchical-grid.component.ts#L423-L424
This is done explicitly so the root can capture overlays (listening for open) and close them on scroll. There's a check to avoid closing the row edit overlay of course:
https://github.com/IgniteUI/igniteui-angular/blob/976fb707e376fd6a70019dfc266abc0d95b235e1/projects/igniteui-angular/src/lib/grids/grid-base.directive.ts#L3355-L3357
However this doesn't work since the row edit overlay belongs to a child grid and so is not the same as `this.rowEditingOverlay`.

I considered having a shared overlay for all grids, however there are good reasons to have more than one on the off chance multiple child grids enter edit mode.
So the only reasonable solution I see is to choose a better outlet for child grids in this scenario. Using the main outlet (assuming that's the only option) doesn't quite translate in the Hierarchical Grid, since there are options. I think the _direct_ parent's edit outlet (inside tbody) looks really promising - should both allow the overlay to go outside the smaller grid, while avoiding going to the parent/root main outlet scroll handling. This should also avoid the case where if not closed the overlay can overlap parent headers/footers/etc and allow it to behave correctly with scroll without the need for extra handling, since the tbody overflow is restricted. Two birds one stone deal and it should be reasonably easy to do that for the HGrid since `parentRowOutletDirective` getter is already in place :)

**Closed** 2021-08-23 14:27 UTC
Labels: bug, status: in-review, status: resolved, grid: row-editing, grid: hierarchical-grid, version: 12.0.x
