### ISSUE TITLE
Shadow effect for hovered floating-action buttons is unchanged for 'compact' density

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#4852] opened 2019-05-21 08:46 UTC
## Description  
Shadow effect for hovered floating-action buttons is unchanged for '**compact**' density.

 * igniteui-angular version: 7.3.x
 * browser: any

## Steps to reproduce  

1. Navigate to the following sample:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/button.html#display-density
2. Hover the floating-action button (circular one) and notice the shadow.
3. Change density to '**compact**'.
4. Hover the floating-action button (circular one) and notice the shadow.

## Result  
Shadow remains unchanged in 'compact' and looks too big for the floating-action button.

## Expected result  
Shadow gets smaller in 'compact'.

## Attachments  

![image](https://user-images.githubusercontent.com/12784974/58081514-e014b680-7bbd-11e9-9281-1b4d34e44335.png)

**Comment by desig9stein** [comment] 2019-05-21 10:21
The shadow remains the same for all density types, you can verify that by inspecting the button in different density. It's normal to visually look smaller since it's applied to a smaller element. You can close the issue as this is not a bug!

The default shadow for the FAB button is for all density types
```
box-shadow: 
    0 3px 5px -1px rgba(0, 0, 0, 0.26),
    0 6px 10px 0 rgba(0, 0, 0, 0.12),
    0 1px 18px 0 rgba(0, 0, 0, 0.08);
```

**Closed** 2019-05-22 11:08 UTC
Labels: bug, button, display-density, severity: low, status: in-review, version: 7.3.x
