### ISSUE TITLE
Grid with focused/selected column resets horizontal scroll position when the user leaves the browser tab and comes back to it

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular#8488] opened 2020-10-29 16:20 UTC
This is probably either the same issue or very closely related to #8487 . Feel free to close it as duplicate if you find it to be the same.

## Steps to reproduce  

1. Open https://www.infragistics.com/angular-demos/grid/column-selection
2. Shrink the browser window so that horizontal scrollbar appears
3. Scroll right
4. Select one of the last columns
5. Go to another browser tab
6. Come back

- The grid has its horizontal scroll reset, the first column is focused

- The grid state should remain the same between browser tab switching

**Comment by Aleksandyr** [comment] 2020-11-03 11:55
After a short discussion, It has been determined that this is the default behaviour of the browser and it is not our job to handle it. It's gonna be hacky and painful.

P.S.
The active element always tries to find the first element of the focused area. Once the tab is changed the active node gets blurred and the time we come back the focused area finds it's first focusable child which triggers the scroll.

**Comment by damyanpetev** [comment] 2020-11-18 08:44
@ChronosSF @Aleksandyr - No need for such complicated step description, since switching tabs merely causes a blur and re-focus on return. Here's a much simpler _identical_ scenario:

1. Open the sample https://www.infragistics.com/angular-demos/grid/column-selection
2. Scroll down and select a cell
3. Shift-Tab to the columns
4. Tab back into the grid

Active cell (and thus scroll position) is reset. If anything the issue is that I see no active style applied, yet when I navigate it was clearly the first cell in the grid. Horizontal scroll position seems to reset on blur, while vertical scroll on focus.

The issue is **not** about switching tabs - it's about if we want to maintain the active cell on blur and use it on the next focus. Whether we keep it or reset it to the first cell - matter of design really, though it seems simple enough to not delete the active cell on blur and use it on focus. And that's not fighting the browser behavior in any way.

**Comment by ddincheva** [comment] 2020-12-04 10:00
Since there are several issues regarding the described problem they are addressed in issue #8677 for easier tracking.

**Closed by ddincheva** 2020-12-04 10:00 UTC
Labels: active-node, bug, column-selection, duplicate, grid, status: in-review
