### ISSUE TITLE
Memory leak with tooltips or anything using overlayService

### ISSUE THREAD

**Issue by m4yorga** [IgniteUI/igniteui-angular#11609] opened 2022-05-23 20:54 UTC
## Description  
The OverlayService can easily cause memory leaks, for example, when being consumed from child components that are later destroyed. See below to reproduce the issue:

 * igniteui-angular version: 12.2.3
 * browser: Tested in Microsoft Edge, but happens in any

## Steps to reproduce  

1. Use Microsoft Edge as its DevTools contain the Detached Elements panel
2. Open [this stackblitz](https://stackblitz.com/edit/github-hwzhn1-rjuppe?file=src%2Fapp%2Fapp.component.ts)
3. Click the CREATE NESTED COMPONENT button
4. Hover on the underlined text to show the tooltip
5. Click the DESTROY NESTED COMPONENT button
6. Open the Detached Elements in DevTools
7. You will realize that the <app-test> component cannot be garbage collected 

## Result  
Any child components that display tooltips, overlays or igxToggles , such as <app-test> component in this example, are not properly disposed.

This only happens when user hovers on the text, if the tooltip is not displayed then no memory leaks occur

## Expected result  
Child components should be properly disposed, no Detached Elements should be left behind.

## Attachments  
Take a look at this gif that also demonstrates the issue
![IgniteMemoryLeak](https://user-images.githubusercontent.com/4580348/169904348-eb2c97b3-b23e-411a-a086-68ea89df9969.gif)

**Comment by valadzhov** [comment] 2022-05-27 13:54
The issue is fixed in version 12.3.25 and above.

**Closed by valadzhov** 2022-05-27 13:54 UTC
Labels: :bug: bug, :white_check_mark: status: resolved
