### ISSUE TITLE
Autofill data insert incorrectly to input field

### ISSUE THREAD

**Issue by EvgeniyZhukovets** [IgniteUI/igniteui-angular#6839] opened 2020-02-27 12:54 UTC
## Description  
When inputs autofill by browser, the label doesn`t move upper than the inserted text.

 * igniteui-angular version: 9.0.1
 * browser: Google Chrome

## Steps to reproduce  

1. Add input group with the input field and label to the page
E.g.:
```
<igx-input-group class="layout-box__el input-field">
          <label igxLabel>Password</label>
          <input igxInput type="password" name="password" required/>
</igx-input-group>
```
Same issue with 'text' input type
2. Save this field in browser to use it with autofill
3. Refresh page
4. Use autofill from browser

## Result  
<img width="123" alt="image" src="https://user-images.githubusercontent.com/22504733/75446417-73162480-5978-11ea-9d8f-85396cfb22ae.png">

## Expected result  
<img width="119" alt="image" src="https://user-images.githubusercontent.com/22504733/75446451-80331380-5978-11ea-91a5-d5333fb85e3f.png">

**Comment by EvgeniyZhukovets** [comment] 2020-05-08 10:40
Will this bug be fixed?

**Comment by Lipata** [comment] 2020-05-08 11:53
Hi, @EvgeniyZhukovets yes it will be fixed. This label is a reminder for us to prioritize it.

**Comment by kdinev** [comment] 2020-07-07 08:31
I'm experiencing a slightly different variation of this issue. My login form is bound to an `ngModel` and I get the labels positioned correctly, but in Chrome and the new Edge, there's a weird user-agent style applied. It looks like this:

![image](https://user-images.githubusercontent.com/1472513/86748300-06f1ae80-c045-11ea-8e56-a036e05938b1.png)

The user agent style is this:
```css
input:-internal-autofill-selected {
    -webkit-appearance: menulist-button;
    background-color: rgb(232, 240, 254) !important;
    background-image: none !important;
    color: -internal-light-dark-color(black, white) !important;
}
```

I hope we can get an override for this in our theme.
Here's my form:
```html
<form class="login-buttons" #userLogin="ngForm" (ngSubmit)="loginWithForm()">
  <igx-input-group class="login-button" type="border">
    <label for="username" igxLabel>Username</label>
    <igx-prefix>
      <igx-icon>person</igx-icon>
    </igx-prefix>
    <input #userName igxInput id="username" required name="username" [(ngModel)]="logininfo.username" />
  </igx-input-group>

  <igx-input-group class="login-button" type="border">
    <label for="passwordField" igxLabel>Password</label>
    <input #passwordField igxInput type="password" required id="passwordField" name="passwordField" [(ngModel)]="logininfo.password" />
  </igx-input-group>

  <igx-checkbox name="rememberme" [(ngModel)]="logininfo.rememberMe">
    Remember me
  </igx-checkbox>

  <button igxButton="outlined"
          class="submit-button space-out"
          [disabled]="!userLogin.touched || !userLogin.valueChanges || userLogin.invalid || submitInProgress">
    Login
  </button>
</form>
```

**Comment by simeonoff** [comment] 2020-07-07 08:34
@kdinev This should be a separate issue that is solely handled by modifying the existing input group theme.

**Comment by kdinev** [comment] 2020-07-07 10:59
@simeonoff I wanted to post it here, since it's related to autofill. @EvgeniyZhukovets I guess if you implement this with `ngModel` or `FormGroup` then you wouldn't experience this issue anymore.

**Comment by EvgeniyZhukovets** [comment] 2020-07-13 12:30
@kdinev I implemented ngModel. Just removed it from 'Steps to reproduce'. Still have this issue.

**Comment by kdinev** [comment] 2020-07-13 14:13
@EvgeniyZhukovets Strange that I don't see such an issue under Chrome. I'm using 10.0.3.

**Comment by kdinev** [comment] 2020-07-22 12:14
@EvgeniyZhukovets I managed to reproduce your issue as well. When I land directly on the route with the autofill values in the form, and no change detection has been ran yet, then Angular cannot determine that there's been a value change. Upon any change detection, the label positions correctly. I suggest you call `cdr.detectChanges()` in your component on `ngAfterViewInit()` and the issue should go away!

**Comment by simeonoff** [comment] 2020-09-23 08:39
Closing due to inactivity.

**Closed by simeonoff** 2020-09-23 08:39 UTC
Labels: bug, input, input-group, severity: medium, status: in-review, version: 10.0.x, version: 9.0.x
