### ISSUE TITLE
Grid layout changes, the toolbar taking the available height, while the body shrinks

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular#9331] opened 2021-04-15 10:49 UTC
* igniteui-angular version: 
 * browser: 

## Steps to reproduce  

1. Open Row Pinning dev demo
2. Open the pinning actions dialog from the toolbar
3. Try to scroll the grid horizontally either with the mouse or doing shift + mouse wheel

## Result  
Grid layout changes, the toolbar taking the available height, while the body shrinks:
![image](https://user-images.githubusercontent.com/14248932/114857540-0f0b2580-9df1-11eb-9bd7-410e5b143dd5.png)

## Expected result  
Grid layout to stay fixed and not change in this way

Attach a sample if available, and screenshots, if applicable.

**Comment by mddragnev** [comment] 2021-04-26 13:02
Hello @hanastasov,
Which version of the product were you using. I cannot reproduce the issue in master branch. Current behavior is: once you start scrolling horizontally the toolbar closes.

**Comment by hanastasov** [comment] 2021-04-26 13:49
Could not reproduce it now on master.

**Comment by mddragnev** [comment] 2021-04-26 13:53
Ok, closing the issue as already fixed

**Comment by hanastasov** [comment] 2021-05-10 06:44
> This is still happening with me, I am using version 11.1.0, it doesn't happen to all my grids, but still happens, I think the more columns you have on the grid, more likely is this to happen, I had like 10 + columns and it was shifting the `aria-hidden` would only change to false if the mouse either hover the object or clicked outside the grid.

Thanks for this feedback @DeniseCP. I reopened the issue so that we have a look and try to reproduce it again using your information.

**Comment by mddragnev** [comment] 2021-05-17 14:08
Hello @DeniseCP,
Even though you gave us additional information I still cannot reproduce this issue. I have been trying with version 11.1.0 and 14 columns. I have created a stackblitz sample. Could you please try and reproduce this behavior? Let me know the exact steps if you manage to.

**Comment by hanastasov** [comment] 2021-05-17 14:42
Hello @DeniseCP, could you please confirm the exact version you use, where the issue is reproduced?

**Comment by DeniseCP** [comment] 2021-05-17 15:56
> Hello @DeniseCP, could you please confirm the exact version you use, where the issue is reproduced?

![image](https://user-images.githubusercontent.com/9079225/118519287-d4e1bc00-b6ed-11eb-8b1b-a00dfbd807da.png)

**Comment by DeniseCP** [comment] 2021-05-17 16:09
> Hello @DeniseCP,
> Even though you gave us additional information I still cannot reproduce this issue. I have been trying with version 11.1.0 and 14 columns. I have created a stackblitz sample. Could you please try and reproduce this behavior? Let me know the exact steps if you manage to. [sample](https://stackblitz.com/edit/github-sx4azh?file=src/app/grid/grid-row-pinning/grid-row-pinning.component.html)

Hi, I checked the stackblitz, you are right it doesn't happen there. It's weird on my end as well, it happens for just one table I have. not all. You can go ahead and close, since you cannot reproduce, I will upgrade when v-12 is ready, and check if the problem is gone. Thanks for the help anyways.

**Closed** 2021-05-17 16:29 UTC
Labels: awaiting author, bug, grid: general, grid: toolbar, priority: high, scroll, scrollbar, severity: medium

**Comment by ricardosaracino** [comment] 2021-07-13 16:44
Well, i just encountered this problem myself. ill try to reproduce on stackblitz 


![image](https://user-images.githubusercontent.com/759253/125492231-ffd81eda-5357-4224-a14e-9b66ea55efd8.png)

```typescript
"dependencies": {
    "@angular/animations": "^12.0.1",
    "@angular/cdk": "^12.0.0",
    "@angular/common": "^12.0.1",
    "@angular/compiler": "^12.0.1",
    "@angular/core": "^12.0.1",
    "@angular/forms": "^12.0.1",
    "@angular/material": "^12.0.0",
    "@angular/platform-browser": "^12.0.1",
    "@angular/platform-browser-dynamic": "^12.0.1",
    "@angular/platform-server": "^12.0.1",
    "@angular/router": "^12.0.1",
    "@infragistics/igniteui-angular": "^12.0.0",
    "@infragistics/igniteui-dockmanager": "^1.2.0",
    "@ngrx/effects": "^12.0.0",
    "@ngrx/router-store": "^12.0.0",
    "@ngrx/schematics": "^12.0.0",
    "@ngrx/store": "^12.0.0",
    "@ngrx/store-devtools": "^12.0.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/hammerjs": "^2.0.36",
    "ajv": "^6.9.1",
    "angular-mentions": "^1.1.6",
    "bootstrap": "^3.4.1",
    "core-js": "^2.6.4",
    "hammerjs": "^2.0.8",
    "highcharts": "^6.1.0",
    "intl": "^1.2.5",
    "jquery": "^3.4.1",
    "jquery-ui-dist": "^1.12.1",
    "jszip": "^3.1.5",
    "lodash.groupby": "^4.6.0",
    "lodash.isequal": "^4.5.0",
    "lodash.pick": "^4.4.0",
    "lodash.uniqby": "^4.7.0",
    "minireset.css": "^0.0.7",
    "moment": "^2.21.0",
    "ngx-permissions": "^7.0.3",
    "rxjs": "^6.5.4",
    "rxjs-compat": "^6.4.0",
    "tslib": "^2.0.0",
    "web-animations-js": "^2.3.2",
    "zone.js": "~0.11.4"
  },
```

**Comment by hanastasov** [comment] 2021-07-26 07:40
@ricardosaracino, did you get any success reproducing it on stackblitz?

**Comment by ricardosaracino** [comment] 2021-07-26 23:18
I gave it a shot but couldnt reproduce. This is the defective code below. If i ever track down the problem i will report back.

https://stackblitz.com/edit/github-gymlyx?file=src%2Fapp%2Fgrid%2Fgrid-column-hiding-toolbar-sample%2Fgrid-column-hiding-toolbar-sample.component.html

``` html
<div class="titan-data-grid h-70">
  <igx-grid #securityPricesListGrid [data]="securityPricesData" [height]="importStdFile.value ? '95%' : '100%'"
            [columnPinning]="true" [allowFiltering]="true" [hideRowSelectors]="true" [rowSelection]="'single'"
            [clipboardOptions]="clipboardOptions" [addRowEmptyTemplate]="addRowTamplate" [rowEditable]="true"
            [primaryKey]="'id'" (cellEdit)="onCellEditDone($event)" (cellEditEnter)="onCellEditEnter()">

    <!-- TODO https://github.com/IgniteUI/igniteui-angular/issues/9331 -->
    <!--igx-grid-toolbar>
      <igx-grid-toolbar-actions>
        <igx-grid-toolbar-hiding></igx-grid-toolbar-hiding>
      </igx-grid-toolbar-actions>
    </igx-grid-toolbar-->

    <igx-column field="securityCode" [header]="'LABELS.CODE' | translate" [dataType]="'string'"
                [editable]="false" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
    </igx-column>
    <igx-column field="securityShortName" [header]="'LABELS.SHORT_NAME' | translate" [dataType]="'string'"
                [editable]="false" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate" [hidden]="true">
    </igx-column>
    <igx-column field="date" [header]="'LABELS.LAST_PRICE_DATE' | translate" [dataType]="'string'"
                [editable]="false" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
      <ng-template igxCell let-value>{{ value | date:'yyyy-MM-dd' }}</ng-template>
    </igx-column>
    <igx-column field="currencyShortName" [header]="'* ' + ('LABELS.CURRENCY' | translate)" [dataType]="'string'"
                [editable]="true" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
    </igx-column>

    <igx-column field="bid" [header]="'* ' + ('LABELS.BID' | translate)" [dataType]="'string'"
                [editable]="true" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
      <ng-template igxCell let-value
                   let-cell="cell">{{ value | number:'.' + cell.rowData.securityRounding.pricingPrecision }}</ng-template>
    </igx-column>
    <igx-column field="ask" [header]="'* ' + ('LABELS.ASK' | translate)" [dataType]="'string'"
                [editable]="true" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
      <ng-template igxCell let-value
                   let-cell="cell">{{ value | number:'.' + cell.rowData.securityRounding.pricingPrecision }}</ng-template>
    </igx-column>
    <igx-column field="lastTrade" [header]="'* ' + ('LABELS.LAST_TRADE' | translate)" [dataType]="'string'"
                [editable]="true" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
      <ng-template igxCell let-value
                   let-cell="cell">{{ value | number:'.' + cell.rowData.securityRounding.pricingPrecision }}</ng-template>
    </igx-column>
    <igx-column field="closing" [header]="'* ' + ('LABELS.CLOSING' | translate)" [dataType]="'string'"
                [editable]="true" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
      <ng-template igxCell let-value
                   let-cell="cell">{{ value | number:'.' + cell.rowData.securityRounding.pricingPrecision }}</ng-template>
    </igx-column>

    <igx-column field="bidChange" [header]="'LABELS.BID_CHANGE' | translate" [dataType]="'string'"
                [editable]="false" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate" [hidden]="true">
      <ng-template igxCell let-value>{{ value | number:'.2-2' }}%</ng-template>
    </igx-column>
    <igx-column field="askChange" [header]="'LABELS.ASK_CHANGE' | translate" [dataType]="'string'"
                [editable]="false" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate" [hidden]="true">
      <ng-template igxCell let-value>{{ value | number:'.2-2' }}%</ng-template>
    </igx-column>
    <igx-column field="lastTradeChange" [header]="'LABELS.LAST_CHANGE' | translate" [dataType]="'string'"
                [editable]="false" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
      <ng-template igxCell let-value>{{ value | number:'.2-2' }}%</ng-template>
    </igx-column>
    <igx-column field="closingChange" [header]="'LABELS.CLOSING_CHANGE' | translate" [dataType]="'string'"
                [editable]="false" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
      <ng-template igxCell let-value>{{ value | number:'.2-2' }}%</ng-template>
    </igx-column>

    <igx-column field="status" [header]="'LABELS.STATUS' | translate" [dataType]="'string'"
                [editable]="false" [hasSummary]="false" [sortable]="true" [movable]="true" [resizable]="true"
                [filterCellTemplate]="textFilterTemplate">
      <ng-template igxCell let-value>{{ value }}</ng-template>
    </igx-column>
    <igx-column field="id" [header]="'LABELS.ACTION' | translate" width="90px" [dataType]="'string'"
                [editable]="false"
                [filterable]="false" [hasSummary]="false" [sortable]="false" [movable]="false" [resizable]="true">
      <ng-template igxCell let-cell="cell">
        <div class="w-100 text-center action-show-when-hover">
          <button *ngIf="!cell.row.inEditMode && cell.rowData.status === 'OPEN'" igxButton="icon"
                  igxRipple="white" igxButtonColor="#28a745" [igxRippleCentered]="true"
                  [igxTooltipTarget]="commitTooltipRef" (click)="doCommitPrice(cell.rowData)">
            <igx-icon>check</igx-icon>
          </button>
          <button *ngIf="!cell.row.inEditMode && cell.rowData.status === 'COMMITTED'" igxButton="icon"
                  igxRipple="white" igxButtonColor="#28a745" [igxRippleCentered]="true"
                  [igxTooltipTarget]="uncommitTooltipRef" (click)="doUncommitPrice(cell.rowData)">
            <igx-icon>swap_vert</igx-icon>
          </button>
        </div>
      </ng-template>
    </igx-column>

    <ng-template igxRowEditText let-rowChangesCount></ng-template>
    <ng-template let-column="column" igxRowEditActions let-endRowEdit>
      <div class="custom-buttons">
        <button igxButton="icon" class="custom-button" igxRowEditTabStop (click)="endRowEdit(false)">
          <igx-icon>clear</igx-icon>
        </button>
        <button igxButton="icon" class="custom-button" igxRowEditTabStop (click)="endRowEdit(true)">
          <igx-icon>check</igx-icon>
        </button>
      </div>
    </ng-template>
  </igx-grid>
  <div class="row">
    <div class="col-xs-5">
      <igx-hint>
        <span class="grid-footer-hint-message">{{ 'MESSAGES.COLUMNS_EDITABLE' | translate}}</span>
      </igx-hint>
    </div>
  </div>

  <span #commitTooltipRef="tooltip" igxTooltip class="default-tooltip-style">{{'LABELS.COMMIT' | translate }}</span>
  <span #uncommitTooltipRef="tooltip" igxTooltip
        class="default-tooltip-style">{{'LABELS.SET_PRICE_TO_OPEN' | translate }}</span>

  <ng-template #addRowTamplate></ng-template>
  <ng-template #textFilterTemplate igxFilterCellTemplate let-column="column">
    <div class="filter-cell">
      <igx-input-group #inputGr class="filter-input" type="box" [displayDensity]="'compact'">
        <igx-prefix>
          <igx-icon>search</igx-icon>
        </igx-prefix>
        <input #input igxInput tabindex="0" [placeholder]="'LABELS.FILTER' | translate" autocomplete="off"
               [value]="getFilterValue(column)" (input)="onApplyFilter(input, column)" (click)="onClick(inputGr)"
               (keydown)="onKeyDown($event)"/>
        <igx-suffix *ngIf="input.value || input.value === 0" (click)="clearInput(column)" tabindex="0">
          <igx-icon>clear</igx-icon>
        </igx-suffix>
      </igx-input-group>
    </div>
  </ng-template>
</div>
```
