### ISSUE TITLE
Error thrown when clearing search in Excel Style Filter input

### ISSUE THREAD

**Issue by skrustev** [IgniteUI/igniteui-angular#6133] opened 2019-11-06 15:22 UTC
## Description  
Error thrown when clearing the value for the Excel Style Filter search input by pressing the 'clear' button or simply deleting it.

 * igniteui-angular version: 9.0.x
 * browser: any

## Steps to reproduce  

1. Open "grid-excel-style-filtering-sample-1" sample in "igniteui-samples"
2. Open the excel style filtering dialog for the first column
3. Search by "dat"
4. Clear the search either by clicking on the 'x' button or using "Backspace"
5. Error is thrown:

## Result  
The following error is thrown:
ERROR NullInjectorError: R3InjectorError(GridsModule)[IgxListBaseDirective -> IgxListBaseDirective -> IgxListBaseDirective -> IgxListBaseDirective]: 
  NullInjectorError: No provider for IgxListBaseDirective!

## Expected result  
There should be no error when clearing the search input.

**Comment by astaev** [comment] 2019-11-27 14:29
Cannot reproduce it. You can try it on your machine with **astaev/chartsRemove** branch.

**Comment by DiyanDimitrov** [comment] 2019-12-04 12:47
@skrustev Could you try if you are still able to reproduce this issue? If not, we can close it.

**Comment by skrustev** [comment] 2019-12-12 14:16
@DiyanDimitrov I can no longer reproduce it as well so it can be closed

**Closed** 2019-12-12 14:24 UTC
Labels: bug, excel-style-filtering, ivy, status: cannot-reproduce, version: 9.0.x
