### ISSUE TITLE
Issue on rowEdit cancel in cells (with edit templates) of new row

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular#9703] opened 2021-06-11 12:03 UTC
## Description  
When rowEdit event is canceled and the user adds a new row with edit templates in some cells, on 'Done' button click the value of the last edited cell with some edit template disappears.

 * igniteui-angular version: 12.1

## Steps to reproduce  

1. Open [this](https://stackblitz.com/edit/igx-grid-cancel-rowedit-on-new-row-issue?file=src/app/grid/grid-add-row-sample/grid-add-row-sample.component.html) sample
2. Add a new row
3. Choose a value from the autocomplete into the ProductName column (or enter some number into the next column)
4. Click on 'Done' button

## Result  
The value disappears

## Expected result  
The value should still be visible in the cell just like when a row in the data is edited

**Comment by radomirchev** [comment] 2021-06-16 11:38
@teodosiah the issue is included in the next sprint planning. You could expect the fixe to be included in the patch scheduled for 06 Jul.

**Comment by ChronosSF** [comment] 2021-06-21 11:13
@teodosiah , could you please confirm this can be fixed just for 12.0 and master? 

There seems to have been some refactoring done for 12.0 so we may need to fix it "twice" if we want this to be released in 11.1 as well. I prefer to avoid that if possible.

**Comment by teodosiah** [comment] 2021-06-22 04:59
Actually, the customer is using 11.1 and he needs the fix to be included in it too.

**Closed** 2021-06-25 10:24 UTC
Labels: bug, grid: row-adding, grid: row-editing, status: resolved, version: 12.1.x
