### ISSUE TITLE
Calendar - Selecting year/month does not update the calendar header.

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#8243] opened 2020-09-30 12:57 UTC
## Description  
Selecting a year or month in the calendar view does not update the calendar header.

 * igniteui-angular version: 10.2.x
 * browser: all

## Steps to reproduce  

1. Open calendar sample in dev demos
2. Scroll to a calendar that has a header enabled.
3. Change the month or a year and observe the header.

## Result  
The header stays at the current date.

## Expected result  
The header should update with the newly selected month/year.

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by zdrawku** [comment] 2020-11-02 08:29
Hey @desig9stein isn't that going to be addressed with the [A11y changes](https://github.com/IgniteUI/igniteui-angular/pull/8335)?

**Comment by desig9stein** [comment] 2020-11-02 08:48
> Hey @desig9stein isn't that going to be addressed with the [A11y changes](https://github.com/IgniteUI/igniteui-angular/pull/8335)?

No, as far as I remember we agree upon making a separate issue for that.

**Comment by ddincheva** [comment] 2021-01-06 13:05
Hello all,
I managed to investigate the described issue and this behavior is by design.  The date that is displayed in the header is corresponding to the selected date in the calendar/[Material Specification](https://material.io/components/date-pickers#anatomy)/. The selected date is not affected by changing the view date. If no date is selected as a default value is the current date/today/.
So this issue either should be closed as by-design or maybe have further discussion should we introduce a behavior change.

**Comment by zdrawku** [comment] 2021-01-07 10:18
Thank you Marin for keeping track of the issues that needed to be clarified.
I agree with Desislava, we are not changing the selected date with year/month view navigation OR based on the active date. The actual change happen only when a new Date is selected, hence the header is updated. 

@radomirchev @StefanIvanov, in my opinion we should leave the current behavior as is and mark the issue as `by-design`.

![Uploading calendar.gif…]()

**Comment by StefanIvanov** [comment] 2021-01-07 10:35
I agree with @ddincheva and @zdrawku and since it is not a bug, I would like to ask @radomirchev if he sees this as a potential enhancement

**Comment by radomirchev** [comment] 2021-01-11 08:58
As @ddincheva stated, the current behavior is according the Material design and the issue have to be labeled as `by-design`. I do not see added value in enhancement here.

**Closed by radomirchev** 2021-01-11 08:58 UTC
Labels: bug, calendar, status: in-review, version: 10.2.x
