### ISSUE TITLE
Extend rowDeleted event arguments

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-angular#12380] opened 2022-11-25 12:10 UTC
## Is your feature request related to a problem? Please describe.
Right now, `rowDeleted` emits `IRowDataEventArgs`. This argument has no information about the id of the deleted row.

## Describe the solution you'd like
Extend the `rowDeleted` event arguments to include at least the deleted row id.

## Describe alternatives you've considered
I can search through the grid's data and find the row id, but it is common scenario to send to the backend the id of the item you need to delete. This is why it should present in the event arguments.

**Comment by hanastasov** [comment] 2022-11-28 09:55
Currently, task  https://github.com/IgniteUI/igniteui-angular/issues/12371 is being implemented to make the grid API consistent and always expose the row data , instead of the primary key value.

Considering this, it does not make sense to expose a new property in `IRowDataEventArgs`, which would be a duplicate of `data`:
![image](https://user-images.githubusercontent.com/14248932/204248134-4623294f-6a86-48bf-8b2a-33f80b4026d9.png)

**Closed** 2023-03-10 05:04 UTC
Labels: :toolbox: feature-request, grid: row-editing, :runner: priority: high, version: 15.1.x, :crown:  app-builder
