### ISSUE TITLE
cellEdit event is not emitted when cell value is not modified

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular#9668] opened 2021-06-07 07:54 UTC
## Description  
When the user enters edit mode of a specific cell and exits it without modifying the value, the `cellEdit` event is not emitted. This becomes an issue when validation logic is executed at this stage.

 * igniteui-angular version: 11.1.x, 12.0.x
 * browser: any

## Steps to reproduce  
1. Open the following [sample](https://stackblitz.com/edit/github-cell-edit-validation)
2. Double click on the Product Name cell within the first row
3. Without modifying its value press Tab

### Another scenario
1. Within the same sample add a new row through the action strip
2. Again enter edit mode for the Product name cell and press Tab without modifying its value

## Result  
The value is submitted.

## Expected result  
The value should not be submitted since there is a validation applied against empty cell values.

## NOTE
The following conditional check within both methods update_cell and update_add_cell (api.service.ts) prevents the emitting of the `cellEdit` event when the user exits edit mode without modifying the cell value.
` if (isEqual(args.oldValue, args.newValue)) {​return args; }​`

## Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Aleksandyr** [comment] 2021-06-14 11:48
@mmart1n  That is the expected behavior, which IMO it is not a bug.
As it is described in the documentation. [cellEdit](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing#event-arguments-and-sequence) is emitted only when the value has been changed.
@damyanpetev could you please give your opinion on that matter?

**Comment by damyanpetev** [comment] 2021-06-17 10:45
@mmart1n , @Aleksandyr  Is correct, the point of the edit event is to inform the user has made changes, otherwise there's no `newValue` to speak of and every app running update logic would have to check if there's an actual change behind each event. So yeah, by design `cellEdit` should emit when a change has been made, otherwise you get enter and exit events.

For the main scenario, if the validation logic is supposed to keep the data in the grid valid, then if the user made no changes - then the original data remains, which by presumption should already be valid, since it wasn't touched by the user, right? If the state of the data before edit is already invalid I think there might be an issue elsewhere, since the data loaded in that state (likely from backend), which shouldn't happen if it's being validated. So in this case "Result: The value is submitted." is not totally correct, since no data is submitted at all. 

As for the second scenario, I see your point, but it's _row_ add and even if you don't get specific cell edits, you should get the entire row edit event which is the most reasonable place to validate that atm.

I realize this complicates the validation handling a bit and the edit events are less-than-ideal for that purpose and we're aware of that. There's a feature request for integrated validation support already logged - https://github.com/IgniteUI/igniteui-angular/issues/6501

**Comment by Aleksandyr** [comment] 2021-06-17 10:56
@damyanpetev @mmart1n considering that fact, we can link this issue to #6501 and close it as not a bug?

**Comment by Aleksandyr** [comment] 2021-06-21 07:13
Closing that issue as by design.

**Closed by Aleksandyr** 2021-06-21 07:13 UTC
Labels: bug, grid: cell-editing, grid: general, status: by-design
