### ISSUE TITLE
ERROR in IgxNumberFormatSpecifier cannot be used as an entry component.

### ISSUE THREAD

**Issue by matpinsdorf** [IgniteUI/igniteui-angular#8386] opened 2020-10-16 01:03 UTC
## Description  

Hi  , i updated my aplication to angular 10 and updated igniteui-angular to the latested version, now i cant build it anymore, i got the follwing error: "ERROR in IgxNumberFormatSpecifier cannot be used as an entry component." but i dont know what or where is this "IgxNumberFormatSpecifier ", before the update when i was using angular 9 and a previous version of  igniteui-angular everything was right.

 * igniteui-angular version: 
     10.2.0-beta.1

![image](https://user-images.githubusercontent.com/57017667/96200921-a02c3d00-0f31-11eb-8b18-5a50fbc0dd23.png)

**Comment by gmurray81** [comment] 2020-10-18 21:23
@matpinsdorf are you loading one of our *Dynamic modules?

**Comment by matpinsdorf** [comment] 2020-10-19 05:32
> @matpinsdorf are you loading one of our *Dynamic modules?

iam not sure .... 
we are using several infragiscs components including" igniteui-angular-charts"

**Comment by gmurray81** [comment] 2020-10-20 15:44
If you look in your app module, or other modules in your application, you should see one or more of our modules imported.
I suspect one of those will end in `DynamicModule`. A few of those may have a regression issue in the current version.

The good news is that those are for very edge case scenarios that may not pertain to your application, and you can probably just import the version that ends in `Module` instead of `DynamicModule`, unless you have one of those very specific scenarios.

**Comment by matpinsdorf** [comment] 2020-10-20 17:34
hi @gmurray81  thanks for the help, but i looked in all of our modules and we are not using any DynamicModule, the only place i see imports using then is inside igniteui-angular-charts.

**Comment by gmurray81** [comment] 2020-10-21 21:07
Hmm.... could you tell me which imports you do have in your App module? In terms of things from our packages?

**Comment by matpinsdorf** [comment] 2020-10-22 02:01
Sure !

here is all of our "igniteui-angular" and "igniteui-angular-charts"  imports , we are not importing then in App Module, we are importing then in a specific module:

import {     IgxMaskModule, 
                  IgxGridModule, 
                  IgxTreeGridModule,
                  getCurrentResourceStrings, 
                  changei18n } 
from 'igniteui-angular';



import { 
        IgxCategoryChartModule, 
        IgxPieChartModule,
        IgxDoughnutChartModule,
        IgxDataChartCoreModule,
        IgxDataChartCategoryModule,
        IgxLegendModule,
        IgxItemLegendModule,
        IgxDataChartInteractivityModule,
        IgxDataChartStackedModule,
        IgxDataChartPolarCoreModule,
        IgxDataChartPolarModule,
        IgxDataChartRadialCoreModule,
        IgxDataChartRadialModule,
        IgxDataChartScatterCoreModule,
        IgxDataChartScatterModule,
        IgxBarSeriesComponent,
        IgxStackedBarSeriesComponent,
        IgxStackedColumnSeriesComponent,
        IgxStackedAreaSeriesComponent,
        IgxStacked100AreaSeriesComponent,
        IgxStacked100BarSeriesComponent,
        IgxStacked100ColumnSeriesComponent,
        IgxStackedLineSeriesComponent,
        IgxStacked100LineSeriesComponent,
        IgxStackedSplineAreaSeriesComponent,
        IgxStacked100SplineAreaSeriesComponent,
        IgxStackedSplineSeriesComponent,
        IgxStacked100SplineSeriesComponent,
        IgxRingSeriesComponent,
        IgxCategoryXAxisComponent,
        IgxCategoryYAxisComponent,
        IgxNumericXAxisComponent,
        IgxNumericYAxisComponent,
        IgxCategoryAngleAxisComponent,
        IgxNumericAngleAxisComponent,
        IgxNumericRadiusAxisComponent,
        IgxCalloutLayerComponent,
        IgxPieChartComponent,
        IgxAreaSeriesComponent,
        IgxColumnSeriesComponent,
        IgxLineSeriesComponent,
        IgxPointSeriesComponent,
        IgxSplineAreaSeriesComponent,
        IgxSplineSeriesComponent,
        IgxStepAreaSeriesComponent,
        IgxStepLineSeriesComponent,
        IgxWaterfallSeriesComponent,
        IgxPolarScatterSeriesComponent,
        IgxPolarLineSeriesComponent,
        IgxPolarAreaSeriesComponent,
        IgxPolarSplineSeriesComponent,
        IgxPolarSplineAreaSeriesComponent,
        IgxRadialLineSeriesComponent,
        IgxRadialColumnSeriesComponent,
        IgxRadialPieSeriesComponent,
        IgxRadialAreaSeriesComponent,
        IgxRangeAreaSeriesComponent,
        IgxRangeColumnSeriesComponent,
        IgxScatterSeriesComponent,
        IgxScatterLineSeriesComponent,
        IgxScatterSplineSeriesComponent,
        IgxBubbleSeriesComponent,
    } from 'igniteui-angular-charts';

**Comment by zdrawku** [comment] 2020-10-26 08:15
@matpinsdorf I want to be sure that the issue still persists in the official 10.2.0 version, as I see that when you logged it, you were using beta.1

**Comment by gmurray81** [comment] 2020-10-26 13:05
@matpinsdorf I believe I know what the underlying issue is, but I'm not really sure why you would be hitting it for your scenario.

I was actually asking which of our modules you had added to the imports collection of your app's NGModules,

**Comment by gmurray81** [comment] 2020-10-26 13:10
ah or are you not using explicit modules?

**Comment by matpinsdorf** [comment] 2020-10-26 13:50
@zdrawku everything is updated, but 
unfortunately the error persists 
![image](https://user-images.githubusercontent.com/57017667/97180567-ff335280-1778-11eb-8aab-a0305f361769.png)

**Comment by matpinsdorf** [comment] 2020-10-26 13:53
@gmurray81 
![image](https://user-images.githubusercontent.com/57017667/97180941-7963d700-1779-11eb-84e5-8771c42737cd.png)
![image](https://user-images.githubusercontent.com/57017667/97180972-85e82f80-1779-11eb-819e-9fd1d40c46ca.png)

**Comment by gmurray81** [comment] 2020-10-26 16:05
Thanks @matpinsdorf, that should give us enough info to reproduce the issue, and I might be able to get you a work around faster than we can get an update out there.

**Comment by gmurray81** [comment] 2020-10-26 16:49
Hmm... I'm still unable to reproduce the issue. @matpinsdorf could you tell me more details about what version of angular and angular compiler you are using? Anything special about the build toolchain?

I can proceed with resolving what I assume to be the issue, but I'm still confused as to why you are running into it at all, as it doesn't seem like you should be hitting it.

**Comment by matpinsdorf** [comment] 2020-10-26 21:45
hi @gmurray81 were are using this versions now 👍:

![image](https://user-images.githubusercontent.com/57017667/97232054-417d8380-17bb-11eb-8a67-912aa6835d5c.png)

but the problem started when upgraded from version 9 to 10.

**Comment by gmurray81** [comment] 2020-11-18 22:02
This should be fixed in the next package.

**Closed by gmurray81** 2020-11-18 22:02 UTC
Labels: bug, status: in-review
