### ISSUE TITLE
Implement Display Density for the IgxDropDownComponent

### ISSUE THREAD

**Issue by tachojelev** [IgniteUI/igniteui-angular#4851] opened 2019-05-21 07:02 UTC
## Is your feature request related to a problem? Please describe.
In order to support the display density for the Excel Style Filtering across all its sub-components and sub-dialogs, we need IgxDropDown to implement the display density functionality.

## Describe the solution you'd like
Either the dropdown component or its dropdown-item components (or both) should probably extend the DisplayDensityBase class.

## Describe alternatives you've considered
N/A

## Additional context

![image](https://user-images.githubusercontent.com/12784974/58074967-2c0c2f00-7baf-11e9-9b03-721d3e62bd2e.png)

**Comment by ViktorSlavov** [comment] 2019-05-21 08:26
Duplicate of https://github.com/IgniteUI/igniteui-angular/issues/2960
Once we have a spec for display density in drop-down items, we will implement it for combo, drop-down and select items

**Closed by ViktorSlavov** 2019-05-21 08:26 UTC
Labels: dropdown, feature-request, status: in-review
