### ISSUE TITLE
Fluent and bootstrap igx-grid themes don't theme the expander border correctly when a row is active

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#7373] opened 2020-05-19 13:37 UTC
## Description  
If you focus a grid groupby row with fluent or bootstrap theme, you will see that the entire row, except the expander column gets a pinkish border.

 * igniteui-angular version: 9.1.0-alpha.latest
 * browser: N/A

## Steps to reproduce  

1. Open the sample browser on the live grid data sample. https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/live_data.html
2. Switch to fluent light or bootstrap light from the theming widget.
3. Focus a groupby row.

## Result  
No border is applied to the expander column.

## Expected result  
All of the elements in the row should get a border.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/82332815-8b816280-99ee-11ea-920d-cf3baa6c41c8.png)

**Comment by zdrawku** [comment] 2020-05-27 07:25
@kdinev @desig9stein this issue is fixed now. It was caused by simultaneous cache problems on the environment agents of angular-samples application along with failing "lob" build while the main angular-samples build was successful. We've improved the cache handling and build success ratio and this fixed the problem. Related [issue](https://github.com/IgniteUI/igniteui-angular-samples/pull/1965#issuecomment-629075673)

Screenshot of the styles and version mismatch:
![image](https://user-images.githubusercontent.com/11193764/82990154-68fdd380-a004-11ea-9abc-bd18349cb0c2.png)

**Closed by zdrawku** 2020-05-27 07:25 UTC
Labels: bootstrap-theme, bug, fluent-theme, grid, groupby, severity: medium, status: in-development
