### ISSUE TITLE
igx -grid - pinned columns are not visualized correctly if no width is set

### ISSUE THREAD

**Issue by SAndreeva** [IgniteUI/igniteui-angular#948] opened 2018-04-10 15:41 UTC
### Description  
Pinned columns are not visualized correctly if no width is set on that columns.

### Steps to reproduce  

1. Run the attached sample.
2. Observe how pinned columns are displayed.

### Result  
Header titles are not shown, no text is displayed - see the attached screenshot.

### Expected result  
Text is displayed on pinned columns, they are properly sized.

### Attachments  
![igxgrid](https://user-images.githubusercontent.com/7972965/38566895-8038dcce-3ced-11e8-957c-8e93217be224.png)
[igxgrid.zip](https://github.com/IgniteUI/igniteui-angular/files/1895263/igxgrid.zip)

**Comment by ChronosSF** [comment] 2018-04-10 16:31
@simeonoff - this might be because the flex rules don't work for items outside the display container. I was thinking of making it mandatory for the grid to have a horizontal scrollbar for pinning to be allowed (as in igGrid) which sort-of makes it required for all grid columns to have width so we may not handle this as a bug. @SlavUI  what do you think?

**Comment by SlavUI** [comment] 2018-04-10 16:42
@ChronosSF For it does not make sense to have Pinned columns for Grids that do not have horizontal scrolling. I agree that we should allow pinning on on Grid with horizontal scroll because the idea of the feature is to have the columns visible when scrolling horizontally

**Comment by ChronosSF** [comment] 2018-04-24 12:29
Duplicate of #1034

**Closed by ChronosSF** 2018-04-24 12:29 UTC
Labels: bug, grid, severity: medium, status: in-review
