### ISSUE TITLE
Misalignment of the Cells in the grid when Row Selection is enabled 

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular#3918] opened 2019-02-14 12:49 UTC
## Description  
Misalignment of the Cells in the grid when Row Selection is enabled 

 * igniteui-angular version: 7.2.x
 * browser: Chrome

## Steps to reproduce  

1. Open the infragistics website on the row selection demo enable row selection and resize the window, at one point the cells in the columns get misaligned 

## Expected result  
The cells should stay aligned under the respective columns 

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/33216749/52787816-bea8a980-3067-11e9-9a1d-07b917c33982.png)

**Comment by desig9stein** [comment] 2019-02-25 11:43
@SlavUI Is this on the live website or the staging? Since I can't find a sample with the name "row selection," can you specify the exact name of the sample or provide me an URL to it. Thanks!

**Comment by SlavUI** [comment] 2019-02-25 11:53
@desig9stein it is in Production

**Comment by desig9stein** [comment] 2019-02-26 08:27
I found that this is the commit that causes the issue:
[`Commit reference - fbb39da`](https://github.com/IgniteUI/igniteui-angular/commit/fbb39da2175db5a328c584f893ce9d8b1b6dac81)

@skrustev this is your commit, Can you check if you really need to add overflow: visible to the grid-display-container-tr?

**Comment by skrustev** [comment] 2019-03-05 09:57
@desig9stein 
It's set to `overflow: visible`, because the `igx-display-container` in general has `overflow: hidden`  which combined with the `width: 100%` sizes the row to the grid container but hides any cells that goes beyond and when scrolling horizontally there will be blank columns. 

Otherwise the only way I got this to reproduce is by zooming on the window which results in the cells not sizing correctly because they are set in percentages.

**Comment by desig9stein** [comment] 2019-03-14 14:48
@SlavUI the problem is not in the row selection, I am able to reproduce it without it. 
I don't think that this is a CSS issue, @simeonoff, @ChronosSF can you guys take a look at it?

**Comment by simeonoff** [comment] 2019-05-17 07:08
@ChronosSF @desig9stein Are we still experiencing this issue in the latest versions of the product? If not can we close this issue?

**Comment by Lipata** [comment] 2019-08-20 12:51
This is still reproducible:

1. Open [Selection demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection.html#grid-row-selection).
2. Maximize and Restore or Resize browser window.

**Closed** 2019-08-22 10:36 UTC
Labels: bug, grid, row-selection, severity: medium, status: resolved, version: 7.3.x, version: 8.1.x, version: 8.2.x
